/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-nestjs-open-redirect",
  bugClass: "novel",
  files: {
    ["src/nestjs-open-redirect.ts"]: "import { Controller, Get, Header, Redirect, Query } from '@nestjs/common';\nimport { AppService } from './app.service';\n\n@Controller()\nexport class AppController {\n  constructor(private readonly appService: AppService) {}\n\n  @Get('test')\n  @Redirect('https://docs.nestjs.com', 302)\n  getDocs1(@Query('input') userInput) {\n    if (userInput) {\n      // ruleid:nestjs-open-redirect\n      return { url: userInput };\n    }\n  }\n\n  @Get('test-ok')\n  @Redirect('https://docs.nestjs.com', 302)\n  getDocs2(@Query('input') userInput) {\n    return { url: 'https://docs.nestjs.com/v5/' };\n  }\n\n}\n",
  },
  bugReport: "Imported from semgrep rule 'nestjs-open-redirect': Untrusted user input in {url: ...} can result in Open Redirect vulnerability. metadata: cwe: - \"CWE-601: URL Redirection to Untrusted Site ('Open Redirect')\" category: security technology: - nestjs owasp: - A01:2021 - Broken Access Control - A01:2025 - Broken Access Control references: - https://owasp.org/Top10/A01_2021-Broken_Access_Control subcategory: - audit likelihood: LOW impact: MEDIUM conf (WARNING). Found at src/nestjs-open-redirect.ts line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'nestjs-open-redirect': Untrusted user input in {url: ...} can result in Open Redirect vulner",
        failureDescription: "Imported from semgrep rule 'nestjs-open-redirect': Untrusted user input in {url: ...} can result in Open Redirect vulnerability. metadata: cwe: - \"CWE-601: URL Redirection to Untrusted Site ('Open Red",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/nestjs-open-redirect.ts", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
