/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-detect-promptfoo",
  bugClass: "novel",
  files: {
    ["src/detect-promptfoo.ts"]: "// ruleid: detect-promptfoo\nimport promptfoo from 'promptfoo';\n\n// ruleid: detect-promptfoo\nconst results = await promptfoo.evaluate(testSuite, options);",
  },
  bugReport: "Imported from semgrep rule 'detect-promptfoo': Possibly found usage of AI tooling: promptfoo (INFO). Found at src/detect-promptfoo.ts line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'detect-promptfoo': Possibly found usage of AI tooling: promptfoo (INFO). Found at src/detect",
        failureDescription: "Imported from semgrep rule 'detect-promptfoo': Possibly found usage of AI tooling: promptfoo (INFO). Found at src/detect-promptfoo.ts line 1.",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/detect-promptfoo.ts", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
