/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-playwright-goto-injection",
  bugClass: "novel",
  files: {
    ["src/playwright-goto-injection.js"]: "const { chromium } = require('playwright');\n\nconst testFunc = async (userInput) => {\n  const browser = await chromium.launch();\n  const page = await browser.newPage();\n  let url = 'https://hardcoded.url.com'\n// ok\n  await page.goto('https://example.com');\n\n// ok\n  await page.goto(url);\n\n  // ruleid:playwright-goto-injection\n  await page.goto(unverifiedInput());\n\n  const newUrl = userInput;\n  // ruleid:playwright-goto-injection\n  await page.goto(newUrl);\n\n  await page.screenshot({path: 'example.png'});\n  await browser.close();\n};\n",
  },
  bugReport: "Imported from semgrep rule 'playwright-goto-injection': If unverified user data can reach the `goto` method it can result in Server-Side Request Forgery vulnerabilities metadata: owasp: - A10:2021 - Server-Side Request Forgery (SSRF) - A01:2025 - Broken Access Control cwe: - 'CWE-918: Server-Side Request Forgery (SSRF)' category: security technology: - playwright cwe2022-top25: true cwe2021-top25: true subcategory: - audit likelihood: LOW impact: LOW c (WARNING). Found at src/playwright-goto-injection.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'playwright-goto-injection': If unverified user data can reach the `goto` method it can resul",
        failureDescription: "Imported from semgrep rule 'playwright-goto-injection': If unverified user data can reach the `goto` method it can result in Server-Side Request Forgery vulnerabilities metadata: owasp: - A10:2021 - S",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/playwright-goto-injection.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
