/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-lazy-load-module",
  bugClass: "novel",
  files: {
    ["src/lazy-load-module.js"]: "// ok: lazy-load-module\nconst fs = require('fs')\n\nfunction smth() {\n  // ruleid: lazy-load-module\n  const mod = require('module-name')\n  return mod();\n}\n",
  },
  bugReport: "Imported from semgrep rule 'lazy-load-module': Lazy loading can complicate code bundling if care is not taken, also `require`s are run synchronously by Node.js. If they are called from within a function, it may block other requests from being handled at a more critical time. The best practice is to `require` modules at the beginning of each file, before and outside of any functions. languages: [javascript, typescript] severity: WARNING metadat (WARNING). Found at src/lazy-load-module.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'lazy-load-module': Lazy loading can complicate code bundling if care is not taken, also `req",
        failureDescription: "Imported from semgrep rule 'lazy-load-module': Lazy loading can complicate code bundling if care is not taken, also `require`s are run synchronously by Node.js. If they are called from within a functi",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/lazy-load-module.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
