/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-escape-function-overwrite",
  bugClass: "novel",
  files: {
    ["src/escape-function-overwrite.js"]: "// cf. https://github.com/janl/mustache.js/#include-templates\n\n// e.g., browser code:\n// ruleid: escape-function-overwrite\nMustache.escape = function(val) { return val; }\n\nfunction renderHello() {\n  var template = document.getElementById('template').innerHTML;\n  var rendered = Mustache.render(template, { name: 'Luke' });\n  document.getElementById('target').innerHTML = rendered;\n}\n\n// e.g., Node.js code:\nfunction node() {\n  const template = require(\"mustache\");\n  // ruleid: escape-function-overwrite\n  template.escape = (t) => { return t; }\n  let html = template.render(blogItem, { });\n}\n\nfunction ok() {\n  // ok: escape-function-overwrite\n  const template = require(\"mustache\");\n  let html = template.render(blogItem, { });\n}\n",
  },
  bugReport: "Imported from semgrep rule 'escape-function-overwrite': The Mustache escape function is being overwritten. This could bypass HTML escaping safety measures built into the rendering engine, exposing your application to cross-site scripting (XSS) vulnerabilities. If you need unescaped HTML, use the triple brace operator in your template: '{{{ ... }}}'. metadata: cwe: - \"CWE-79: Improper Neutralization of Input During Web Page Generation ('Cross-site Scrip (WARNING). Found at src/escape-function-overwrite.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'escape-function-overwrite': The Mustache escape function is being overwritten. This could by",
        failureDescription: "Imported from semgrep rule 'escape-function-overwrite': The Mustache escape function is being overwritten. This could bypass HTML escaping safety measures built into the rendering engine, exposing you",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/escape-function-overwrite.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
