/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-express-check-directory-listing",
  bugClass: "novel",
  files: {
    ["src/express-check-directory-listing.js"]: "const serveIndex = require('serve-index');\nvar express = require('express');\nvar app = express();\n\nvar serve = serveIndex('public/ftp', {\n    icons: true\n})\n\nvar server = http.createServer(function onRequest(req, res) {\n    var done = finalhandler(req, res)\n    // ruleid: express-check-directory-listing\n    serve(req, res, function onNext(err) {\n        if (err) return done(err)\n        index(req, res, done)\n    })\n})\n\n// ruleid: express-check-directory-listing\napp.use('/ftp', serveIndex('ftp', {\n    icons: true\n}));\n\n// ok\napp.use(bodyParser.text({\n    type: '*/*'\n}));\n",
  },
  bugReport: "Imported from semgrep rule 'express-check-directory-listing': Directory listing/indexing is enabled, which may lead to disclosure of sensitive directories (WARNING). Found at src/express-check-directory-listing.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'express-check-directory-listing': Directory listing/indexing is enabled, which may lead to d",
        failureDescription: "Imported from semgrep rule 'express-check-directory-listing': Directory listing/indexing is enabled, which may lead to disclosure of sensitive directories (WARNING). Found at src/express-check-directo",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/express-check-directory-listing.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
