/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-react-jwt-decoded-property",
  bugClass: "novel",
  files: {
    ["src/react-jwt-decoded-property.tsx"]: "import jwt_decode from \"jwt-decode\";\nimport { something } from \"foobar\";\n\nexport const testAuth1 = async (): Promise<void> => {\n  const { token } = await retrieveToken();\n  const decoded = jwt_decode<any>(token);\n// ruleid: react-jwt-decoded-property\n  const exp = decoded.exp * 1000;\n  return exp;\n};\n\nexport const okTestAuth1 = async (): Promise<void> => {\n  const { token } = await retrieveToken();\n// ok: react-jwt-decoded-property\n  const decoded = jwt_decode<any>(token);\n  foobar(decoded);\n};\n",
  },
  bugReport: "Imported from semgrep rule 'react-jwt-decoded-property': Property decoded from JWT token without verifying and cannot be trustworthy. metadata: cwe: - 'CWE-922: Insecure Storage of Sensitive Information' references: - https://pragmaticwebsecurity.com/articles/oauthoidc/localstorage-xss.html category: security owasp: - A01:2021 - Broken Access Control - A01:2025 - Broken Access Control technology: - react subcategory: - audit likelihood: LOW impact: LOW  (INFO). Found at src/react-jwt-decoded-property.tsx line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'react-jwt-decoded-property': Property decoded from JWT token without verifying and cannot be",
        failureDescription: "Imported from semgrep rule 'react-jwt-decoded-property': Property decoded from JWT token without verifying and cannot be trustworthy. metadata: cwe: - 'CWE-922: Insecure Storage of Sensitive Informati",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/react-jwt-decoded-property.tsx", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
