/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-grpc-nodejs-insecure-connection",
  bugClass: "novel",
  files: {
    ["src/grpc-nodejs-insecure-connection.js"]: "function test1() {\n    // ruleid: grpc-nodejs-insecure-connection\n    var grpc = require('grpc');\n\n    var booksProto = grpc.load('books.proto');\n\n    var client = new booksProto.books.BookService('127.0.0.1:50051', grpc.credentials.createInsecure());\n\n    client.list({}, function(error, books) {\n        if (error)\n            console.log('Error: ', error);\n        else\n            console.log(books);\n    });\n}\n\nfunction test2() {\n    // ruleid: grpc-nodejs-insecure-connection\n    var {credentials, load, Client} = require('grpc');\n\n    var creds = someFunc() || credentials.createInsecure();\n\n    var client = new Client('127.0.0.1:50051', creds);\n\n    client.list({}, function(error, books) {\n        if (error)\n            console.log('Error: ', error);\n        else\n            console.log(books);\n    });\n}\n\nfunction test3() {\n    // ruleid: grpc-nodejs-insecure-connection\n    var grpc = require('grpc');\n\n    var booksProto = grpc.load('books.proto');\n\n    var server = new grpc.Server();\n\n    server.addProtoService(booksProto.books.BookService.service, {});\n\n    server.bind('0.0.0.0:50051', grpc.ServerCredentials.createInsecure());\n    server.start();\n}\n\nfunction testOk1() {\n    // ok: grpc-nodejs-insecure-connection\n    var {credentials, Client} = require('grpc');\n    var channel_creds = credentials.createSsl(root_certs);\n    var client = new Client(address, channel_creds);\n\n    client.list({}, function(error, books) {\n        if (error)\n            console.log('Error: ', error);\n        else\n            console.log(books);\n    });\n}\n",
  },
  bugReport: "Imported from semgrep rule 'grpc-nodejs-insecure-connection': Found an insecure gRPC connection. This creates a connection without encryption to a gRPC client/server. A malicious attacker could tamper with the gRPC message, which could compromise the machine. metadata: owasp: - A08:2017 - Insecure Deserialization - A08:2021 - Software and Data Integrity Failures - A08:2025 - Software or Data Integrity Failures cwe: - 'CWE-502: Deserialization of Untrusted Da (ERROR). Found at src/grpc-nodejs-insecure-connection.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'grpc-nodejs-insecure-connection': Found an insecure gRPC connection. This creates a connecti",
        failureDescription: "Imported from semgrep rule 'grpc-nodejs-insecure-connection': Found an insecure gRPC connection. This creates a connection without encryption to a gRPC client/server. A malicious attacker could tamper",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/grpc-nodejs-insecure-connection.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
