/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-detect-angular-translateprovider-translations-method",
  bugClass: "novel",
  files: {
    ["src/detect-third-party-angular-translate.js"]: "var app = angular.module('MyApp', []);\napp.controller('myCtrl', function($scope, $sce) {\n    $translateSanitization.useStrategy();\n    var output = 'Hallo <b>{{name}}</b>';\n    // ruleid:detect-angular-translateprovider-translations-method\n    $translateProvider.translations('de', {output});\n    // ruleid:detect-angular-translateprovider-translations-method\n    $translateProvider.translations('de', {GREETING: 'Hallo <b>{{name}}</b>'});\n\n});\n",
  },
  bugReport: "Imported from semgrep rule 'detect-angular-translateprovider-translations-method': The use of $translateProvider.translations method can be dangerous if user input is provided to this API. metadata: cwe: - \"CWE-79: Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')\" references: - https://docs.angularjs.org/api/ng/service/$sce#trustAsUrl - https://owasp.org/www-chapter-london/assets/slides/OWASPLondon20170727_AngularJS.pdf category: security tech (WARNING). Found at src/detect-third-party-angular-translate.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'detect-angular-translateprovider-translations-method': The use of $translateProvider.transla",
        failureDescription: "Imported from semgrep rule 'detect-angular-translateprovider-translations-method': The use of $translateProvider.translations method can be dangerous if user input is provided to this API. metadata: c",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/detect-third-party-angular-translate.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
