/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-phantom-injection",
  bugClass: "novel",
  files: {
    ["src/phantom-injection.js"]: "const phantom = require('phantom');\n\n(async function() {\n  const instance = await phantom.create();\n  const page = await instance.createPage();\n  await page.on('onResourceRequested', function(requestData) {\n    console.info('Requesting', requestData.url);\n  });\n\n  // ruleid: phantom-injection\n  const status = await page.open(input());\n\n  // ok: phantom-injection\n  const status = await page.open('https://stackoverflow.com/');\n\n  const content = await page.property('content');\n  console.log(content);\n\n  await instance.exit();\n})();\n\n(async function(userInput) {\n  const instance = await phantom.create();\n  const page = await instance.createPage();\n  await page.on('onResourceRequested', function(requestData) {\n    console.info('Requesting', requestData.url);\n  });\n\n  // ruleid: phantom-injection\n  const status = await page.property('content', input());\n\n  // ruleid: phantom-injection\n  await page.setContent(userInput);\n\n  // ok: phantom-injection\n  var html = '<html>123</html>'\n  const status = await page.property('content', html);\n\n  const content = await page.property('content');\n  console.log(content);\n\n  await instance.exit();\n})();\n\n(async function(userInput) {\n  const instance = await phantom.create();\n  const page = await instance.createPage();\n  await page.on('onResourceRequested', function(requestData) {\n    console.info('Requesting', requestData.url);\n  });\n\n  // ruleid: phantom-injection\n  const status = await page.openUrl(input(), {}, {});\n\n  // ruleid: phantom-injection\n  await page.evaluateJavaScript(userInput);\n\n  // ok: phantom-injection\n  var url = 'https://stackoverflow.com/'\n  const status = await page.openUrl(url, {}, {});\n\n  const content = await page.property('content');\n  console.log(content);\n\n  await instance.exit();\n})();\n",
  },
  bugReport: "Imported from semgrep rule 'phantom-injection': If unverified user data can reach the `phantom` page methods it can result in Server-Side Request Forgery vulnerabilities metadata: owasp: - A10:2021 - Server-Side Request Forgery (SSRF) - A01:2025 - Broken Access Control cwe: - 'CWE-918: Server-Side Request Forgery (SSRF)' category: security technology: - phantom cwe2022-top25: true cwe2021-top25: true subcategory: - audit likelihood: LOW impact: (WARNING). Found at src/phantom-injection.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'phantom-injection': If unverified user data can reach the `phantom` page methods it can resu",
        failureDescription: "Imported from semgrep rule 'phantom-injection': If unverified user data can reach the `phantom` page methods it can result in Server-Side Request Forgery vulnerabilities metadata: owasp: - A10:2021 - ",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/phantom-injection.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
