/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-spawn-git-clone",
  bugClass: "novel",
  files: {
    ["src/spawn-git-clone.js"]: "function test1() {\n    const { spawn } = require('child_process');\n    function downloadGitCommit1(gitBranch, gitUrl, sourceCodePath) {\n        // ruleid: spawn-git-clone\n        const gitClone = spawn('git', [\n            'clone',\n            '--branch', gitBranch,\n            '--depth', '1',\n            gitUrl,\n            sourceCodePath\n        ]);\n        return gitClone;\n    }\n}\n\nfunction test2() {\n    const childProcess = require('child_process');\n    function downloadGitCommit2(req, res) {\n        // ruleid: spawn-git-clone\n        const gitClone = childProcess.spawn('git', [\n            'clone',\n            '--depth', '1',\n            req.body.gitUrl\n        ]);\n        return res.send('ok');\n    }\n}\n\nfunction test3() {\n    const childProcess = require('child_process');\n    function downloadGitCommit3(gitUrl) {\n        // ruleid: spawn-git-clone\n        const gitClone = childProcess.spawn('git', [ 'clone', gitUrl ]);\n        return res.send('ok');\n    }\n}\n\nfunction testOk1() {\n    const { spawn } = require('child_process');\n    function downloadGitCommitOk1() {\n        // ok: spawn-git-clone\n        const gitClone = spawn('git', [ 'clone', 'https://hardcoded-url.com' ]);\n        return res.send('ok');\n    }\n}\n\nfunction testOk2() {\n    const childProcess = require('child_process');\n    const gitUrl = 'https://hardcoded-url.com';\n    function downloadGitCommitOk2() {\n        // ok: spawn-git-clone\n        const gitClone = childProcess.spawn('git', [ 'clone', gitUrl ]);\n        return res.send('ok');\n    }\n}\n",
  },
  bugReport: "Imported from semgrep rule 'spawn-git-clone': Git allows shell commands to be specified in ext URLs for remote repositories. For example, git clone 'ext::sh -c whoami% >&2' will execute the whoami command to try to connect to a remote repository. Make sure that the URL is not controlled by external input. metadata: cwe: - \"CWE-78: Improper Neutralization of Special Elements used in an OS Command ('OS Command Injection')\" owasp: - A01:2017 - I (ERROR). Found at src/spawn-git-clone.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'spawn-git-clone': Git allows shell commands to be specified in ext URLs for remote repositor",
        failureDescription: "Imported from semgrep rule 'spawn-git-clone': Git allows shell commands to be specified in ext URLs for remote repositories. For example, git clone 'ext::sh -c whoami% >&2' will execute the whoami com",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/spawn-git-clone.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
