/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-js-open-redirect",
  bugClass: "novel",
  files: {
    ["src/open-redirect.js"]: "var hi = new URLSearchParams(window.location.search).get('gamer')\n\nvar hi1 = new URLSearchParams(window.location.search)\n\nvar hi2 = new URL(window.location.href)\n\nvar hi3 = new URL(location.href).searchParams.get('gamer');\n\nfunction test1(userInput) {\n    //ruleid:js-open-redirect\n    location.href = hi;\n    //ruleid:js-open-redirect\n    location.href = hi1.get('gamer');\n    //ruleid:js-open-redirect\n    location.href = hi2.searchParams.get('gamer');\n    //ruleid:js-open-redirect\n    location.href = hi3;\n}\n\n\nfunction test4(userInput) {\n    // ok:js-open-redirect\n    location.href = `https://www.hardcoded.place/${userInput}`\n    // ok:js-open-redirect\n    location.href = \"https://www.hardcoded.place/\" + userInput;\n}\n\n",
  },
  bugReport: "Imported from semgrep rule 'js-open-redirect': The application accepts potentially user-controlled input `$PROP` which can control the location of the current window context. This can lead two types of vulnerabilities open-redirection and Cross-Site-Scripting (XSS) with JavaScript URIs. It is recommended to validate user-controllable input before allowing it to control the redirection. options: interfile: true metadata: interfile: true cwe: -  (WARNING). Found at src/open-redirect.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'js-open-redirect': The application accepts potentially user-controlled input `$PROP` which c",
        failureDescription: "Imported from semgrep rule 'js-open-redirect': The application accepts potentially user-controlled input `$PROP` which can control the location of the current window context. This can lead two types o",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/open-redirect.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
