/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-sequelize-raw-query",
  bugClass: "novel",
  files: {
    ["src/sequelize-raw-query.js"]: "// Case1: run query by string concatenation using template literals\n// ruleid: sequelize-raw-query\ndb.sequelize.query(\n  `INSERT INTO user (username, password) VALUES('${username}','${password}')`\n)\n\n// Case 2: Build query by string concatenation using template literals\n// ruleid: sequelize-raw-query\nvar query = `INSERT INTO user (username, password) VALUES('${username}','${password}')`\nconsole.log(\"check password\");\ndb.sequelize.query(query)\n\n\n// Case 3: run query by string concatenation using + operator\n// ruleid: sequelize-raw-query\ndb.sequelize.query(\n  \"INSERT INTO user (username, password) VALUES('\" + username + \"','\" + password + \"')\"\n)\n\n// Case 4: Build query by string concatenation using + operator\n// ruleid: sequelize-raw-query\nvar query = \"INSERT INTO user (username, password) VALUES('\" + username + \"','\" + password + \"')\"\nconsole.log(\"check password\");\ndb.sequelize.query(query)\n",
  },
  bugReport: "Imported from semgrep rule 'sequelize-raw-query': Avoiding SQL string concatenation: untrusted input concatenated with raw SQL query can result in SQL Injection. Data replacement or data binding should be used. See https://sequelize.org/master/manual/raw-queries.html metadata: category: security technology: - sequelize cwe: - \"CWE-89: Improper Neutralization of Special Elements used in an SQL Command ('SQL Injection')\" owasp: - A01:2017 - Injecti (WARNING). Found at src/sequelize-raw-query.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'sequelize-raw-query': Avoiding SQL string concatenation: untrusted input concatenated with r",
        failureDescription: "Imported from semgrep rule 'sequelize-raw-query': Avoiding SQL string concatenation: untrusted input concatenated with raw SQL query can result in SQL Injection. Data replacement or data binding shoul",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/sequelize-raw-query.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
