/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-sequelize-tls-disabled-cert-validation",
  bugClass: "novel",
  files: {
    ["src/sequelize-tls-disabled-cert-validation.js"]: "\n// Example for mysql\nmodule.exports = {\n\n  // ruleid: sequelize-tls-disabled-cert-validation\n  dev: {\n    username: \"0xdbe\",\n    database: \"app_db\",\n    dialect: \"mariadb\",\n    host: \"127.0.0.1\",\n    dialectOptions: {\n      ssl: {\n        rejectUnauthorized: false\n      }\n    }\n  }\n};\n\n// Example for mysql\nmodule.exports = {\n\n  // ruleid: sequelize-tls-disabled-cert-validation\n  dev: {\n    username: \"0xdbe\",\n    database: \"app_db\",\n    dialect: \"mysql\",\n    host: \"127.0.0.1\",\n    dialectOptions: {\n      ssl: {\n        rejectUnauthorized: false\n      }\n    }\n  }\n};\n\n\n// Example for postgresql\nmodule.exports = {\n\n  // ruleid: sequelize-tls-disabled-cert-validation\n  dev: {\n    username: \"0xdbe\",\n    database: \"app_db\",\n    dialect: \"postgres\",\n    host: \"127.0.0.1\",\n    dialectOptions: {\n      ssl: {\n        rejectUnauthorized: false\n      }\n    }\n  }\n};\n\n\n// Example for postgresql\nmodule.exports = {\n\n  // ok: sequelize-tls-disabled-cert-validation\n  dev: {\n    username: \"0xdbe\",\n    database: \"app_db\",\n    dialect: \"postgres\",\n    host: \"127.0.0.1\",\n  }\n};\n",
  },
  bugReport: "Imported from semgrep rule 'sequelize-tls-disabled-cert-validation': Set \"rejectUnauthorized\" to false is a convenient way to resolve certificate error. But this method is unsafe because it disables the server certificate verification, making the Node app open to MITM attack. \"rejectUnauthorized\" option must be alway set to True (default value). With self -signed certificate or custom CA, use \"ca\" option to define Root Certificate. This rule checks TLS configuratio (ERROR). Found at src/sequelize-tls-disabled-cert-validation.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'sequelize-tls-disabled-cert-validation': Set \"rejectUnauthorized\" to false is a convenient w",
        failureDescription: "Imported from semgrep rule 'sequelize-tls-disabled-cert-validation': Set \"rejectUnauthorized\" to false is a convenient way to resolve certificate error. But this method is unsafe because it disables t",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/sequelize-tls-disabled-cert-validation.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
