/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-require-request",
  bugClass: "novel",
  files: {
    ["src/require-request.js"]: "const express = require('express')\nconst app = express()\nconst port = 3000\n\nconst hardcodedPath = 'lib/func.js'\n\nfunction testController1(req, res) {\n    try {\n        // ruleid: require-request\n        require(req.query.controllerFullPath)(req, res);\n    } catch (err) {\n        this.log.error(err);\n    }\n    res.end('ok')\n};\napp.get('/test1', testController1)\n\nlet testController2 = function (req, res) {\n    // ruleid: require-request\n    const func = require(req.body)\n    return res.send(func())\n}\napp.get('/test2', testController2)\n\nvar testController3 = null;\ntestController3 = function (req, res) {\n    // ruleid: require-request\n    const func = require(req.body)\n    return res.send(func())\n}\napp.get('/test3', testController3)\n\n(function (req, res) {\n    // ruleid: require-request\n    const func = require(req.body)\n    return res.send(func())\n})(req, res)\n\napp.get('/ok-test', (req, res) => {\n    // ok: require-request\n    const func = require(hardcodedPath)\n    return res.send(func())\n})\n\nlet okController = function (req, res) {\n    // ok: require-request\n    const func = require('lib/func.js')\n    return res.send(func())\n}\napp.get('/ok-test2', okController)\n\napp.listen(port, () => console.log(`Example app listening at http://localhost:${port}`))\n",
  },
  bugReport: "Imported from semgrep rule 'require-request': If an attacker controls the x in require(x) then they can cause code to load that was not intended to run on the server. options: interfile: true metadata: interfile: true owasp: - A01:2021 - Broken Access Control - A01:2025 - Broken Access Control cwe: - 'CWE-706: Use of Incorrectly-Resolved Name or Reference' source-rule-url: https://nodesecroadmap.fyi/chapter-1/threat-UIR.html category: securit (ERROR). Found at src/require-request.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'require-request': If an attacker controls the x in require(x) then they can cause code to lo",
        failureDescription: "Imported from semgrep rule 'require-request': If an attacker controls the x in require(x) then they can cause code to load that was not intended to run on the server. options: interfile: true metadata",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/require-request.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
