/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-insecure-innerhtml",
  bugClass: "novel",
  files: {
    ["src/insecure-innerhtml.js"]: "const el = element.innerHTML;\n\nfunction bad1(userInput) {\n  // ruleid: insecure-innerhtml\n  el.innerHTML = '<div>' + userInput + '</div>';\n}\n\nfunction bad2(userInput) {\n  // ruleid: insecure-innerhtml\n  document.body.innerHTML = userInput;\n}\n\nfunction bad3(userInput) {\n  const name = '<div>' + userInput + '</div>';\n  // ruleid: insecure-innerhtml\n  document.body.innerHTML = name;\n}\n\nfunction ok1() {\n  const name = \"<div>it's ok</div>\";\n  // ok: insecure-innerhtml\n  el.innerHTML = name;\n}\n\nfunction ok2() {\n  // ok: insecure-innerhtml\n  document.body.innerHTML = \"<div>it's ok</div>\";\n}\n",
  },
  bugReport: "Imported from semgrep rule 'insecure-innerhtml': User controlled data in a `$EL.innerHTML` is an anti-pattern that can lead to XSS vulnerabilities metadata: cwe: - \"CWE-79: Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')\" owasp: - A07:2017 - Cross-Site Scripting (XSS) - A03:2021 - Injection - A05:2025 - Injection category: security technology: - browser cwe2022-top25: true cwe2021-top25: true subcategory: - a (ERROR). Found at src/insecure-innerhtml.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'insecure-innerhtml': User controlled data in a `$EL.innerHTML` is an anti-pattern that can l",
        failureDescription: "Imported from semgrep rule 'insecure-innerhtml': User controlled data in a `$EL.innerHTML` is an anti-pattern that can lead to XSS vulnerabilities metadata: cwe: - \"CWE-79: Improper Neutralization of ",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/insecure-innerhtml.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
