/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-calling-set-state-on-current-state",
  bugClass: "novel",
  files: {
    ["src/set-state-no-op.jsx"]: "import { useState } from \"react\";\nimport styled from \"styled-components\";\n\nconst PolicyColumn = ({\n  group,\n  deck,\n}) => {\n  const [actionsExpanded, setActionsExpanded] = useState<boolean>(false);\n  const [columnRef, setColumnRef] = useState<HTMLElement | null>(null);\n  return (\n    <ColumnContainer>\n      <ColumnHeader>\n        <Button\n          small\n          minimal\n          onClick={() => {\n            // ruleid:calling-set-state-on-current-state\n            setActionsExpanded(actionsExpanded);\n          }}\n          intent={actionsExpanded ? Intent.PRIMARY : Intent.NONE}\n        >\n          <FontAwesomeIcon icon={faBell} />\n        </Button>\n        <Button\n          small\n          minimal\n          onClick={() => {\n            // ok\n            setActionsExpanded(!actionsExpanded);\n          }}\n          intent={actionsExpanded ? Intent.PRIMARY : Intent.NONE}\n        >\n          <FontAwesomeIcon icon={faBell} />\n        </Button>\n      </ColumnHeader>\n    </ColumnContainer>\n  );\n};\n\nexport default PolicyColumn;\n",
  },
  bugReport: "Imported from semgrep rule 'calling-set-state-on-current-state': Calling setState on the current state is always a no-op. Did you mean to change the state like $Y(!$X) instead? languages: - javascript severity: ERROR metadata: technology: - react category: correctness (ERROR). Found at src/set-state-no-op.jsx line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'calling-set-state-on-current-state': Calling setState on the current state is always a no-op",
        failureDescription: "Imported from semgrep rule 'calling-set-state-on-current-state': Calling setState on the current state is always a no-op. Did you mean to change the state like $Y(!$X) instead? languages: - javascript",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/set-state-no-op.jsx", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
