/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-create-de-cipher-no-iv",
  bugClass: "novel",
  files: {
    ["src/create-de-cipher-no-iv.js"]: "const crypto = require('node:crypto')\nfunction decrypt1(ciphertext, key) {\n    iv = ciphertext.iv\n    encryptedData = ciphertext.data\n\n    // ruleid: create-de-cipher-no-iv\n    const decipher = crypto.createDecipher(\"aes-128-gcm\", key, iv);\n    let result = decipher.update(encryptedData);\n\n    return result.toString(\"utf8\");\n}\n\nfunction decrypt2(ciphertext, key) {\n    encryptedData = ciphertext.data\n    auth = ciphertext.auth\n\n    // ruleid: create-de-cipher-no-iv\n    var decipher = crypto.createDecipher(\"aes-192-cbc\", key);\n    let result = decipher.update(encryptedData);\n\n    return result.toString(\"utf8\");\n}\n\nconst { createCipher } = require('node:crypto')\nfunction encrypt1(plaintext, key) {\n    // ruleid: create-de-cipher-no-iv\n    const cipher = createCipher(\"aes-256-ccm\", key, {authTagLength: 16})\n    cipher.setAAD(Buffer.alloc(0), {plaintextLength: plaintext.length})\n    let result = cipher.update(plaintext) + cipher.final()\n\n    return result + cipher.getAuthTag()\n}\n\nfunction decrypt3(key, ciphertext) {\n    let encrypted = Buffer.from(ciphertext, 'base64');\n    let iv = encrypted.slice(encrypted.byteLength - 12, encrypted.byteLength);\n\n    // ok: create-de-cipher-no-iv\n    let decipher = crypto.createDecipheriv(\"aes-256-ocb\", key, iv, {authTagLength: 16});\n    let decrypted = decipher.update(encrypted.slice(0, encrypted.byteLength - 16 - 12));\n\n    decrypted = Buffer.concat([decrypted]);\n    return decrypted;\n}\n\nfunction encrypt2(key, plaintext) {\n    let iv = crypto.randomBytes(12);\n\n    // ok: create-de-cipher-no-iv\n    let cipher = crypto.createCipheriv(\"chacha20-poly1305\", key, iv);\n    let encrypted = Buffer.concat([cipher.update(plaintext), cipher.final(), cipher.getAuthTag()]);\n    return encrypted;\n}\n",
  },
  bugReport: "Imported from semgrep rule 'create-de-cipher-no-iv': The deprecated functions 'createCipher' and 'createDecipher' generate the same initialization vector every time. For counter modes such as CTR, GCM, or CCM this leads to break of both confidentiality and integrity, if the key is used more than once. Other modes are still affected in their strength, though they're not completely broken. Use 'createCipheriv' or 'createDecipheriv' instead. metadata:  (ERROR). Found at src/create-de-cipher-no-iv.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'create-de-cipher-no-iv': The deprecated functions 'createCipher' and 'createDecipher' genera",
        failureDescription: "Imported from semgrep rule 'create-de-cipher-no-iv': The deprecated functions 'createCipher' and 'createDecipher' generate the same initialization vector every time. For counter modes such as CTR, GCM",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/create-de-cipher-no-iv.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
