/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-raw-html-format",
  bugClass: "novel",
  files: {
    ["src/raw-html-format.js"]: "const express = require('express')\nconst app = express()\nconst port = 3000\n\napp.get('/test', async (req, res) => {\n    // ruleid: raw-html-format\n    res.send(\"<h1>\" + \"message: \" + req.query.message + \"</h1>\");\n})\n\napp.post('/test2', async (req, res) => {\n    // ruleid: raw-html-format\n    res.send(`<h1>message: ${req.query.message}</h1>`);\n})\n\napp.post('/test3', async (req, res) => {\n    // ruleid: raw-html-format\n    var html = \"<h1>\" + \"message: \" + req.query.message + \"</h1>\"\n    res.send(html);\n})\n\napp.post('/test4', async (req, res) => {\n    var html = \"<h1> message\"\n    // ruleid: raw-html-format\n    html = html.concat(req.query.message)\n    html = html.concat(\"</h1>\")\n    res.send(html);\n})\n\napp.post('/ok-test', async (req, res) => {\n    let { foobar } = req.query\n    let sanitizedParam = sanitizeUrl(foobar)\n    const url = `${baseUrl}/foo/bar?yo=123&param=${sanitizedParam}`\n    // ok: raw-html-format\n    return res.send(`<a href=\"${url}\" />`)\n})\n\napp.get('/ok', async (req, res) => {\n    // ok: raw-html-format\n    res.send(\"message: \" + req.query.message);\n})\n\napp.post('/ok2', async (req, res) => {\n    // ok: raw-html-format\n    res.send(`message: ${req.query.message}`);\n})\n\napp.post('/ok3', async (req, res) => {\n    // ok: raw-html-format\n    var data = \"message: \" + req.query.message;\n    res.send(data);\n})\n\napp.post('/ok4', async (req, res) => {\n    var data = \"message: \"\n    // ok: raw-html-format\n    data = data.concat(req.query.message)\n    res.send(data);\n})\n\n\napp.listen(port, () => console.log(`Example app listening at http://localhost:${port}`))\n",
  },
  bugReport: "Imported from semgrep rule 'raw-html-format': User data flows into the host portion of this manually-constructed HTML. This can introduce a Cross-Site-Scripting (XSS) vulnerability if this comes from user-provided input. Consider using a sanitization library such as DOMPurify to sanitize the HTML within. metadata: cwe: - \"CWE-79: Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')\" owasp: - A07:2017 - Cross-Si (WARNING). Found at src/raw-html-format.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'raw-html-format': User data flows into the host portion of this manually-constructed HTML. T",
        failureDescription: "Imported from semgrep rule 'raw-html-format': User data flows into the host portion of this manually-constructed HTML. This can introduce a Cross-Site-Scripting (XSS) vulnerability if this comes from ",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/raw-html-format.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
