/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-tainted-html-response",
  bugClass: "novel",
  files: {
    ["src/tainted-html-response.js"]: "exports.handler = function (event, context) {\n    const html = `<div>${event.name}</div>`;\n\n    const someRandomStuff = {\n        // ok: tainted-html-response\n        data: event.foo\n    }\n    bar(someRandomStuff)\n\n    const response = {\n        statusCode: 200,\n        // ruleid: tainted-html-response\n        body: html,\n        headers: {\n            'Content-Type': 'text/html',\n        }\n    };\n\n    return response\n}\n",
  },
  bugReport: "Imported from semgrep rule 'tainted-html-response': Detected user input flowing into an HTML response. You may be accidentally bypassing secure methods of rendering HTML by manually constructing HTML and this could create a cross-site scripting vulnerability, which could let attackers steal sensitive user data. metadata: cwe: - \"CWE-79: Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')\" owasp: - A07:2017 - Cross-S (WARNING). Found at src/tainted-html-response.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'tainted-html-response': Detected user input flowing into an HTML response. You may be accide",
        failureDescription: "Imported from semgrep rule 'tainted-html-response': Detected user input flowing into an HTML response. You may be accidentally bypassing secure methods of rendering HTML by manually constructing HTML ",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/tainted-html-response.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
