/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-x-frame-options-misconfiguration",
  bugClass: "novel",
  files: {
    ["src/x-frame-options-misconfiguration.js"]: "var express = require('express'),\n    app = express();\n\napp.get('/', function (req, res) {\n    // ruleid: x-frame-options-misconfiguration\n    res.set('X-Frame-Options', req.query.opts)\n    res.send('ok')\n})\n\napp.get('/', function (req, res) {\n    // ok: x-frame-options-misconfiguration\n    res.set('X-Frame-Options', 'SAMEORIGIN')\n    res.send('ok')\n})\n",
  },
  bugReport: "Imported from semgrep rule 'x-frame-options-misconfiguration': By letting user input control `X-Frame-Options` header, there is a risk that software does not properly verify whether or not a browser should be allowed to render a page in an `iframe`. metadata: references: - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options owasp: - A04:2021 - Insecure Design - A06:2025 - Insecure Design cwe: - 'CWE-451: User Interface (UI) Misrepresenta (WARNING). Found at src/x-frame-options-misconfiguration.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'x-frame-options-misconfiguration': By letting user input control `X-Frame-Options` header, t",
        failureDescription: "Imported from semgrep rule 'x-frame-options-misconfiguration': By letting user input control `X-Frame-Options` header, there is a risk that software does not properly verify whether or not a browser s",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/x-frame-options-misconfiguration.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
