/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-detect-vercel-ai",
  bugClass: "novel",
  files: {
    ["src/detect-vercel-ai.ts"]: "// ruleid: detect-vercel-ai\nimport { generateText } from \"ai\"\n// ruleid: detect-vercel-ai\nimport { openai } from \"@ai-sdk/openai\"\n// ruleid: detect-vercel-ai\nconst { text } = await generateText({\n    model: openai(\"gpt-4-turbo\"),\n    prompt: \"What is love?\"\n})\n\n// ruleid: detect-vercel-ai\nimport { generateText } from \"ai\"\n// ruleid: detect-vercel-ai\nimport { anthropic } from \"@ai-sdk/anthropic\"\n// ruleid: detect-vercel-ai\nconst { text } = await generateText({\n    model: anthropic(\"claude-3-opus-20240229\"),\n    prompt: \"What is love?\"\n})\n\n// ruleid: detect-vercel-ai\nimport { generateText } from \"ai\"\n// ruleid: detect-vercel-ai\nimport { google } from \"@ai-sdk/google\"\n// ruleid: detect-vercel-ai\nconst { text } = await generateText({\n    model: google(\"models/gemini-1.5-pro-latest\"),\n    prompt: \"What is love?\"\n})\n\n// ruleid: detect-vercel-ai\nimport { generateText } from \"ai\"\n// ruleid: detect-vercel-ai\nimport { mistral } from \"@ai-sdk/mistral\"\n// ruleid: detect-vercel-ai\nconst { text } = await generateText({\n    model: mistral(\"mistral-large-latest\"),\n    prompt: \"What is love?\"\n})\n\n// ruleid: detect-vercel-ai\nimport { generateText } from \"ai\"\n// ruleid: detect-vercel-ai\nimport { custom } from \"@ai-sdk/custom\"\n// ruleid: detect-vercel-ai\nconst { text } = await generateText({\n    model: custom(\"mistral-large-latest\"),\n    prompt: \"What is love?\"\n})",
  },
  bugReport: "Imported from semgrep rule 'detect-vercel-ai': Possibly found usage of AI: VercelAI (INFO). Found at src/detect-vercel-ai.ts line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'detect-vercel-ai': Possibly found usage of AI: VercelAI (INFO). Found at src/detect-vercel-a",
        failureDescription: "Imported from semgrep rule 'detect-vercel-ai': Possibly found usage of AI: VercelAI (INFO). Found at src/detect-vercel-ai.ts line 1.",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/detect-vercel-ai.ts", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
