/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-ajv-allerrors-true",
  bugClass: "novel",
  files: {
    ["src/ajv-allerrors-true.js"]: "import express from 'express';\nimport Ajv from 'ajv';\n\nfunction test1() {\n    const settings = { allErrors: true, smth: 'else' }\n    // ruleid: ajv-allerrors-true\n    const ajv1 = new Ajv(settings);\n    return ajv1\n}\n\nfunction test2() {\n    // ruleid: ajv-allerrors-true\n    var ajv = new Ajv({ allErrors: true, smth: 'else' });\n    ajv.addSchema(schema, 'input');\n}\n\n\nfunction test3() {\n    // ruleid: ajv-allerrors-true\n    var ajv = new Ajv({  smth: 'else', allErrors: true });\n    ajv.addSchema(schema, 'input');\n}\n\nfunction test4() {\n    // ruleid: ajv-allerrors-true\n    var ajv = new Ajv({  smth: 'else', smth: 'else', allErrors: true, smth: 'else' });\n    ajv.addSchema(schema, 'input');\n}\n\n\nfunction okTest1() {\n    // ok: ajv-allerrors-true\n    let ajv = new Ajv({ allErrors: process.env.DEBUG });\n    ajv.addSchema(schema, 'input');\n}\n\nfunction okTest2() {\n    // ok: ajv-allerrors-true\n    var ajv = new Ajv({  smth: 'else', allErrors: false });\n    ajv.addSchema(schema, 'input');\n}\n",
  },
  bugReport: "Imported from semgrep rule 'ajv-allerrors-true': By setting `allErrors: true` in `Ajv` library, all error objects will be allocated without limit. This allows the attacker to produce a huge number of errors which can lead to denial of service. Do not use `allErrors: true` in production. metadata: cwe: - 'CWE-400: Uncontrolled Resource Consumption' category: security technology: - ajv references: - https://ajv.js.org/options.html#allerrors cwe202 (WARNING). Found at src/ajv-allerrors-true.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'ajv-allerrors-true': By setting `allErrors: true` in `Ajv` library, all error objects will b",
        failureDescription: "Imported from semgrep rule 'ajv-allerrors-true': By setting `allErrors: true` in `Ajv` library, all error objects will be allocated without limit. This allows the attacker to produce a huge number of ",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/ajv-allerrors-true.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
