/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-react-unsanitized-property",
  bugClass: "novel",
  files: {
    ["src/react-unsanitized-property.tsx"]: "function Test2(input) {\n  // ruleid: react-unsanitized-property\n    ReactDOM.findDOMNode(this.someRef).outerHTML = input.value;\n  }\n  \n  function OkTest1() {\n  // ok: react-unsanitized-property\n    this.element.innerHTML = \"<a href='/about.html'>About</a>\";\n  }\n  \n  function OkTest2() {\n  // ok: react-unsanitized-property\n    ReactDOM.findDOMNode(this.someRef).outerHTML = \"<a href='/about.html'>About</a>\";\n  }\n  ",
  },
  bugReport: "Imported from semgrep rule 'react-unsanitized-property': Detection of $HTML from non-constant definition. This can inadvertently expose users to cross-site scripting (XSS) attacks if this comes from user-provided input. If you have to use $HTML, consider using a sanitization library such as DOMPurify to sanitize your HTML. metadata: cwe: - \"CWE-79: Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')\" owasp: - A07:2017 -  (WARNING). Found at src/react-unsanitized-property.tsx line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'react-unsanitized-property': Detection of $HTML from non-constant definition. This can inadv",
        failureDescription: "Imported from semgrep rule 'react-unsanitized-property': Detection of $HTML from non-constant definition. This can inadvertently expose users to cross-site scripting (XSS) attacks if this comes from u",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/react-unsanitized-property.tsx", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
