/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-remote-property-injection",
  bugClass: "novel",
  files: {
    ["src/remote-property-injection.js"]: "var express = require('express');\n\nvar app = express();\nvar myObj = {}\n\napp.get('/test1', function(req, res) {\n  var prop = req.query.userControlled\n  // ruleid: remote-property-injection\n  myObj[prop] = function() {}\n  res.send('ok')\n})\n\napp.get('/test2', function(req, res) {\n  // ruleid: remote-property-injection\n  myObj[req.body] = foobar()\n  res.send('ok')\n})\n\napp.get('/okTest', function(req, res) {\n  var prop = \"$\" + req.query.userControlled\n  // ok: remote-property-injection\n  myObj[prop] = function() {}\n  res.send('ok')\n})\n",
  },
  bugReport: "Imported from semgrep rule 'remote-property-injection': Bracket object notation with user input is present, this might allow an attacker to access all properties of the object and even it's prototype. Use literal values for object properties. metadata: confidence: LOW owasp: - A02:2017 - Broken Authentication - A04:2021 - Insecure Design - A06:2025 - Insecure Design cwe: - 'CWE-522: Insufficiently Protected Credentials' category: security technology: - (ERROR). Found at src/remote-property-injection.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'remote-property-injection': Bracket object notation with user input is present, this might a",
        failureDescription: "Imported from semgrep rule 'remote-property-injection': Bracket object notation with user input is present, this might allow an attacker to access all properties of the object and even it's prototype.",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/remote-property-injection.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
