/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-zlib-async-loop",
  bugClass: "novel",
  files: {
    ["src/zlib-async-loop.js"]: "const zlib = require('zlib');\n\nconst payload = Buffer.from('This is some data');\n\nfor (let i = 0; i < 30000; ++i) {\n    // ruleid: zlib-async-loop\n    zlib.deflate(payload, (err, buffer) => {});\n}\n\n[1,2,3].forEach((el) => {\n    // ruleid: zlib-async-loop\n    zlib.deflate(payload, (err, buffer) => {});\n})\n\nfor (let i = 0; i < 30000; ++i) {\n    // ok: zlib-async-loop\n    zlib.deflateSync(payload);\n}\n\n// ok: zlib-async-loop\nzlib.deflate(payload, (err, buffer) => {});\n",
  },
  bugReport: "Imported from semgrep rule 'zlib-async-loop': Creating and using a large number of zlib objects simultaneously can cause significant memory fragmentation. It is strongly recommended that the results of compression operations be cached or made synchronous to avoid duplication of effort. metadata: references: - https://nodejs.org/api/zlib.html#zlib_threadpool_usage_and_performance_considerations category: best-practice technology: - javascript  (WARNING). Found at src/zlib-async-loop.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'zlib-async-loop': Creating and using a large number of zlib objects simultaneously can cause",
        failureDescription: "Imported from semgrep rule 'zlib-async-loop': Creating and using a large number of zlib objects simultaneously can cause significant memory fragmentation. It is strongly recommended that the results o",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/zlib-async-loop.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
