/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-jwt-none-alg",
  bugClass: "novel",
  files: {
    ["src/jwt-none-alg.js"]: "function verifyJwt() {\n    let jwt = require(\"jsonwebtoken\");\n    let secret = 'some-secret';\n    // ruleid: jwt-none-alg\n    jwt.verify('token-here', secret, { algorithms: ['RS256', 'none'] }, function(err, payload) {\n        console.log(payload);\n    });\n}\n\n// ok: jwt-none-alg\nconst jwt = require(\"jsonwebtoken\");\nconst secret = 'some-secret';\nconst payload = jwt.verify('token-here', secret, { algorithms: ['RS256', 'HS256'] });\n",
  },
  bugReport: "Imported from semgrep rule 'jwt-none-alg': Detected use of the 'none' algorithm in a JWT token. The 'none' algorithm assumes the integrity of the token has already been verified. This would allow a malicious actor to forge a JWT token that will automatically be verified. Do not explicitly use the 'none' algorithm. Instead, use an algorithm such as 'HS256'. metadata: cwe: - 'CWE-327: Use of a Broken or Risky Cryptographic Algorithm' owasp:  (ERROR). Found at src/jwt-none-alg.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'jwt-none-alg': Detected use of the 'none' algorithm in a JWT token. The 'none' algorithm ass",
        failureDescription: "Imported from semgrep rule 'jwt-none-alg': Detected use of the 'none' algorithm in a JWT token. The 'none' algorithm assumes the integrity of the token has already been verified. This would allow a ma",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/jwt-none-alg.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
