/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-eqeq-is-bad",
  bugClass: "novel",
  files: {
    ["src/useless-eqeq.js"]: "\n// ruleid:eqeq-is-bad\nx == x\n\n// ok:eqeq-is-bad\nassert(x == x)\n\n// ok, harmless\n1 == 1\n",
  },
  bugReport: "Imported from semgrep rule 'eqeq-is-bad': Detected a useless comparison operation `$X == $X` or `$X != $X`. This operation is always true. If testing for floating point NaN, use `math.isnan`, or `cmath.isnan` if the number is complex. languages: - javascript - typescript severity: INFO metadata: category: correctness technology: - javascript (INFO). Found at src/useless-eqeq.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'eqeq-is-bad': Detected a useless comparison operation `$X == $X` or `$X != $X`. This operati",
        failureDescription: "Imported from semgrep rule 'eqeq-is-bad': Detected a useless comparison operation `$X == $X` or `$X != $X`. This operation is always true. If testing for floating point NaN, use `math.isnan`, or `cmat",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/useless-eqeq.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
