/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-multiargs-code-execution",
  bugClass: "novel",
  files: {
    ["src/multiargs-code-execution.js"]: "var thenify = require('thenify');\n\nfunction bad1() {\n// ruleid: multiargs-code-execution\n    var promise = thenify(function (callback) {\n        callback(null, 1, 2, 3);\n    }, { multiArgs: [ 'one', 'tow', 'three' ] });\n}\n\nfunction bad2() {\n// ruleid: multiargs-code-execution\n    var params = { multiArgs: [ 'one', 'tow', 'three' ] };\n\n    var promise = thenify(function (callback) {\n        callback(null, 1, 2, 3);\n    }, params);\n}\n\nfunction ok1() {\n// ok: multiargs-code-execution\n    var promise = thenify(function (callback) {\n        callback(null, 1, 2, 3);\n    }, { multiArgs: false });\n}\n\nfunction ok2() {\n// ok: multiargs-code-execution\n    var params = { multiArgs: false };\n\n    var promise = thenify(function (callback) {\n        callback(null, 1, 2, 3);\n    }, params);\n}\n",
  },
  bugReport: "Imported from semgrep rule 'multiargs-code-execution': Potential arbitrary code execution, piped to eval metadata: cwe: - \"CWE-94: Improper Control of Generation of Code ('Code Injection')\" owasp: - A03:2021 - Injection - A05:2025 - Injection category: security technology: - thenify cwe2022-top25: true subcategory: - audit likelihood: LOW impact: HIGH confidence: LOW references: - https://owasp.org/Top10/A03_2021-Injection languages: - javascript - ty (WARNING). Found at src/multiargs-code-execution.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'multiargs-code-execution': Potential arbitrary code execution, piped to eval metadata: cwe: ",
        failureDescription: "Imported from semgrep rule 'multiargs-code-execution': Potential arbitrary code execution, piped to eval metadata: cwe: - \"CWE-94: Improper Control of Generation of Code ('Code Injection')\" owasp: - A",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/multiargs-code-execution.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
