/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-dangerous-spawn-shell",
  bugClass: "novel",
  files: {
    ["src/dangerous-spawn-shell.js"]: "const {spawn, spawnSync} = require('child_process');\nconst cp = require('child_process');\n\nfunction test1(userInput) {\n    let name = \"bash\";\n    // ruleid: dangerous-spawn-shell\n    spawnSync(name, [\"-c\", userInput]);\n}\n\nfunction test2(userInput) {\n    // ruleid: dangerous-spawn-shell\n    cp.spawn('sh', [userInput]);\n}\n\nfunction testOk(userInput) {\n    foobar(userInput);\n    // ok: dangerous-spawn-shell\n    spawn('ls', ['-la', '/tmp']);\n}\n\n",
  },
  bugReport: "Imported from semgrep rule 'dangerous-spawn-shell': Detected non-literal calls to $EXEC(). This could lead to a command injection vulnerability. metadata: cwe: - \"CWE-78: Improper Neutralization of Special Elements used in an OS Command ('OS Command Injection')\" owasp: - A01:2017 - Injection - A03:2021 - Injection - A05:2025 - Injection source-rule-url: https://github.com/nodesecurity/eslint-plugin-security/blob/master/rules/detect-child-process.js (ERROR). Found at src/dangerous-spawn-shell.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'dangerous-spawn-shell': Detected non-literal calls to $EXEC(). This could lead to a command ",
        failureDescription: "Imported from semgrep rule 'dangerous-spawn-shell': Detected non-literal calls to $EXEC(). This could lead to a command injection vulnerability. metadata: cwe: - \"CWE-78: Improper Neutralization of Sp",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/dangerous-spawn-shell.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
