/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-unknown-value-in-redirect",
  bugClass: "novel",
  files: {
    ["src/possible-user-input-redirect.js"]: "/*\n * Copyright (c) 2014-2020 Bjoern Kimminich.\n * SPDX-License-Identifier: MIT\n */\n\nconst utils = require('../lib/utils')\nconst insecurity = require('../lib/insecurity')\nconst challenges = require('../data/datacache').challenges\n\nmodule.exports = function performRedirect () {\n  return ({ query }, res, next) => {\n    const toUrl = query.to\n    if (insecurity.isRedirectAllowed(toUrl)) {\n      utils.solveIf(challenges.redirectCryptoCurrencyChallenge, () => { return toUrl === 'https://explorer.dash.org/address/Xr556RzuwX6hg5EGpkybbv5RanJoZN17kW' || toUrl === 'https://blockchain.info/address/1AbKfgvw9psQ41NbLi8kufDQTezwG8DRZm' || toUrl === 'https://etherscan.io/address/0x0f933ab9fcaaa782d0279c300d73750e1311eae6' })\n      utils.solveIf(challenges.redirectChallenge, () => { return isUnintendedRedirect(toUrl) })\n      // ruleid:unknown-value-in-redirect\n      res.redirect(toUrl)\n    } else {\n      res.status(406)\n      next(new Error('Unrecognized target URL for redirect: ' + toUrl))\n    }\n  }\n}\n\nfunction isUnintendedRedirect (toUrl) {\n  let unintended = true\n  for (const allowedUrl of insecurity.redirectWhitelist) {\n    unintended = unintended && !utils.startsWith(toUrl, allowedUrl)\n  }\n  return unintended\n}\n",
  },
  bugReport: "Imported from semgrep rule 'unknown-value-in-redirect': It looks like '$UNK' is read from user input and it is used to as a redirect. Ensure '$UNK' is not externally controlled, otherwise this is an open redirect. metadata: owasp: - A01:2021 - Broken Access Control - A01:2025 - Broken Access Control cwe: - \"CWE-601: URL Redirection to Untrusted Site ('Open Redirect')\" asvs: section: V5 Validation, Sanitization and Encoding control_id: 5.5.1 Insecue Red (WARNING). Found at src/possible-user-input-redirect.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'unknown-value-in-redirect': It looks like '$UNK' is read from user input and it is used to a",
        failureDescription: "Imported from semgrep rule 'unknown-value-in-redirect': It looks like '$UNK' is read from user input and it is used to as a redirect. Ensure '$UNK' is not externally controlled, otherwise this is an o",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/possible-user-input-redirect.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
