/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-vm2-code-injection",
  bugClass: "novel",
  files: {
    ["src/vm2-code-injection.js"]: "'use strict';\n\nconst fs = require('fs');\nconst {VM, NodeVM} = require('vm2');\n\n\nasync function test1(code, input) {\n  code = `\n    console.log(${input})\n  `;\n\n  const sandbox = {\n    setTimeout,\n    fs: {\n      watch: fs.watch\n    }\n  };\n\n  // ruleid: vm2-code-injection\n  return new VM({\n    timeout: 40 * 1000,\n    sandbox\n  }).run(code);\n}\n\nfunction test2(input) {\n  const sandbox = {\n    setTimeout,\n    fs: {\n      watch: fs.watch\n    }\n  };\n\n  // ruleid: vm2-code-injection\n  const nodeVM = new NodeVM({timeout: 40 * 1000, sandbox});\n  return nodeVM.run('console.log(' + input + ')')\n}\n\nfunction test3(input) {\n  const sandbox = {\n    setTimeout,\n    fs: {\n      watch: fs.watch\n    }\n  };\n\n  const nodeVM = new NodeVM({timeout: 40 * 1000, sandbox});\n  // ruleid: vm2-code-injection\n  const script = new VMScript(`console.log(${input})`)\n  return nodeVM.run(script)\n}\n\nasync function okTest1(code) {\n  code = `\n    console.log(\"Hello world\")\n  `;\n\n  const sandbox = {\n    setTimeout,\n    fs: {\n      watch: fs.watch\n    }\n  };\n\n  return new VM({\n    timeout: 40 * 1000,\n    sandbox\n  }).run(code);\n}\n\nfunction okTest2() {\n  const sandbox = {\n    setTimeout,\n    fs: {\n      watch: fs.watch\n    }\n  };\n\n  const nodeVM = new NodeVM({timeout: 40 * 1000, sandbox});\n  return nodeVM.run('console.log(\"Hello world\")')\n}\n\nfunction okTest3() {\n  const sandbox = {\n    setTimeout,\n    fs: {\n      watch: fs.watch\n    }\n  };\n\n  const nodeVM = new NodeVM({timeout: 40 * 1000, sandbox});\n  const script = new VMScript('console.log(\"Hello world\")')\n  return nodeVM.run(script)\n}\n",
  },
  bugReport: "Imported from semgrep rule 'vm2-code-injection': Make sure that unverified user data can not reach `vm2`. metadata: owasp: - A03:2021 - Injection - A05:2025 - Injection cwe: - \"CWE-94: Improper Control of Generation of Code ('Code Injection')\" category: security technology: - vm2 cwe2022-top25: true subcategory: - audit likelihood: LOW impact: HIGH confidence: LOW references: - https://owasp.org/Top10/A03_2021-Injection languages: - javascript - (WARNING). Found at src/vm2-code-injection.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'vm2-code-injection': Make sure that unverified user data can not reach `vm2`. metadata: owas",
        failureDescription: "Imported from semgrep rule 'vm2-code-injection': Make sure that unverified user data can not reach `vm2`. metadata: owasp: - A03:2021 - Injection - A05:2025 - Injection cwe: - \"CWE-94: Improper Contro",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/vm2-code-injection.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
