/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-detect-angular-trust-as-js-method",
  bugClass: "novel",
  files: {
    ["src/detect-angular-trust-as-js-method.js"]: "var app = angular.module('MyApp', []);\napp.controller('myCtrl', function($scope, $sce) {\n\n$scope.userInput = 'foo';\n    $scope.sayHello = function() {\n     // ruleid:detect-angular-trust-as-js-method\n     $scope.trustedurl = $sce.trustAsJs($scope.html);\n     // ruleid:detect-angular-trust-as-js-method\n     input = $scope.html\n     $scope.trustedurl = $sce.trustAsJs(input);\n\n\n     //Data is not coming from user input\n     $scope.trustedurl = $sce.trustAsJs('stringLiteral');\n   };\n\n});\n",
  },
  bugReport: "Imported from semgrep rule 'detect-angular-trust-as-js-method': The use of $sce.trustAsJs can be dangerous if unsanitized user input flows through this API. metadata: owasp: - A07:2017 - Cross-Site Scripting (XSS) - A03:2021 - Injection - A05:2025 - Injection references: - https://docs.angularjs.org/api/ng/service/$sce#trustAsJs - https://owasp.org/www-chapter-london/assets/slides/OWASPLondon20170727_AngularJS.pdf cwe: - \"CWE-79: Improper Neutralization of Inp (WARNING). Found at src/detect-angular-trust-as-js-method.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'detect-angular-trust-as-js-method': The use of $sce.trustAsJs can be dangerous if unsanitize",
        failureDescription: "Imported from semgrep rule 'detect-angular-trust-as-js-method': The use of $sce.trustAsJs can be dangerous if unsanitized user input flows through this API. metadata: owasp: - A07:2017 - Cross-Site Sc",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/detect-angular-trust-as-js-method.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
