/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-react-dangerouslysetinnerhtml",
  bugClass: "novel",
  files: {
    ["src/react-dangerouslysetinnerhtml.tsx"]: "import DOMPurify from \"dompurify\"\nimport sanitize from \"xss\"\n\nfunction TestComponent1() {\n    // ok:react-dangerouslysetinnerhtml\n  return <div dangerouslySetInnerHTML={createMarkup()} />;\n}\n\nfunction TestComponent2(foo) {\n    // ruleid:react-dangerouslysetinnerhtml\n    let params = {smth: 'test123', dangerouslySetInnerHTML: {__html: foo.bar},a:b};\n    return React.createElement('div', params);\n}\n\n// ok:react-dangerouslysetinnerhtml\n{collaborationSectionData.paragraphs.map((item, i) => (\n  <li key={`collaboration-p-${i}`} dangerouslySetInnerHTML={{\n    __html: item,}}>\n  </li>\n))}\n\nfunction TestComponent3() {\n    // ok:react-dangerouslysetinnerhtml\n  return <li className={\"foobar\"} dangerouslySetInnerHTML={{__html: params}} />;\n}\n\n\nfunction OkComponent1() {\n    // ok:react-dangerouslysetinnerhtml\n  return <li className={\"foobar\"} dangerouslySetInnerHTML={{__html: DOMPurify.sanitize(foo)}} />;\n}\n\n\n\nfunction OkComponent2() {\n    // ok:react-dangerouslysetinnerhtml\n  return <li className={\"foobar\"} dangerouslySetInnerHTML={DOMPurify.sanitize(createMarkup())} />;\n}\n\nfunction OkComponent3() {\n    // ok:react-dangerouslysetinnerhtml\n    let params = {smth: 'test123', dangerouslySetInnerHTML: {__html: sanitize(foo)},a:b};\n    return React.createElement('div', params);\n}\n\nfunction OkComponent4() {\n    // ok:react-dangerouslysetinnerhtml\n    let params = {smth: 'test123', dangerouslySetInnerHTML: {__html: \"hi\"},a:b};\n    return React.createElement('div', params);\n}\n\nfunction OkComponent5() {\n    // ok:react-dangerouslysetinnerhtml\n  return <li class=\"foobar\" selected={true} />;\n}\n\nfunction OkComponent6() {\n    // ok:react-dangerouslysetinnerhtml\n    let params = {smth: \"test123\", style: {color: 'red'}};\n    return React.createElement('div', params);\n}\n",
  },
  bugReport: "Imported from semgrep rule 'react-dangerouslysetinnerhtml': Detection of dangerouslySetInnerHTML from non-constant definition. This can inadvertently expose users to cross-site scripting (XSS) attacks if this comes from user-provided input. If you have to use dangerouslySetInnerHTML, consider using a sanitization library such as DOMPurify to sanitize your HTML. metadata: cwe: - \"CWE-79: Improper Neutralization of Input During Web Page Generation ('Cross-si (WARNING). Found at src/react-dangerouslysetinnerhtml.tsx line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'react-dangerouslysetinnerhtml': Detection of dangerouslySetInnerHTML from non-constant defin",
        failureDescription: "Imported from semgrep rule 'react-dangerouslysetinnerhtml': Detection of dangerouslySetInnerHTML from non-constant definition. This can inadvertently expose users to cross-site scripting (XSS) attacks",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/react-dangerouslysetinnerhtml.tsx", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
