/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-dom-based-xss",
  bugClass: "novel",
  files: {
    ["src/dom-based-xss.js"]: "// ruleid:dom-based-xss\ndocument.write(\"<OPTION value=1>\"+document.location.href.substring(document.location.href.indexOf(\"default=\")+8)+\"</OPTION>\");\n\n// ok:dom-based-xss\ndocument.write(\"<OPTION value=2>English</OPTION>\");\n",
  },
  bugReport: "Imported from semgrep rule 'dom-based-xss': Detected possible DOM-based XSS. This occurs because a portion of the URL is being used to construct an element added directly to the page. For example, a malicious actor could send someone a link like this: http://www.some.site/page.html?default=<script>alert(document.cookie)</script> which would add the script to the page. Consider allowlisting appropriate values or using an approach which does  (ERROR). Found at src/dom-based-xss.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'dom-based-xss': Detected possible DOM-based XSS. This occurs because a portion of the URL is",
        failureDescription: "Imported from semgrep rule 'dom-based-xss': Detected possible DOM-based XSS. This occurs because a portion of the URL is being used to construct an element added directly to the page. For example, a m",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/dom-based-xss.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
