/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-insecure-createnodesfrommarkup",
  bugClass: "novel",
  files: {
    ["src/insecure-createnodesfrommarkup.js"]: "\nfunction ok1() {\n// ok: insecure-createnodesfrommarkup\n  createNodesFromMarkup('<div></div', function () {\n    handleIt();\n  })\n}\n\nfunction bad1(input) {\n// ruleid: insecure-createnodesfrommarkup\n  createNodesFromMarkup('<div>' + input + '</div', function () {\n    handleIt();\n  })\n}\n",
  },
  bugReport: "Imported from semgrep rule 'insecure-createnodesfrommarkup': User controlled data in a `createNodesFromMarkup` is an anti-pattern that can lead to XSS vulnerabilities metadata: cwe: - \"CWE-79: Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')\" owasp: - A07:2017 - Cross-Site Scripting (XSS) - A03:2021 - Injection - A05:2025 - Injection category: security technology: - fbjs cwe2022-top25: true cwe2021-top25: true subcategory (WARNING). Found at src/insecure-createnodesfrommarkup.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'insecure-createnodesfrommarkup': User controlled data in a `createNodesFromMarkup` is an ant",
        failureDescription: "Imported from semgrep rule 'insecure-createnodesfrommarkup': User controlled data in a `createNodesFromMarkup` is an anti-pattern that can lead to XSS vulnerabilities metadata: cwe: - \"CWE-79: Imprope",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/insecure-createnodesfrommarkup.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
