/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-pg-sqli",
  bugClass: "novel",
  files: {
    ["src/pg-sqli.js"]: "let response;\n\nconst prettyPrint = (ob) => JSON.stringify(ob, null, 2).replace('\\'','');\nconst timestamp = () => new Date();\n\nconst toBase64 = (msg) => Buffer.from(msg).toString('base64');\n\nconst { Client } = require('pg');\nexports.handler = async function (event, context) {\n  console.log(\"the event\");\n  console.log(event);\n\n  const client = new Client({\n    user: \"test\",\n    host: \"db\",\n    database: \"nockslots\",\n    password: \"test\",\n    port: 5432,\n  });\n\n  console.log(\"connecting to db...\");\n\n  await client.connect();\n\n  records = [];\n  event.Records.forEach((record) => {\n    const { body } = record;\n    console.log(body);\n    records.push(toBase64(body));\n  });\n\n  const query = `INSERT INTO public.messages (body, encoded_message) VALUES ('${prettyPrint(event)}', '${records[0]}');`;\n\n  console.log('the query:');\n  console.log(query);\n\n  try {\n    console.log(\"Trying the query...\");\n    // ruleid: pg-sqli\n    await client.query(query)\n    // ok: pg-sqli\n    await client.query('INSERT INTO messages (body, message) VALUES ($1, $2);', [prettyPrint(event), records[0]])\n    await client.end();\n  } catch (error) {\n    console.log('Could not add row to postgres, soz');\n    console.log(error);\n  }\n\n  return { key: JSON.stringify(records) };\n};",
  },
  bugReport: "Imported from semgrep rule 'pg-sqli': Detected SQL statement that is tainted by `$EVENT` object. This could lead to SQL injection if the variable is user-controlled and not properly sanitized. In order to prevent SQL injection, use parameterized queries or prepared statements instead. You can use parameterized statements like so: `connection.query('SELECT $1 from table', [userinput])` metadata: references: - https://node-postgres.com/ (WARNING). Found at src/pg-sqli.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'pg-sqli': Detected SQL statement that is tainted by `$EVENT` object. This could lead to SQL ",
        failureDescription: "Imported from semgrep rule 'pg-sqli': Detected SQL statement that is tainted by `$EVENT` object. This could lead to SQL injection if the variable is user-controlled and not properly sanitized. In orde",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/pg-sqli.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
