/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-detect-gemini",
  bugClass: "novel",
  files: {
    ["src/detect-gemini.ts"]: "// ruleid: detect-gemini\nconst { GoogleGenerativeAI } = require(\"@google/generative-ai\");\n\n// Access your API key as an environment variable (see \"Set up your API key\" above)\n// ruleid: detect-gemini\nconst genAI = new GoogleGenerativeAI(process.env.API_KEY);\n\n// ruleid: detect-gemini\nconst model = genAI.getGenerativeModel({ model: \"gemini-1.5-flash\"});",
  },
  bugReport: "Imported from semgrep rule 'detect-gemini': Possibly found usage of AI: Gemini (INFO). Found at src/detect-gemini.ts line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'detect-gemini': Possibly found usage of AI: Gemini (INFO). Found at src/detect-gemini.ts lin",
        failureDescription: "Imported from semgrep rule 'detect-gemini': Possibly found usage of AI: Gemini (INFO). Found at src/detect-gemini.ts line 1.",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/detect-gemini.ts", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
