/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-javascript-alert",
  bugClass: "novel",
  files: {
    ["src/leftover_debugging.js"]: "\n// ruleid:javascript-prompt\nvar name = prompt('what is your name');\n// ruleid: javascript-alert\nalert('your name is ' + name);\nalert('not', 'a', 'valid', 'alert')\n// ruleid: javascript-confirm\nif ( confirm(\"pushem!\") == true) {\n    r = \"x\";\n} else {\n    r = \"Y\";\n    // ruleid: javascript-debugger\n    debugger;\n}\n",
  },
  bugReport: "Imported from semgrep rule 'javascript-alert': found alert() call; should this be in production code? (WARNING). Found at src/leftover_debugging.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'javascript-alert': found alert() call; should this be in production code? (WARNING). Found a",
        failureDescription: "Imported from semgrep rule 'javascript-alert': found alert() call; should this be in production code? (WARNING). Found at src/leftover_debugging.js line 1.",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/leftover_debugging.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
