/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-shelljs-exec-injection",
  bugClass: "novel",
  files: {
    ["src/shelljs-exec-injection.js"]: "const shell = require('shelljs');\n\nfunction test1(userInput) {\n    // ruleid:shelljs-exec-injection\n    return shell.exec(userInput, {silent: true})\n}\n\nfunction test2(userInput) {\n    const input = `ls ${userInput}`\n    // ruleid:shelljs-exec-injection\n    return shell.exec(input, {silent: true})\n}\n\nfunction okTest3(userInput) {\n    // ok:shelljs-exec-injection\n    const input = 'ls ./'\n    return shell.exec(input, {silent: true})\n}\n\nfunction okTest4(userInput) {\n    // ok:shelljs-exec-injection\n    return shell.exec('ls ./', {silent: true})\n}\n",
  },
  bugReport: "Imported from semgrep rule 'shelljs-exec-injection': If unverified user data can reach the `exec` method it can result in Remote Code Execution metadata: owasp: - A01:2017 - Injection - A03:2021 - Injection - A05:2025 - Injection cwe: - \"CWE-78: Improper Neutralization of Special Elements used in an OS Command ('OS Command Injection')\" category: security technology: - shelljs cwe2022-top25: true cwe2021-top25: true subcategory: - audit likelihood: L (ERROR). Found at src/shelljs-exec-injection.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'shelljs-exec-injection': If unverified user data can reach the `exec` method it can result i",
        failureDescription: "Imported from semgrep rule 'shelljs-exec-injection': If unverified user data can reach the `exec` method it can result in Remote Code Execution metadata: owasp: - A01:2017 - Injection - A03:2021 - Inj",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/shelljs-exec-injection.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
