/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-wkhtmltopdf-injection",
  bugClass: "novel",
  files: {
    ["src/wkhtmltopdf-injection.js"]: "const wkhtmltopdf = require('wkhtmltopdf')\n\n// ruleid: wkhtmltopdf-injection\nwkhtmltopdf(input(), { output: 'vuln.pdf' })\n\nfunction test(userInput) {\n  // ruleid: wkhtmltopdf-injection\n  return wkhtmltopdf(userInput, { output: 'vuln.pdf' })\n}\n\n// ok: wkhtmltopdf-injection\nwkhtmltopdf('<html><html/>', { output: 'vuln.pdf' })\n\nfunction okTest(userInput) {\n   var html = '<html><html/>';\n   // ok: wkhtmltopdf-injection\n   return wkhtmltopdf(html, { output: 'vuln.pdf' })\n}\n",
  },
  bugReport: "Imported from semgrep rule 'wkhtmltopdf-injection': If unverified user data can reach the `wkhtmltopdf` it can result in Server-Side Request Forgery vulnerabilities metadata: owasp: - A10:2021 - Server-Side Request Forgery (SSRF) - A01:2025 - Broken Access Control cwe: - 'CWE-918: Server-Side Request Forgery (SSRF)' category: security technology: - wkhtmltopdf cwe2022-top25: true cwe2021-top25: true subcategory: - audit likelihood: LOW impact: LOW  (WARNING). Found at src/wkhtmltopdf-injection.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'wkhtmltopdf-injection': If unverified user data can reach the `wkhtmltopdf` it can result in",
        failureDescription: "Imported from semgrep rule 'wkhtmltopdf-injection': If unverified user data can reach the `wkhtmltopdf` it can result in Server-Side Request Forgery vulnerabilities metadata: owasp: - A10:2021 - Serve",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/wkhtmltopdf-injection.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
