/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-angular-bypasssecuritytrust",
  bugClass: "novel",
  files: {
    ["src/angular-domsanitizer.ts"]: "import { DomSanitizer, SecurityContext } from '@angular/platform-browser'\nimport DOMPurify from 'dompurify'\n\nclass SomeClass {\n    constructor(private sanitizer: DomSanitizer){}\n\n    bypass(value: string){\n        // ruleid:angular-bypasssecuritytrust\n        let html = this.sanitizer.bypassSecurityTrustHtml(value);\n        // ruleid:angular-bypasssecuritytrust\n        let style = this.sanitizer.bypassSecurityTrustStyle(value);\n        // ruleid:angular-bypasssecuritytrust\n        let script = this.sanitizer.bypassSecurityTrustScript(value);\n        // ruleid:angular-bypasssecuritytrust\n        let resource_url = this.sanitizer.bypassSecurityTrustResourceUrl(value);\n        // ruleid:angular-bypasssecuritytrust\n        let url = this.sanitizer.bypassSecurityTrustUrl(value);\n\n\n        // ok:angular-bypasssecuritytrust\n        let url1 = this.sanitizer.bypassSecurityTrustUrl(\"a\");\n        // ok:angular-bypasssecuritytrust\n        let html1 = this.sanitizer.bypassSecurityTrustHtml(\"value\");\n        // ok:angular-bypasssecuritytrust\n        let html2 = this.sanitizer.bypassSecurityTrustHtml(DOMPurify.sanitize(\"value\"))\n    }\n}\n",
  },
  bugReport: "Imported from semgrep rule 'angular-bypasssecuritytrust': Detected the use of `$TRUST`. This can introduce a Cross-Site-Scripting (XSS) vulnerability if this comes from user-provided input. If you have to use `$TRUST`, ensure it does not come from user-input or use the appropriate prevention mechanism e.g. input validation or sanitization depending on the context. metadata: cwe: - \"CWE-79: Improper Neutralization of Input During Web Page Generation ('Cro (WARNING). Found at src/angular-domsanitizer.ts line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'angular-bypasssecuritytrust': Detected the use of `$TRUST`. This can introduce a Cross-Site-",
        failureDescription: "Imported from semgrep rule 'angular-bypasssecuritytrust': Detected the use of `$TRUST`. This can introduce a Cross-Site-Scripting (XSS) vulnerability if this comes from user-provided input. If you hav",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/angular-domsanitizer.ts", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
