/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-detect-pseudoRandomBytes",
  bugClass: "novel",
  files: {
    ["src/detect-pseudoRandomBytes.js"]: "// ok:detect-pseudoRandomBytes\ncrypto.randomBytes\n\n// ruleid:detect-pseudoRandomBytes\ncrypto.pseudoRandomBytes\n",
  },
  bugReport: "Imported from semgrep rule 'detect-pseudoRandomBytes': Detected usage of crypto.pseudoRandomBytes, which does not produce secure random numbers. metadata: cwe: - 'CWE-338: Use of Cryptographically Weak Pseudo-Random Number Generator (PRNG)' owasp: - A02:2021 - Cryptographic Failures - A04:2025 - Cryptographic Failures source-rule-url: https://github.com/nodesecurity/eslint-plugin-security/blob/master/rules/detect-pseudoRandomBytes.js asvs: section: 'V (WARNING). Found at src/detect-pseudoRandomBytes.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'detect-pseudoRandomBytes': Detected usage of crypto.pseudoRandomBytes, which does not produc",
        failureDescription: "Imported from semgrep rule 'detect-pseudoRandomBytes': Detected usage of crypto.pseudoRandomBytes, which does not produce secure random numbers. metadata: cwe: - 'CWE-338: Use of Cryptographically Wea",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/detect-pseudoRandomBytes.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
