/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-express-third-party-object-deserialization",
  bugClass: "novel",
  files: {
    ["src/express-third-party-object-deserialization.ts"]: "var node_serialize = require(\"node-serialize\")\nvar serialize_to_js = require('serialize-to-js');\n\nmodule.exports.value = function (req,res){\n\t// ruleid: express-third-party-object-deserialization\n\tnode_serialize.unserialize(req.files.products.data.toString('utf8'))\n\t// ok: express-third-party-object-deserialization\n\tfake.unserialize(req.files)\n}\n\n\nmodule.exports.value1 = function (req,res){\n\tvar str = new Buffer(req.cookies.profile, 'base64').toString();\n\t// ruleid: express-third-party-object-deserialization\n\tserialize_to_js.deserialize(str)\n\t// ok: express-third-party-object-deserialization\n\tfoo.deserialize(str)\n}\n",
  },
  bugReport: "Imported from semgrep rule 'express-third-party-object-deserialization': The following function call $SER.$FUNC accepts user controlled data which can result in Remote (WARNING). Found at src/express-third-party-object-deserialization.ts line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'express-third-party-object-deserialization': The following function call $SER.$FUNC accepts ",
        failureDescription: "Imported from semgrep rule 'express-third-party-object-deserialization': The following function call $SER.$FUNC accepts user controlled data which can result in Remote (WARNING). Found at src/express-",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/express-third-party-object-deserialization.ts", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
