/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-res-render-injection",
  bugClass: "novel",
  files: {
    ["src/res-render-injection.js"]: "const express = require('express')\nconst app = express()\nconst port = 3000\n\nconst hardcodedPath = 'lib/layout'\n\nfunction testController1(req, res) {\n    // ruleid: res-render-injection\n    return res.render(`tpl.${req.query.path}`, {foo: bar})\n};\n\napp.get('/test1', testController1)\n\napp.get('/test2', (req, res) => {\n    // ruleid: res-render-injection\n    return res.render('tpl.' + req.query.path + '.smth-else', {foo: bar})\n})\n\napp.get('/ok-test', (req, res) => {\n    // ok: res-render-injection\n    return res.render(hardcodedPath, {foo: bar})\n})\n\napp.listen(port, () => console.log(`Example app listening at http://localhost:${port}`))\n",
  },
  bugReport: "Imported from semgrep rule 'res-render-injection': User controllable data `$REQ` enters `$RES.render(...)` this can lead to the loading of other HTML/templating pages that they may not be authorized to render. An attacker may attempt to use directory traversal techniques e.g. `../folder/index` to access other HTML pages on the file system. Where possible, do not allow users to define what should be loaded in $RES.render or use an allow list for th (WARNING). Found at src/res-render-injection.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'res-render-injection': User controllable data `$REQ` enters `$RES.render(...)` this can lead",
        failureDescription: "Imported from semgrep rule 'res-render-injection': User controllable data `$REQ` enters `$RES.render(...)` this can lead to the loading of other HTML/templating pages that they may not be authorized t",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/res-render-injection.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
