/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-knex-sqli",
  bugClass: "novel",
  files: {
    ["src/knex-sqli.js"]: "import knex from \"knex\";\nimport Knex from \"knex\";\n\nexports.handler = async (event) => {\n  const connection = knex({\n    client: \"mysql\",\n    connection: {\n      host: process.env.DB_HOST,\n      port: Number(process.env.DB_PORT || \"3306\"),\n      user: process.env.DB_USER,\n      password: process.env.DB_PASSWORD,\n      database: process.env.DB_DATABASE,\n    },\n  });\n\n  // ruleid: knex-sqli\n  await connection.raw(`\n    INSERT INTO  (id, character, cartoon, link)\n    VALUES(\n        '${event.id}', \n        '${event.character}',\n        '${event.cartoon}', \n        '${event.link}'\n    )\n    `);\n\n  // ok: knex-sqli\n  await connection.raw('SELECT * FROM foobar');\n};",
  },
  bugReport: "Imported from semgrep rule 'knex-sqli': Detected SQL statement that is tainted by `$EVENT` object. This could lead to SQL injection if the variable is user-controlled and not properly sanitized. In order to prevent SQL injection, use parameterized queries or prepared statements instead. You can use parameterized statements like so: `knex.raw('SELECT $1 from table', [userinput])` metadata: references: - https://knexjs.org/#Builder-fromRa (WARNING). Found at src/knex-sqli.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'knex-sqli': Detected SQL statement that is tainted by `$EVENT` object. This could lead to SQ",
        failureDescription: "Imported from semgrep rule 'knex-sqli': Detected SQL statement that is tainted by `$EVENT` object. This could lead to SQL injection if the variable is user-controlled and not properly sanitized. In or",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/knex-sqli.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
