/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-monaco-hover-htmlsupport",
  bugClass: "novel",
  files: {
    ["src/monaco-hover-htmlsupport.js"]: "import { editor, languages, Range } from \"monaco-editor\";\n\nfunction test1 (userInput) {\n  languages.registerHoverProvider('mySpecialLanguage', {\n    provideHover: function (model) {\n      return {\n        range: new Range(1, 1, model.getLineCount(), model.getLineMaxColumn(model.getLineCount())),\n        contents: [\n          // ruleid:monaco-hover-htmlsupport\n          {\n            value: `<a href=\"${userInput}\">Hello</a>`,\n            supportHtml: true,\n            isTrusted: true\n          },\n        ]\n      }\n    }\n  });\n}\n\nfunction okTest1 () {\n  languages.registerHoverProvider('mySpecialLanguage', {\n    provideHover: function (model) {\n      return {\n        range: new Range(1, 1, model.getLineCount(), model.getLineMaxColumn(model.getLineCount())),\n        contents: [\n          {\n            value: `<a href=\"//google.com\">Hello</a>`,\n            supportHtml: true,\n            isTrusted: true\n          },\n        ]\n      }\n    }\n  });\n}\n\nfunction okTest2 (userInput) {\n  languages.registerHoverProvider('mySpecialLanguage', {\n    provideHover: function (model) {\n      return {\n        range: new Range(1, 1, model.getLineCount(), model.getLineMaxColumn(model.getLineCount())),\n        contents: [\n          {\n            value: `** Hello ${userInput}`,\n          },\n        ]\n      }\n    }\n  });\n}\n",
  },
  bugReport: "Imported from semgrep rule 'monaco-hover-htmlsupport': If user input reaches `HoverProvider` while `supportHml` is set to `true` it may introduce an XSS vulnerability. Do not produce HTML for hovers with dynamically generated input. metadata: cwe: - \"CWE-79: Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')\" owasp: - A07:2017 - Cross-Site Scripting (XSS) - A03:2021 - Injection - A05:2025 - Injection references: - htt (WARNING). Found at src/monaco-hover-htmlsupport.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'monaco-hover-htmlsupport': If user input reaches `HoverProvider` while `supportHml` is set t",
        failureDescription: "Imported from semgrep rule 'monaco-hover-htmlsupport': If user input reaches `HoverProvider` while `supportHml` is set to `true` it may introduce an XSS vulnerability. Do not produce HTML for hovers w",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/monaco-hover-htmlsupport.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
