/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-express-check-csurf-middleware-usage",
  bugClass: "novel",
  files: {
    ["src/express-check-csurf-middleware-usage.js"]: "var cookieParser = require('cookie-parser') //for cookie parsing\n// var csrf = require('csurf') //csrf module\nvar bodyParser = require('body-parser') //for body parsing\n\nvar express = require('express')\n\n// setup route middlewares\nvar csrfProtection = csrf({\n    cookie: true\n})\nvar parseForm = bodyParser.urlencoded({\n    extended: false\n})\n\n// ruleid: express-check-csurf-middleware-usage\nvar app = express()\n\n// parse cookies\napp.use(cookieParser())\n\napp.get('/form', csrfProtection, function(req, res) {\n    // generate and pass the csrfToken to the view\n    res.render('send', {\n        csrfToken: req.csrfToken()\n    })\n})\n\napp.post('/process', parseForm, csrfProtection, function(req, res) {\n    res.send('data is being processed')\n})\n\napp.post('/bad', parseForm, function(req, res) {\n    res.send('data is being processed')\n})\n",
  },
  bugReport: "Imported from semgrep rule 'express-check-csurf-middleware-usage': A CSRF middleware was not detected in your express application. Ensure you are either using one such as `csurf` or `csrf` (see rule references) and/or you are properly doing CSRF validation in your routes with a token or cookies. metadata: category: security references: - https://www.npmjs.com/package/csurf - https://www.npmjs.com/package/csrf - https://cheatsheetseries.owasp.org/cheatsheets/Cross (INFO). Found at src/express-check-csurf-middleware-usage.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'express-check-csurf-middleware-usage': A CSRF middleware was not detected in your express ap",
        failureDescription: "Imported from semgrep rule 'express-check-csurf-middleware-usage': A CSRF middleware was not detected in your express application. Ensure you are either using one such as `csurf` or `csrf` (see rule r",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/express-check-csurf-middleware-usage.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
