/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-detect-buffer-noassert",
  bugClass: "novel",
  files: {
    ["src/detect-buffer-noassert.js"]: "// ok:detect-buffer-noassert\na.readUInt8(0)\n\n// ok:detect-buffer-noassert\na.readUInt8(0, false)\n\n// ruleid:detect-buffer-noassert\na.readUInt8(0, true)\n\n// ruleid:detect-buffer-noassert\na.writeFloatLE(0, true)\n",
  },
  bugReport: "Imported from semgrep rule 'detect-buffer-noassert': Detected usage of noassert in Buffer API, which allows the offset the be beyond the end of the buffer. This could result in writing or reading beyond the end of the buffer. metadata: cwe: - 'CWE-119: Improper Restriction of Operations within the Bounds of a Memory Buffer' source-rule-url: https://github.com/nodesecurity/eslint-plugin-security/blob/master/rules/detect-buffer-noassert.js category: s (WARNING). Found at src/detect-buffer-noassert.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'detect-buffer-noassert': Detected usage of noassert in Buffer API, which allows the offset t",
        failureDescription: "Imported from semgrep rule 'detect-buffer-noassert': Detected usage of noassert in Buffer API, which allows the offset the be beyond the end of the buffer. This could result in writing or reading beyo",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/detect-buffer-noassert.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
