/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-express-data-exfiltration",
  bugClass: "novel",
  files: {
    ["src/express-data-exfiltration.js"]: "const express = require('express')\nconst app = express()\nconst port = 3000\n\nfunction testController1(req, res) {\n    try {\n        const defaultData = {foo: true}\n        // ruleid: express-data-exfiltration\n        let data = Object.assign(defaultData, req.query)\n        doSmthWith(data)\n    } catch (err) {\n        this.log.error(err);\n    }\n    res.end('ok')\n};\napp.get('/test1', testController1)\n\nlet testController2 = function (req, res) {\n    const defaultData = {foo: {bar: true}}\n    // ruleid: express-data-exfiltration\n    let data = Object.assign(defaultData, {foo: req.query})\n    doSmthWith(data)\n    return res.send({ok: true})\n\n}\napp.get('/test2', testController2)\n\nvar testController3 = null;\ntestController3 = function (req, res) {\n    const defaultData = {foo: true}\n    let newData = req.body\n    // ruleid: express-data-exfiltration\n    let data = Object.assign(defaultData, newData)\n    doSmthWith(data)\n    return res.send({ok: true})\n}\napp.get('/test3', testController3)\n\napp.get('/ok-test', (req, res) => {\n    const defaultData = {foo: req.body.foo}\n    let newData = {bar: '123'}\n    // ruleid: express-data-exfiltration\n    let data = Object.assign(defaultData, newData)\n    doSmthWith(data)\n    return res.send(func())\n})\n\nlet okController = function (req, res) {\n    const defaultData = {foo: {bar: true}}\n    // ok: express-data-exfiltration\n    let data = Object.assign(defaultData, {foo: getFoo()})\n    doSmthWith(data)\n    return res.send({ok: true})\n}\napp.get('/ok-test2', okController)\n\napp.listen(port, () => console.log(`Example app listening at http://localhost:${port}`))\n",
  },
  bugReport: "Imported from semgrep rule 'express-data-exfiltration': Depending on the context, user control data in `Object.assign` can cause web response to include data that it should not have or can lead to a mass assignment vulnerability. metadata: owasp: - A08:2021 - Software and Data Integrity Failures - A08:2025 - Software or Data Integrity Failures cwe: - 'CWE-915: Improperly Controlled Modification of Dynamically-Determined Object Attributes' references: - (WARNING). Found at src/express-data-exfiltration.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'express-data-exfiltration': Depending on the context, user control data in `Object.assign` c",
        failureDescription: "Imported from semgrep rule 'express-data-exfiltration': Depending on the context, user control data in `Object.assign` can cause web response to include data that it should not have or can lead to a m",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/express-data-exfiltration.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
