/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-unsafe-dynamic-method",
  bugClass: "novel",
  files: {
    ["src/unsafe-dynamic-method.js"]: "function test1(data) {\n  const message = JSON.parse(data);\n  // ruleid:unsafe-dynamic-method\n  window[message.name](message.payload);\n}\n\nfunction test2(data) {\n  const message = JSON.parse(data);\n  // ruleid:unsafe-dynamic-method\n  const action = window[message.name];\n  action(message.payload);\n}\n\nlet api = {\n  foo: function () { /* do smth */ },\n  bar: function () { /* do smth */ }\n}\n\nfunction okTest1(data) {\n  const message = JSON.parse(data);\n  if (!api.hasOwnProperty(message.name)) {\n    return;\n  }\n  // ok:unsafe-dynamic-method\n  api[message.name](message.payload);\n}\n\nfunction okTest2(data) {\n  // ok:unsafe-dynamic-method\n  const result = api[\"foo\"](data);\n  console.log(result);\n}\n\nfunction okTest3(data) {\n  // ok:unsafe-dynamic-method\n  const result = actions[1](data);\n  console.log(result);\n}\n\nfunction okTest4(data) {\n  const actions = api = {\n    foo: function () { /* do smth */ },\n    bar: function () { /* do smth */ }\n  }\n  let result = null\n  Object.keys(actions).forEach(a => {\n    // ok:unsafe-dynamic-method\n    result = actions[a](result);\n  })\n  console.log(result);\n}\n",
  },
  bugReport: "Imported from semgrep rule 'unsafe-dynamic-method': Using non-static data to retrieve and run functions from the object is dangerous. If the data is user-controlled, it may allow executing arbitrary code. metadata: owasp: - A03:2021 - Injection - A05:2025 - Injection cwe: - \"CWE-94: Improper Control of Generation of Code ('Code Injection')\" category: security technology: - javascript cwe2022-top25: true subcategory: - audit likelihood: LOW impact:  (WARNING). Found at src/unsafe-dynamic-method.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'unsafe-dynamic-method': Using non-static data to retrieve and run functions from the object ",
        failureDescription: "Imported from semgrep rule 'unsafe-dynamic-method': Using non-static data to retrieve and run functions from the object is dangerous. If the data is user-controlled, it may allow executing arbitrary c",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/unsafe-dynamic-method.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
