/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-detect-disable-mustache-escape",
  bugClass: "novel",
  files: {
    ["src/detect-disable-mustache-escape.js"]: "// ruleid: detect-disable-mustache-escape\na.escapeMarkup = false;\n\n// deeptodook: detect-disable-mustache-escape\nescapeMarkup = false;\n",
  },
  bugReport: "Imported from semgrep rule 'detect-disable-mustache-escape': Markup escaping disabled. This can be used with some template engines to escape disabling of HTML entities, which can lead to XSS attacks. metadata: cwe: - 'CWE-116: Improper Encoding or Escaping of Output' owasp: - A03:2021 - Injection - A05:2025 - Injection source-rule-url: https://github.com/nodesecurity/eslint-plugin-security/blob/master/rules/detect-disable-mustache-escape.js category: securi (WARNING). Found at src/detect-disable-mustache-escape.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'detect-disable-mustache-escape': Markup escaping disabled. This can be used with some templa",
        failureDescription: "Imported from semgrep rule 'detect-disable-mustache-escape': Markup escaping disabled. This can be used with some template engines to escape disabling of HTML entities, which can lead to XSS attacks. ",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/detect-disable-mustache-escape.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
