/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-express-open-redirect",
  bugClass: "novel",
  files: {
    ["src/express-open-redirect.js"]: "module.exports.redirect = function (req, res) {\n\n\t// ok: express-open-redirect\n\tres.redirect(`https://reddit.com/${req.query.url}/fooo`)\n\t// ok: express-open-redirect\n\tres.redirect(\"https://google.com/\"+req.query.url)\n\t// ok: express-open-redirect\n\tres.redirect(config_value.foo+req.query.url)\n\t// ok: express-open-redirect\n\tres.redirect(config_value.foo+req.body.shouldalsonotcatch)\n\t// ok: express-open-redirect\n\tres.redirect(config_value.foo+req)\n\n\t// ruleid: express-open-redirect\n\tres.redirect(req.body.url)\n\t// ruleid: express-open-redirect\n\tres.redirect(`${req.query.url}/fooo`)\n\t// ruleid: express-open-redirect\n\tres.redirect(req.query.url+config_value.url)\n\n\tconst a = req.body.url\n\tconst b = req.body['url']\n\t// ruleid: express-open-redirect\n\tres.redirect(a)\n\t// ruleid: express-open-redirect\n\tres.redirect(`${b}/fooo`)\n\t// ruleid: express-open-redirect\n\tres.redirect(a+config_value.url)\n\n\t// ok: express-open-redirect\n\tres.redirect(c+a)\n\t// ok: express-open-redirect\n\tres.redirect(`${c}${a}/fooo`)\n\t// ok: express-open-redirect\n\tres.redirect(c+a+config_value.url)\n\n\t// ok: express-open-redirect\n\tres.redirect(c)\n\t// ok: express-open-redirect\n\tres.redirect(`${c}`)\n\t// ok: express-open-redirect\n\tres.redirect(c+config_value.url)\n\n\t// ruleid: express-open-redirect\n\tres.redirect(req.body['url'])\n\t// ruleid: express-open-redirect\n\tres.redirect(`${req.body['url']}/fooo`)\n\t// ruleid: express-open-redirect\n\tres.redirect(req.body['url']+config_value.url)\n\n\t// ruleid: express-open-redirect\n\tres.redirect(\"https://\"+req.body['url'])\n\t// ruleid: express-open-redirect\n\tres.redirect(`https://${req.body['url']}/fooo`)\n\t// ruleid: express-open-redirect\n\tres.redirect(\"https://\"+req.body['url']+config_value.url)\n\n\t// todo: express-open-redirect\n\tres.redirect(\"https://google.com\"+req.query.url)\n}\n",
  },
  bugReport: "Imported from semgrep rule 'express-open-redirect': The application redirects to a URL specified by user-supplied input `$REQ` that is not validated. This could redirect users to malicious locations. Consider using an allow-list approach to validate URLs, or warn users they are being redirected to a third-party website. metadata: technology: - express references: - https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Ch (WARNING). Found at src/express-open-redirect.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'express-open-redirect': The application redirects to a URL specified by user-supplied input ",
        failureDescription: "Imported from semgrep rule 'express-open-redirect': The application redirects to a URL specified by user-supplied input `$REQ` that is not validated. This could redirect users to malicious locations. ",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/express-open-redirect.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
