/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-unsafe-argon2-config",
  bugClass: "novel",
  files: {
    ["src/unsafe-argon2-config.js"]: "const argon2 = require(\"argon2\");\n\nconst hashSettings = {\n  type: argon2.argon2i,\n  memoryCost: 2 ** 16,\n  parallelism: os.cpus().length || 8,\n};\n\nconst goodHashSettings = {\n  type: argon2.argon2id,\n  memoryCost: 2 ** 16,\n  parallelism: os.cpus().length || 8,\n};\n\nconst prepareSavingGood = (user) => {\n  if (!user.Password) return Promise.resolve(user);\n\n\n  return argon2\n    // ok: unsafe-argon2-config\n    .hash(user.Password, goodHashSettings)\n    .then((hash) => ({ ...user, Password: hash }))\n    .catch((err) => console.error(`Error during hashing: ${err}`));\n};\n\nconst prepareSavingBad = (user) => {\n  if (!user.Password) return Promise.resolve(user);\n\n\n  return argon2\n    // ruleid:unsafe-argon2-config\n    .hash(user.Password, hashSettings)\n    .then((hash) => ({ ...user, Password: hash }))\n    .catch((err) => console.error(`Error during hashing: ${err}`));\n};\n\nconst bad = (user) => {\n  if (!user.Password) return Promise.resolve(user);\n  const hashSettings = {\n    type: argon2.argon2i,\n    memoryCost: 2 ** 16,\n    parallelism: os.cpus().length || 8,\n  };\n\n  return argon2\n    // ruleid:unsafe-argon2-config\n    .hash(user.Password, hashSettings)\n    .then((hash) => ({ ...user, Password: hash }))\n    .catch((err) => console.error(`Error during hashing: ${err}`));\n};\n\nfunction okTest(user) {\n  if (!user.Password) return Promise.resolve(user);\n  // ok: unsafe-argon2-config\n  return argon2\n    .hash(user.Password, {\n      type: argon2.argon2id,\n      memoryCost: 2 ** 16,\n      parallelism: os.cpus().length || 8,\n    })\n    .then((hash) => ({ ...user, Password: hash }))\n    .catch((err) => console.error(`Error during hashing: ${err}`));\n}\n",
  },
  bugReport: "Imported from semgrep rule 'unsafe-argon2-config': Prefer Argon2id where possible. Per RFC9016, section 4 IETF recommends selecting Argon2id unless you can guarantee an adversary has no direct access to the computing environment. metadata: references: - https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html - https://eprint.iacr.org/2016/759.pdf - https://www.cs.tau.ac.il/~tromer/papers/cache-joc-20090619.pdf - https://da (WARNING). Found at src/unsafe-argon2-config.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'unsafe-argon2-config': Prefer Argon2id where possible. Per RFC9016, section 4 IETF recommend",
        failureDescription: "Imported from semgrep rule 'unsafe-argon2-config': Prefer Argon2id where possible. Per RFC9016, section 4 IETF recommends selecting Argon2id unless you can guarantee an adversary has no direct access ",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/unsafe-argon2-config.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
