/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-cors-misconfiguration",
  bugClass: "novel",
  files: {
    ["src/cors-misconfiguration.js"]: "const express = require('express');\n\nconst app = express();\n\napp.get('/test1', function (req, res) {\n    const origin = req.query.origin;\n    // ruleid: cors-misconfiguration\n    res.writeHead(200, { 'Access-Control-Allow-Origin': origin });\n});\n\napp.get('/test2', function (req, res) {\n    res.set({\n        'Content-Length': 123,\n        // ruleid: cors-misconfiguration\n        'access-control-allow-origin': req.body.origin,\n        'ETag': '12345'\n    })\n});\n\napp.get('/test3', function (req, res) {\n    let origin = req.query.origin\n    // ruleid: cors-misconfiguration\n    res.set('access-control-allow-origin', origin)\n});\n\napp.get('/okTest1', function (req, res) {\n    foobar()\n    // ok: cors-misconfiguration\n    res.set('access-control-allow-origin', 'xyz.com')\n});\n",
  },
  bugReport: "Imported from semgrep rule 'cors-misconfiguration': By letting user input control CORS parameters, there is a risk that software does not properly verify that the source of data or communication is valid. Use literal values for CORS settings. metadata: owasp: - A07:2021 - Identification and Authentication Failures - A07:2025 - Authentication Failures cwe: - 'CWE-346: Origin Validation Error' category: security references: - https://developer.mozill (WARNING). Found at src/cors-misconfiguration.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'cors-misconfiguration': By letting user input control CORS parameters, there is a risk that ",
        failureDescription: "Imported from semgrep rule 'cors-misconfiguration': By letting user input control CORS parameters, there is a risk that software does not properly verify that the source of data or communication is va",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/cors-misconfiguration.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
