/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-detect-anthropic",
  bugClass: "novel",
  files: {
    ["src/detect-anthropic.ts"]: "// ruleid: detect-anthropic\nimport Anthropic from '@anthropic-ai/sdk';\n\n// ruleid: detect-anthropic\nconst anthropic = new Anthropic({\n  apiKey: 'my_api_key', // defaults to process.env[\"ANTHROPIC_API_KEY\"]\n});\n\n// ruleid: detect-anthropic\nconst msg = await anthropic.messages.create({\n  model: \"claude-3-opus-20240229\",\n  max_tokens: 1024,\n  messages: [{ role: \"user\", content: \"Hello, Claude\" }],\n});\nconsole.log(msg);",
  },
  bugReport: "Imported from semgrep rule 'detect-anthropic': Possibly found usage of AI: Anthropic (INFO). Found at src/detect-anthropic.ts line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'detect-anthropic': Possibly found usage of AI: Anthropic (INFO). Found at src/detect-anthrop",
        failureDescription: "Imported from semgrep rule 'detect-anthropic': Possibly found usage of AI: Anthropic (INFO). Found at src/detect-anthropic.ts line 1.",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/detect-anthropic.ts", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
