/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-missing-template-string-indicator",
  bugClass: "novel",
  files: {
    ["src/missing-template-string-indicator.js"]: "function name() {\n  // ok: missing-template-string-indicator\n  return `this is ${start.line}`\n}\n\nfunction ok() {\n  // ok: missing-template-string-indicator\n  `test`;\n  if (true) { a = 3; }\n  `test`;\n}\n\nfunction name2() {\n  // ruleid: missing-template-string-indicator\n  return `this is {start.line}`\n}\n\nfunction name3() {\n  // ok: missing-template-string-indicator\n  return \"this is ${start.line}\"\n}\n\n\nfunction name3() {\n  // ok: missing-template-string-indicator\n  return \"this is {start.line}\"\n}\n",
  },
  bugReport: "Imported from semgrep rule 'missing-template-string-indicator': This looks like a JavaScript template string. Are you missing a '$' in front of '{...}'? severity: INFO metadata: category: correctness technology: - js (INFO). Found at src/missing-template-string-indicator.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'missing-template-string-indicator': This looks like a JavaScript template string. Are you mi",
        failureDescription: "Imported from semgrep rule 'missing-template-string-indicator': This looks like a JavaScript template string. Are you missing a '$' in front of '{...}'? severity: INFO metadata: category: correctness ",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/missing-template-string-indicator.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
