/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-no-stringify-keys",
  bugClass: "novel",
  files: {
    ["src/no-stringify-keys.jsx"]: "import stableStringify from \"json-stable-stringify\";\n\nconst stringify = JSON.stringify;\n\n// ruleid:no-stringify-keys\nhashed[JSON.stringify(obj)] = obj;\n\n// ruleid:no-stringify-keys\nconst result = hashed[JSON.stringify(obj)];\n\n// ruleid:no-stringify-keys\nhashed[stringify(obj)] = obj;\n\n// ruleid:no-stringify-keys\nconst result = hashed[stringify(obj)];\n\n//ok\nhashed[stableStringify(obj)] = obj;\n\n//ok\nconst result = hashed[stableStringify(obj)]",
  },
  bugReport: "Imported from semgrep rule 'no-stringify-keys': JSON stringify does not produce a stable key ordering, and should not be relied on for producing object keys. Consider using json-stable-stringify instead. languages: - javascript - typescript severity: WARNING metadata: category: correctness references: - https://www.npmjs.com/package/json-stable-stringify - https://stackoverflow.com/a/16168003 technology: - javascript - typescript (WARNING). Found at src/no-stringify-keys.jsx line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'no-stringify-keys': JSON stringify does not produce a stable key ordering, and should not be",
        failureDescription: "Imported from semgrep rule 'no-stringify-keys': JSON stringify does not produce a stable key ordering, and should not be relied on for producing object keys. Consider using json-stable-stringify inste",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/no-stringify-keys.jsx", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
