/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-jquery-insecure-method",
  bugClass: "novel",
  files: {
    ["src/jquery-insecure-method.js"]: "(function ($) {\n\n  function bad1() {\n    var content = '<div>' + window.location.hash + '</div>';\n    // ruleid: jquery-insecure-method\n    $( \"div\" ).html( content );\n  }\n\n  function bad2() {\n    // ruleid: jquery-insecure-method\n    $( userInput ).appendTo( \"#foo\" );\n  }\n\n  function bad4() {\n    // ruleid: jquery-insecure-method\n    $('<div>' + window.location.hash + '</div>').insertBefore( \".inner\" );\n    // ruleid: jquery-insecure-method\n    $('.inner').prepend(window.location.hash);\n    function test() {\n    // ruleid: jquery-insecure-method\n      jQuery.globalEval('<div>' + window.location.hash + '</div>', {\n        nonce: \"nonce-2726c7f26c\"\n      } );\n    }\n  }\n\n  function bad5(userInput) {\n    // ruleid: jquery-insecure-method\n    $( \".inner\" ).wrap( \"<div class='new'>\" + userInput + \"</div>\" );\n    // ruleid: jquery-insecure-method\n    $( \"p\" ).wrapAll(userInput);\n  }\n\n\n  function bad6() {\n    $.get(\n      `/foo/${x}`,\n      (response) => {\n        let select = $('foo')\n        for (let d of response.data) {\n            let bar = $(new Data(d))\n            // ruleid: jquery-insecure-method\n            select.append(bar)\n        }\n      }\n    );\n  }\n\n  function ok1() {\n    const item = '<div></div>';\n    // ok: jquery-insecure-method\n    $( \".inner\" ).wrap(item);\n  }\n\n  function ok2(userInput) {\n    // ok: jquery-insecure-method\n    $( \"div\" ).html( '<div></div>' );\n  }\n\n  function ok3(userInput) {\n    jQuery(document).ready(function($){\n      // ok: jquery-insecure-method\n      $('<input type=\"checkbox\"/>').prependTo('.checklist-box li');\n    });\n  }\n\n  function ok4(userInput) {\n      // ok: jquery-insecure-method\n      var url = this.prependRestapi(userInput);\n      fooBar(url);\n  }\n\n})(jQUery);\n",
  },
  bugReport: "Imported from semgrep rule 'jquery-insecure-method': User controlled data in a jQuery's `.$METHOD(...)` is an anti-pattern that can lead to XSS vulnerabilities metadata: cwe: - \"CWE-79: Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')\" owasp: - A07:2017 - Cross-Site Scripting (XSS) - A03:2021 - Injection - A05:2025 - Injection references: - https://owasp.org/www-community/attacks/xss/ - https://bugs.jquery.com/tic (WARNING). Found at src/jquery-insecure-method.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'jquery-insecure-method': User controlled data in a jQuery's `.$METHOD(...)` is an anti-patte",
        failureDescription: "Imported from semgrep rule 'jquery-insecure-method': User controlled data in a jQuery's `.$METHOD(...)` is an anti-pattern that can lead to XSS vulnerabilities metadata: cwe: - \"CWE-79: Improper Neutr",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/jquery-insecure-method.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
