/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-detect-angular-element-taint",
  bugClass: "novel",
  files: {
    ["src/detect-angular-element-taint.js"]: "var app = angular.module('MyApp', []);\napp.controller('myCtrl', function($scope,$sanitize) {\n    let a = unescape(window.location.href)\n    // ruleid: detect-angular-element-taint\n    angular.element('div').html(a)\n    let b = $sanitize(unescape(window.location.href))\n    // ok: detect-angular-element-taint\n    angular.element('div').html(b)\n    let b = window.location.href\n    // ruleid: detect-angular-element-taint\n    angular.element('div').html((new URLSearchParams(window.location.search)).get('returnUrl'))\n\n});\n",
  },
  bugReport: "Imported from semgrep rule 'detect-angular-element-taint': Use of angular.element can lead to XSS if user-input is treated as part of the HTML element within `$SINK`. It is recommended to contextually output encode user-input, before inserting into `$SINK`. If the HTML needs to be preserved it is recommended to sanitize the input using $sce.getTrustedHTML or $sanitize. metadata: confidence: MEDIUM cwe: - \"CWE-79: Improper Neutralization of Input During We (WARNING). Found at src/detect-angular-element-taint.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'detect-angular-element-taint': Use of angular.element can lead to XSS if user-input is treat",
        failureDescription: "Imported from semgrep rule 'detect-angular-element-taint': Use of angular.element can lead to XSS if user-input is treated as part of the HTML element within `$SINK`. It is recommended to contextually",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/detect-angular-element-taint.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
