/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-detect-angular-open-redirect",
  bugClass: "novel",
  files: {
    ["src/detect-angular-open-redirect.js"]: "var app = angular.module('MyApp', []);\napp.controller('myCtrl', function($scope, $sce) {\n    $scope.userInput = 'foo';\n\n    $scope.sayHello = function() {\n     // ruleid:detect-angular-open-redirect\n     $window.location.href = input + '/app/logout';\n     input = $scope.input;\n     // ruleid:detect-angular-open-redirect\n     $window.location.href = input + '/app/logout';\n\n     //Data is not coming from user input\n     $location.location.location = test\n     // ok:detect-angular-open-redirect\n     $window.location.href = \"//untatintedredirect\"\n   };\n\n});\n",
  },
  bugReport: "Imported from semgrep rule 'detect-angular-open-redirect': Use of $window.location.href can lead to open-redirect if user input is used for redirection. metadata: asvs: section: V5 Validation, Sanitization and Encoding control_id: 5.5.1 Insecue Redirect control_url: https://github.com/OWASP/ASVS/blob/master/4.0/en/0x13-V5-Validation-Sanitization-Encoding.md#v51-input-validation version: '4' references: - https://docs.angularjs.org/api/ng/service/$sce#trus (ERROR). Found at src/detect-angular-open-redirect.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'detect-angular-open-redirect': Use of $window.location.href can lead to open-redirect if use",
        failureDescription: "Imported from semgrep rule 'detect-angular-open-redirect': Use of $window.location.href can lead to open-redirect if user input is used for redirection. metadata: asvs: section: V5 Validation, Sanitiz",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/detect-angular-open-redirect.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
