/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-moment-deprecated",
  bugClass: "novel",
  files: {
    ["src/moment-deprecated.tsx"]: "// ruleid: moment-deprecated\nimport moment from 'moment';\n// ruleid: moment-deprecated\nimport { moment } from 'moment';\n// ruleid: moment-deprecated\nimport { moment, something } from 'moment';\n// ruleid: moment-deprecated\nimport Moment, { moment, something } from 'moment';\n\n// ok: moment-deprecated\nimport dayjs from 'dayjs';\n",
  },
  bugReport: "Imported from semgrep rule 'moment-deprecated': Moment is a legacy project in maintenance mode. Consider using libraries that are actively supported, e.g. `dayjs`. (INFO). Found at src/moment-deprecated.tsx line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'moment-deprecated': Moment is a legacy project in maintenance mode. Consider using libraries",
        failureDescription: "Imported from semgrep rule 'moment-deprecated': Moment is a legacy project in maintenance mode. Consider using libraries that are actively supported, e.g. `dayjs`. (INFO). Found at src/moment-deprecat",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/moment-deprecated.tsx", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
