/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-useless-assignment",
  bugClass: "novel",
  files: {
    ["src/useless-assign.js"]: "// ruleid:useless-assignment\nvar x1 = 1;\nx1 = 2;\n\n// ruleid:useless-assignment\nlet x2 = 1;\nx2 = 2;\n\n// ruleid:useless-assignment\nx3 = 1;\nx3 = 2;\n\n// ok:useless-assignment\nx4 = {value1: 42};\nx4 = {x4, value2: 43};\n\n// ok:useless-assignment\nx5 = {value1: 42};\nx5 = {...x5, value2: 43};\n\n// ok:useless-assignment\ny = [1, 2];\ny = y.map(function(e) { return e * 2; });\n\n// ok:useless-assignment\nz = [1, 2];\nz = z.map(e => e * 2);\n\n// ok:useless-assignment\na = \"Hi \";\na += \"Mom\";\n\n// ok:useless-assignment\nb = i;\nb = f(1, b);\n\n// ok:useless-assignment\nc = j;\nc = f(1, g(c));\n",
  },
  bugReport: "Imported from semgrep rule 'useless-assignment': `$X` is assigned twice; the first assignment is useless (INFO). Found at src/useless-assign.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'useless-assignment': `$X` is assigned twice; the first assignment is useless (INFO). Found a",
        failureDescription: "Imported from semgrep rule 'useless-assignment': `$X` is assigned twice; the first assignment is useless (INFO). Found at src/useless-assign.js line 1.",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/useless-assign.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
