/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-react-props-spreading",
  bugClass: "novel",
  files: {
    ["src/react-props-spreading.tsx"]: "function Test1(props) {\n// ruleid: react-props-spreading\n    const el = <App {...props} />;\n    return el;\n}\n\nfunction Test2(props) {\n// ruleid: react-props-spreading\n    const el = <MyCustomComponent {...props} some_other_prop={some_other_prop} />;\n    return el;\n}\n\nfunction Test2(props, otherProps) {\n    const {src, alt} = props;\n    const {one_prop, two_prop} = otherProps;\n// ok: react-props-spreading\n    return <MyCustomComponent one_prop={one_prop} two_prop={two_prop} />;\n}\n",
  },
  bugReport: "Imported from semgrep rule 'react-props-spreading': It's best practice to explicitly pass props to an HTML component rather than use the spread operator. The spread operator risks passing invalid HTML props to an HTML element, which can cause console warnings or worse, give malicious actors a way to inject unexpected attributes. languages: - typescript - javascript severity: INFO metadata: source-rule-url: https://github.com/yannickcr/eslint-plugin (INFO). Found at src/react-props-spreading.tsx line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'react-props-spreading': It's best practice to explicitly pass props to an HTML component rat",
        failureDescription: "Imported from semgrep rule 'react-props-spreading': It's best practice to explicitly pass props to an HTML component rather than use the spread operator. The spread operator risks passing invalid HTML",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/react-props-spreading.tsx", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
