/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-md5-used-as-password",
  bugClass: "novel",
  files: {
    ["src/md5-used-as-password.js"]: "const crypto = require(\"crypto\");\n\nfunction ex1(user, pwtext) {\n    digest = crypto.createHash(\"md5\").update(pwtext).digest(\"hex\");\n    // ruleid: md5-used-as-password\n    user.setPassword(digest);\n}\n\nfunction ok1(user, pwtext) {\n    digest = crypto.createHash(\"sha256\").update(pwtext).digest(\"hex\");\n    // ok: md5-used-as-password\n    user.setPassword(digest);\n}\n",
  },
  bugReport: "Imported from semgrep rule 'md5-used-as-password': It looks like MD5 is used as a password hash. MD5 is not considered a secure password hash because it can be cracked by an attacker in a short amount of time. Use a suitable password hashing function such as bcrypt. You can use the `bcrypt` node.js package. metadata: category: security technology: - crypto - md5 references: - https://tools.ietf.org/id/draft-lvelvindron-tls-md5-sha1-deprecate-01.ht (WARNING). Found at src/md5-used-as-password.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'md5-used-as-password': It looks like MD5 is used as a password hash. MD5 is not considered a",
        failureDescription: "Imported from semgrep rule 'md5-used-as-password': It looks like MD5 is used as a password hash. MD5 is not considered a secure password hash because it can be cracked by an attacker in a short amount",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/md5-used-as-password.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
