/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-react-markdown-insecure-html",
  bugClass: "novel",
  files: {
    ["src/react-markdown-insecure-html.tsx"]: "import ReactMarkdown from \"react-markdown\";\nimport htmlParser from \"react-markdown/plugins/html-parser\";\n\n// For more info on the processing instructions, see\n// <https://github.com/aknuds1/html-to-react#with-custom-processing-instructions>\nconst parseHtml = htmlParser({\n  isValidNode: (node) => node.type !== 'script',\n  processingInstructions: [\n    /* ... */\n  ]\n})\n\nfunction bad1() {\n// ruleid: react-markdown-insecure-html\n    return <ReactMarkdown astPlugins={[parseHtml]} allowDangerousHtml children={markdown} />;\n}\n\nfunction bad2() {\n// ruleid: react-markdown-insecure-html\n    return <ReactMarkdown astPlugins={[parseHtml]} escapeHtml={false} children={markdown} />;\n}\n\nfunction ok1() {\n// ok: react-markdown-insecure-html\n    return <ReactMarkdown renderers={renderers} children={markdown} />;\n}\n\nfunction ok2() {\n// ok: react-markdown-insecure-html\n    return <ReactMarkdown renderers={renderers} escapeHtml={true} children={markdown} />;\n}\n",
  },
  bugReport: "Imported from semgrep rule 'react-markdown-insecure-html': Overwriting `transformLinkUri` or `transformImageUri` to something insecure, or turning `allowDangerousHtml` on, or turning `escapeHtml` off, will open the code up to XSS vectors. metadata: cwe: - \"CWE-79: Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')\" owasp: - A07:2017 - Cross-Site Scripting (XSS) - A03:2021 - Injection - A05:2025 - Injection references: - h (WARNING). Found at src/react-markdown-insecure-html.tsx line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'react-markdown-insecure-html': Overwriting `transformLinkUri` or `transformImageUri` to some",
        failureDescription: "Imported from semgrep rule 'react-markdown-insecure-html': Overwriting `transformLinkUri` or `transformImageUri` to something insecure, or turning `allowDangerousHtml` on, or turning `escapeHtml` off,",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/react-markdown-insecure-html.tsx", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
