/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-detect-non-literal-require",
  bugClass: "novel",
  files: {
    ["src/detect-non-literal-require.js"]: "function dynamicRequire1(packageName) {\n    // ruleid: detect-non-literal-require\n    var a = require(packageName)\n    return a;\n}\n\nfunction dynamicRequire2(source, file) {\n    // ruleid: detect-non-literal-require\n    require(path.resolve(process.cwd(), file, source));\n}\n\nfunction okDynamicRequire1() {\n    var lib = path.join(path.dirname(fs.realpathSync(__filename)), \"index.js\");\n    // ok: detect-non-literal-require\n    require(lib).run(process.argv.slice(2)); \n}\n\nfunction okDynamicRequire2(userInput) {\n    var name = process.env.NAME\n    var path = name + '/smth/path';\n    var mod = path + '/module.js';\n    // ok: detect-non-literal-require\n    require(mk).main(top, userInput);\n}\n\nfunction okDynamicRequire3(userInput) {\n    var lib  = path.join(path.dirname(fs.realpathSync(__filename)), 'lib');\n    // ok: detect-non-literal-require\n    require(lib + '/foobar').run(userInput);\n}\n\nfunction okDynamicRequire4(userInput) {\n    // ok:detect-non-literal-require\n    var a = require('b')\n}\nfunction okDynamicRequire5(userInput) {\n    // ok:detect-non-literal-require\n    var a = require(process.env.VAR)\n}",
  },
  bugReport: "Imported from semgrep rule 'detect-non-literal-require': Detected the use of require(variable). Calling require with a non-literal argument might allow an attacker to load and run arbitrary code, or access arbitrary files. metadata: cwe: - \"CWE-95: Improper Neutralization of Directives in Dynamically Evaluated Code ('Eval Injection')\" owasp: - A03:2021 - Injection - A05:2025 - Injection source-rule-url: https://github.com/nodesecurity/eslint-plugin-secu (WARNING). Found at src/detect-non-literal-require.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'detect-non-literal-require': Detected the use of require(variable). Calling require with a n",
        failureDescription: "Imported from semgrep rule 'detect-non-literal-require': Detected the use of require(variable). Calling require with a non-literal argument might allow an attacker to load and run arbitrary code, or a",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/detect-non-literal-require.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
