/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-express-insecure-template-usage",
  bugClass: "novel",
  files: {
    ["src/express-insecure-template-usage.jsx"]: "import express from 'express';\nimport * as pug from 'pug';\nimport * as jade from 'jade';\nimport * as dot from 'dot';\nimport * as ejs from 'ejs';\nimport * as nunjucks from 'nunjucks';\nimport * as lodash from 'lodash';\nimport * as handlebars from 'handlebars';\nimport * as mustache from 'mustache';\nconst Hogan = require(\"hogan.js\");\nimport * as Eta from 'eta';\nimport * as Sqrl from 'squirrelly'\n\nvar app = express();\n\napp.get('/', function(req, res) {\n    let tainted = req.query.id;\n    // ruleid: express-insecure-template-usage\n    pug.compile(tainted); \n    // ruleid: express-insecure-template-usage\n    pug.render(tainted); \n    // ruleid: express-insecure-template-usage\n    jade.compile(tainted);\n    // ruleid: express-insecure-template-usage\n    jade.render(tainted);\n     // ruleid: express-insecure-template-usage\n    dot.template(tainted); \n    // ruleid: express-insecure-template-usage\n    ejs.render(tainted); \n    // ruleid: express-insecure-template-usage\n    nunjucks.renderString(tainted); \n    // ruleid: express-insecure-template-usage\n    lodash.template(tainted); \n    // ruleid: express-insecure-template-usage\n    dot.compile(tainted); \n    // ruleid: express-insecure-template-usage\n    handlebars.compile(req.query.id); \n    // ruleid: express-insecure-template-usage\n    mustache.render(req.body._); \n    // ruleid: express-insecure-template-usage\n    Hogan.compile(tainted); \n    // ruleid: express-insecure-template-usage\n    Eta.render(tainted); \n    // ruleid: express-insecure-template-usage\n    Sqrl.render(tainted); \n});\n",
  },
  bugReport: "Imported from semgrep rule 'express-insecure-template-usage': User data from `$REQ` is being compiled into the template, which can lead to a Server Side (WARNING). Found at src/express-insecure-template-usage.jsx line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'express-insecure-template-usage': User data from `$REQ` is being compiled into the template,",
        failureDescription: "Imported from semgrep rule 'express-insecure-template-usage': User data from `$REQ` is being compiled into the template, which can lead to a Server Side (WARNING). Found at src/express-insecure-templa",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/express-insecure-template-usage.jsx", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
