/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-incomplete-sanitization",
  bugClass: "novel",
  files: {
    ["src/incomplete-sanitization.js"]: "function escapeQuotes(s) {\n    // ruleid:incomplete-sanitization\n    return s.replace(\"'\", \"''\");\n}\n\nfunction removeTabs(s) {\n    // ruleid:incomplete-sanitization\n    return s.replace('\\t', \"\");\n}\n\nfunction escapeHtml(html) {\n  // ruleid:incomplete-sanitization\n  return html\n    .replace(\"<\", \"\")\n    .replace(\">\", \"\");\n}\n\nfunction okTest(s) {\n    return s.replace(\"foo\", \"bar\");\n}\n\nfunction okEscapeQuotes(s) {\n    return s.replace(/'/g, \"''\");\n}\n",
  },
  bugReport: "Imported from semgrep rule 'incomplete-sanitization': `$STR.replace` method will only replace the first occurrence when used with a string argument ($CHAR). If this method is used for escaping of dangerous data then there is a possibility for a bypass. Try to use sanitization library instead or use a Regex with a global flag. metadata: cwe: - 'CWE-116: Improper Encoding or Escaping of Output' category: security technology: - javascript owasp: - A03:2 (WARNING). Found at src/incomplete-sanitization.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'incomplete-sanitization': `$STR.replace` method will only replace the first occurrence when ",
        failureDescription: "Imported from semgrep rule 'incomplete-sanitization': `$STR.replace` method will only replace the first occurrence when used with a string argument ($CHAR). If this method is used for escaping of dang",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/incomplete-sanitization.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
