/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-detect-child-process",
  bugClass: "novel",
  files: {
    ["src/detect-child-process.ts"]: "import { exec } from 'child_process'\nimport * as cp from 'child_process';\n\nfunction a(args) {\n  // ruleid:detect-child-process\n  exec(`cat *.js ${args[0]}| wc -l`, (error, stdout, stderr) => {\n    console.log(stdout)\n  });\n}\n\nfunction a(userInput) {\n  // ruleid:detect-child-process\n  cp.spawnSync(userInput);\n}\n\n// ok:detect-child-process\nexec('ls')\n\nconst parentMachine = createMachine({\n  id: 'parent',\n  initial: 'waiting',\n  context: {\n    localOne: null\n  },\n  states: {\n    waiting: {\n      entry: assign({\n        // ok:detect-child-process\n        localOne: () => spawn(remoteMachine)  // <--\n      }),\n      on: {\n        'LOCAL.WAKE': {\n          actions: send({ type: 'WAKE' }, { to: (context) => context.localOne })\n        },\n        'REMOTE.ONLINE': { target: 'connected' }\n      }\n    },\n    connected: {}\n  }\n});\n",
  },
  bugReport: "Imported from semgrep rule 'detect-child-process': Detected calls to child_process from a function argument `$FUNC`. This could lead to a command injection if the input is user controllable. Try to avoid calls to child_process, and if it is needed ensure user input is correctly sanitized or sandboxed. metadata: cwe: - \"CWE-78: Improper Neutralization of Special Elements used in an OS Command ('OS Command Injection')\" owasp: - A01:2017 - Injection  (ERROR). Found at src/detect-child-process.ts line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'detect-child-process': Detected calls to child_process from a function argument `$FUNC`. Thi",
        failureDescription: "Imported from semgrep rule 'detect-child-process': Detected calls to child_process from a function argument `$FUNC`. This could lead to a command injection if the input is user controllable. Try to av",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/detect-child-process.ts", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
