/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-tainted-html-string",
  bugClass: "novel",
  files: {
    ["src/tainted-html-string.js"]: "const {format} = require('util');\n\nexports.handler = async function (event, context) {\n  // ruleid: tainted-html-string\n  await sendThisHtmlSomewhere(`<h1>message: ${event.name}</h1>`)\n  \n  // ruleid: tainted-html-string\n  const htmlResult = \"<h1>\" + \"message: \" + event['message'] + \"</h1>\";\n\n  let html = \"<h1> message\"\n  // ruleid: tainted-html-string\n  html = html.concat(event.message)\n  html = html.concat(\"</h1>\")\n  doSmth(html)\n\n  // ruleid: tainted-html-string\n  foobar(format('<div>Message: %s</div>', event.body.name))\n\n  // ok: tainted-html-string\n  foobar(format('Message: %s', event.body.name))\n\n  // ok: tainted-html-string\n  console.log('<div>Message: %s</div>', event.body.name)\n  \n  // ok: tainted-html-string\n  console.error(`<h1>message: ${event.name}</h1>`)\n\n  return { body: htmlResult }\n}\n",
  },
  bugReport: "Imported from semgrep rule 'tainted-html-string': Detected user input flowing into a manually constructed HTML string. You may be accidentally bypassing secure methods of rendering HTML by manually constructing HTML and this could create a cross-site scripting vulnerability, which could let attackers steal sensitive user data. To be sure this is safe, check that the HTML is rendered safely. Otherwise, use templates which will safely render HTML i (WARNING). Found at src/tainted-html-string.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'tainted-html-string': Detected user input flowing into a manually constructed HTML string. Y",
        failureDescription: "Imported from semgrep rule 'tainted-html-string': Detected user input flowing into a manually constructed HTML string. You may be accidentally bypassing secure methods of rendering HTML by manually co",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/tainted-html-string.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
