/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-react-find-dom",
  bugClass: "novel",
  files: {
    ["src/react-find-dom.tsx"]: "class TestComponent1 extends Component {\n  componentDidMount() {\n        // ruleid: react-find-dom\n    findDOMNode(this).scrollIntoView();\n  }\n\n  render() {\n    return <div />\n  }\n}\n\nclass OkComponent1 extends Component {\n  componentDidMount() {\n        // ok: react-find-dom\n    this.node.scrollIntoView();\n  }\n\n  render() {\n    return <div ref={node => this.node = node} />\n  }\n}\n\nclass TestComponent1 extends Component {\n  componentDidMount() {\n        // ruleid: react-find-dom\n    ReactDOM.findDOMNode(this.refs.something).scrollIntoView();\n  }\n\n  render() {\n    return (\n      <div>\n        <div ref='something' />\n      </div>\n    )\n  }\n}\n\nclass OkComponent2 extends Component {\n  componentDidMount() {\n        // ok: react-find-dom\n    this.something.scrollIntoView();\n  }\n\n  render() {\n    return (\n      <div>\n        <div ref={node => this.something = node} />\n      </div>\n    )\n  }\n}\n",
  },
  bugReport: "Imported from semgrep rule 'react-find-dom': findDOMNode is an escape hatch used to access the underlying DOM node. In most cases, use of this escape hatch is discouraged because it pierces the component abstraction. metadata: references: - https://react.dev/reference/react-dom/findDOMNode - https://github.com/yannickcr/eslint-plugin-react/issues/678#issue-165177220 category: best-practice technology: - react languages: - typescript - javasc (WARNING). Found at src/react-find-dom.tsx line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'react-find-dom': findDOMNode is an escape hatch used to access the underlying DOM node. In m",
        failureDescription: "Imported from semgrep rule 'react-find-dom': findDOMNode is an escape hatch used to access the underlying DOM node. In most cases, use of this escape hatch is discouraged because it pierces the compon",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/react-find-dom.tsx", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
