/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-express-libxml-noent",
  bugClass: "novel",
  files: {
    ["src/express-libxml-noent.js"]: "var libxmljs = require(\"libxmljs\");\nvar libxmljs2 = require(\"libxmljs2\");\n\nmodule.exports.foo =  function(req, res) {\n\n\t// ruleid: express-libxml-noent\n\tlibxmljs.parseXmlString(req.files.products.data.toString('utf8'), {noent:true,noblanks:true})\n\t// ruleid: express-libxml-noent\n\tlibxmljs.parseXml(req.query.products, {noent:true,noblanks:true})\n\t// ok: express-libxml-noent\n\tlibxmljs.parseXml(req.files.products.data.toString('utf8'), {noent:false,noblanks:true})\n\t// ruleid: express-libxml-noent\n\tlibxmljs2.parseXmlString(req.body, {noent:true,noblanks:true})\n\t// ruleid: express-libxml-noent\n\tlibxmljs2.parseXml(req.body, {noent:true,noblanks:true})\n\t// ok: express-libxml-noent\n\tlibxmljs2.parseXml(req.body, {noent:false,noblanks:true})\n}\n",
  },
  bugReport: "Imported from semgrep rule 'express-libxml-noent': The libxml library processes user-input with the `noent` attribute is set to `true` which can lead to being vulnerable to XML External Entities (XXE) type attacks. It is recommended to set `noent` to `false` when using this feature to ensure you are protected. options: interfile: true metadata: interfile: true references: - https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevent (ERROR). Found at src/express-libxml-noent.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'express-libxml-noent': The libxml library processes user-input with the `noent` attribute is",
        failureDescription: "Imported from semgrep rule 'express-libxml-noent': The libxml library processes user-input with the `noent` attribute is set to `true` which can lead to being vulnerable to XML External Entities (XXE)",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/express-libxml-noent.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
