/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-nestjs-header-xss-disabled",
  bugClass: "novel",
  files: {
    ["src/nestjs-header-xss-disabled.ts"]: "import { Controller, Get, Header, Redirect, Query } from '@nestjs/common';\nimport { AppService } from './app.service';\n\n// ruleid:nestjs-header-xss-disabled\n@Controller()\nexport class AppController1 {\n  constructor(private readonly appService: AppService) {}\n\n  @Get('test1')\n  @Header('X-XSS-Protection', '0')\n  getHello1(): string {\n    return this.appService.getHello();\n  }\n\n}\n\n@Controller()\nexport class AppController2 {\n  constructor(private readonly appService: AppService) {}\n\n  @Get('test1')\n  @Header('X-XSS-Protection', '1')\n  getHello2(): string {\n    return this.appService.getHello();\n  }\n\n}\n",
  },
  bugReport: "Imported from semgrep rule 'nestjs-header-xss-disabled': X-XSS-Protection header is set to 0. This will disable the browser's XSS Filter. metadata: cwe: - \"CWE-79: Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')\" category: security technology: - nestjs owasp: - A07:2017 - Cross-Site Scripting (XSS) - A03:2021 - Injection - A05:2025 - Injection references: - https://owasp.org/Top10/A03_2021-Injection cwe2022-top25: tr (WARNING). Found at src/nestjs-header-xss-disabled.ts line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'nestjs-header-xss-disabled': X-XSS-Protection header is set to 0. This will disable the brow",
        failureDescription: "Imported from semgrep rule 'nestjs-header-xss-disabled': X-XSS-Protection header is set to 0. This will disable the browser's XSS Filter. metadata: cwe: - \"CWE-79: Improper Neutralization of Input Dur",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/nestjs-header-xss-disabled.ts", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
