/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-express-jwt-hardcoded-secret",
  bugClass: "novel",
  files: {
    ["src/express-jwt-hardcoded-secret.js"]: "var jwt = require('express-jwt');\n\n// ruleid: express-jwt-hardcoded-secret\napp.get('/protected', jwt({ secret: 'shhhhhhared-secret' }), function(req, res) {\n    if (!req.user.admin) return res.sendStatus(401);\n    res.sendStatus(200);\n});\n\n// ruleid: express-jwt-hardcoded-secret\nlet hardcodedSecret = 'shhhhhhared-secret'\n\napp.get('/protected2', jwt({ secret: hardcodedSecret }), function(req, res) {\n    \n    if (!req.user.admin) return res.sendStatus(401);\n    res.sendStatus(200);\n});\n\nlet secret = \"hardcode\"\n\nconst opts = Object.assign({issuer: 'http://issuer'}, {secret: secret})\n\napp.get('/protected3', jwt(opts), function(req, res) {\n    if (!req.user.admin) return res.sendStatus(401);\n    res.sendStatus(200);\n});\n\n// ok: express-jwt-hardcoded-secret\napp.get('/ok-protected', jwt({ secret: process.env.SECRET }), function(req, res) {\n    if (!req.user.admin) return res.sendStatus(401);\n    res.sendStatus(200);\n});\n\n\nlet configSecret = config.get('secret')\nconst opts = Object.assign({issuer: 'http://issuer'}, {secret: configSecret})\n\n// ok: express-jwt-hardcoded-secret\napp.get('/ok-protected', jwt(opts), function(req, res) {\n    if (!req.user.admin) return res.sendStatus(401);\n    res.sendStatus(200);\n});\n",
  },
  bugReport: "Imported from semgrep rule 'express-jwt-hardcoded-secret': A hard-coded credential was detected. It is not recommended to store credentials in source-code, as this risks secrets being leaked and used by either an internal or external malicious adversary. It is recommended to use environment variables to securely provide credentials or retrieve credentials from a secure vault or HSM (Hardware Security Module). options: interfile: true metadata: interfile:  (WARNING). Found at src/express-jwt-hardcoded-secret.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'express-jwt-hardcoded-secret': A hard-coded credential was detected. It is not recommended t",
        failureDescription: "Imported from semgrep rule 'express-jwt-hardcoded-secret': A hard-coded credential was detected. It is not recommended to store credentials in source-code, as this risks secrets being leaked and used ",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/express-jwt-hardcoded-secret.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
