/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-detect-angular-sce-disabled",
  bugClass: "novel",
  files: {
    ["src/detect-angular-sce-disabled.js"]: "var app = angular.module('MyApp', []).config(function ($sceProvider) {\n    // ruleid: detect-angular-sce-disabled\n    $sceProvider.enabled(false);\n});\n app.controller('myCtrl', function($scope) {\n\n $scope.userInput = 'foo';\n     $scope.sayHello = function() {\n      $scope.html = \"Hello <b>\" + $scope.userInput + \"</b>!\"\n\n    };\n\n });\n\n\n  var app = angular.module('MyApp2', []).config(function ($sceProvider) {\n    $sceProvider.enabled(true);\n});\n",
  },
  bugReport: "Imported from semgrep rule 'detect-angular-sce-disabled': $sceProvider is set to false. Disabling Strict Contextual escaping (SCE) in an AngularJS application could provide additional attack surface for XSS vulnerabilities. metadata: cwe: - \"CWE-79: Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')\" references: - https://docs.angularjs.org/api/ng/service/$sce - https://owasp.org/www-chapter-london/assets/slides/OWASPLon (ERROR). Found at src/detect-angular-sce-disabled.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'detect-angular-sce-disabled': $sceProvider is set to false. Disabling Strict Contextual esca",
        failureDescription: "Imported from semgrep rule 'detect-angular-sce-disabled': $sceProvider is set to false. Disabling Strict Contextual escaping (SCE) in an AngularJS application could provide additional attack surface f",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/detect-angular-sce-disabled.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
