/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-unsafe-formatstring",
  bugClass: "novel",
  files: {
    ["src/unsafe-formatstring.js"]: "const util = require('util')\n\nfunction test1(data) {\n  const {user, ip} = data\n  foobar(user)\n  // ruleid: unsafe-formatstring\n  console.log(\"Unauthorized access attempt by \" + user, ip);\n}\n\nfunction test2(data) {\n  const {user, ip} = data\n  foobar(user)\n  const logs = `Unauthorized access attempt by ${user}`\n  // ruleid: unsafe-formatstring\n  console.log(logs, ip);\n}\n\nfunction test3(data) {\n  const {user, ip} = data\n  foobar(user)\n  const logs = `Unauthorized access attempt by ${user} %d`\n  // ruleid: unsafe-formatstring\n  return util.format(logs, ip);\n}\n\nfunction okTest1(data) {\n  const {user, ip} = data\n  foobar(user)\n  const logs = `Unauthorized access attempt by user`\n  // ok: unsafe-formatstring\n  console.log(logs, ip);\n}\n\nfunction okTest2(data) {\n  const {user, ip} = data\n  foobar(user)\n  // ok: unsafe-formatstring\n  console.log(\"Unauthorized access attempt by \" + user);\n}\n\nfunction okTest3(data) {\n  const {user, ip} = data\n  foobar(user)\n  // ok: unsafe-formatstring\n  return util.format(\"Unauthorized access attempt by %d\", ip);\n}\n",
  },
  bugReport: "Imported from semgrep rule 'unsafe-formatstring': Detected string concatenation with a non-literal variable in a util.format / console.log function. If an attacker injects a format specifier in the string, it will forge the log message. Try to use constant values for the format string. metadata: cwe: - 'CWE-134: Use of Externally-Controlled Format String' owasp: - \"A01:2021 - Broken Access Control\" - A01:2025 - Broken Access Control category: sec (INFO). Found at src/unsafe-formatstring.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'unsafe-formatstring': Detected string concatenation with a non-literal variable in a util.fo",
        failureDescription: "Imported from semgrep rule 'unsafe-formatstring': Detected string concatenation with a non-literal variable in a util.format / console.log function. If an attacker injects a format specifier in the st",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/unsafe-formatstring.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
