/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-deno-dangerous-run",
  bugClass: "novel",
  files: {
    ["src/deno-dangerous-run.js"]: "async function okTest() {\n  const p = Deno.run({\n    cmd: [\"echo\", \"hello\"],\n  });\n\n  await p.status();\n}\n\nasync function test1(userInput) {\n  const p = Deno.run({\n    // ruleid: deno-dangerous-run\n    cmd: [userInput, \"hello\"],\n    stdout: \"piped\",\n    stderr: \"piped\",\n  });\n\n  await p.status();\n}\n\nasync function test2(userInput) {\n  const p = Deno.run({\n    // ruleid: deno-dangerous-run\n    cmd: [\"bash\", \"-c\", userInput],\n    stdout: \"piped\",\n    stderr: \"piped\",\n  });\n\n  await p.status();\n}\n",
  },
  bugReport: "Imported from semgrep rule 'deno-dangerous-run': Detected non-literal calls to Deno.run(). This could lead to a command injection vulnerability. metadata: cwe: - \"CWE-78: Improper Neutralization of Special Elements used in an OS Command ('OS Command Injection')\" owasp: - A01:2017 - Injection - A03:2021 - Injection - A05:2025 - Injection category: security technology: - deno references: - https://deno.land/manual/examples/subprocess#simple-exampl (ERROR). Found at src/deno-dangerous-run.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'deno-dangerous-run': Detected non-literal calls to Deno.run(). This could lead to a command ",
        failureDescription: "Imported from semgrep rule 'deno-dangerous-run': Detected non-literal calls to Deno.run(). This could lead to a command injection vulnerability. metadata: cwe: - \"CWE-78: Improper Neutralization of Sp",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/deno-dangerous-run.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
