/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-express-wkhtmltoimage-injection",
  bugClass: "novel",
  files: {
    ["src/express-wkhtml-injection.js"]: "const express = require('express')\nconst app = express()\nconst port = 3000\nconst wkhtmltopdf = require('wkhtmltopdf')\nconst wkhtmltoimage = require('wkhtmltoimage')\n\napp.get('/', async (req, res) => {\n  // ruleid: express-wkhtmltopdf-injection\n  const pdf = wkhtmltopdf(req.query.q, { output: 'vuln.pdf' })\n  res.send(pdf)\n})\n\napp.post('/ok', async (req, res) => {\n  // ok: express-wkhtmltopdf-injection\n  const pdf = wkhtmltopdf('<html></html>', { output: 'vuln.pdf' })\n  res.send(pdf)\n})\n\napp.post('/test', async (req, res) => {\n  // ruleid: express-wkhtmltoimage-injection\n  const img = wkhtmltoimage.generate(req.body, { output: 'vuln.pdf' })\n  res.send(img)\n})\n\napp.post('/test-ok', async (req, res) => {\n  // ok: express-wkhtmltoimage-injection\n  const data = '<html></html>'\n  const img = wkhtmltoimage.generate(data, { output: 'vuln.pdf' })\n  res.send(img)\n})\n\napp.listen(port, () => console.log(`Example app listening at http://localhost:${port}`))\n",
  },
  bugReport: "Imported from semgrep rule 'express-wkhtmltoimage-injection': If unverified user data can reach the `phantom` methods it can result in Server-Side Request Forgery vulnerabilities metadata: owasp: - A10:2021 - Server-Side Request Forgery (SSRF) - A01:2025 - Broken Access Control cwe: - 'CWE-918: Server-Side Request Forgery (SSRF)' category: security technology: - express references: - https://www.npmjs.com/package/wkhtmltopdf cwe2022-top25: true cwe2021-top25 (ERROR). Found at src/express-wkhtml-injection.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'express-wkhtmltoimage-injection': If unverified user data can reach the `phantom` methods it",
        failureDescription: "Imported from semgrep rule 'express-wkhtmltoimage-injection': If unverified user data can reach the `phantom` methods it can result in Server-Side Request Forgery vulnerabilities metadata: owasp: - A1",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/express-wkhtml-injection.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
