/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-sequelize-weak-tls-version",
  bugClass: "novel",
  files: {
    ["src/sequelize-weak-tls-version.js"]: "module.exports = {\n  local: {\n    username: \"AppUser\",\n    database: \"AppDb\",\n    dialect: \"postgres\",\n    host: \"127.0.0.1\",\n    dialectOptions: {\n    // ruleid: sequelize-weak-tls-version\n      ssl: {\n        minVersion: 'TLSv1'\n      }\n    }\n  }\n};\n\nmodule.exports = {\n  local: {\n    username: \"AppUser\",\n    database: \"AppDb\",\n    dialect: \"postgres\",\n    host: \"127.0.0.1\",\n    dialectOptions: {\n    // ruleid: sequelize-weak-tls-version\n      ssl: {\n        minVersion: 'TLSv1.1'\n      }\n    }\n  }\n};\n\nmodule.exports = {\n  local: {\n    username: \"AppUser\",\n    database: \"AppDb\",\n    dialect: \"mysql\",\n    host: \"127.0.0.1\",\n    dialectOptions: {\n    // ruleid: sequelize-weak-tls-version\n      ssl: {\n        minVersion: 'TLSv1.1'\n      }\n    }\n  }\n};\n\nmodule.exports = {\n  local: {\n    username: \"AppUser\",\n    database: \"AppDb\",\n    dialect: \"mariadb\",\n    host: \"127.0.0.1\",\n    dialectOptions: {\n    // ruleid: sequelize-weak-tls-version\n      ssl: {\n        minVersion: 'TLSv1.1'\n      }\n    }\n  }\n};\n\n\nmodule.exports = {\n  local: {\n    username: \"AppUser\",\n    database: \"AppDb\",\n    dialect: \"postgres\",\n    host: \"127.0.0.1\",\n    dialectOptions: {\n    // ok: sequelize-weak-tls-version\n      ssl: {\n        minVersion: 'TLSv1.2'\n      }\n    }\n  }\n};\n",
  },
  bugReport: "Imported from semgrep rule 'sequelize-weak-tls-version': TLS1.0 and TLS1.1 are deprecated and should not be used anymore. By default, NodeJS used TLSv1.2. So, TLS min version must not be downgrade to TLS1.0 or TLS1.1. Enforce TLS1.3 is highly recommended This rule checks TLS configuration only for PostgreSQL, MariaDB and MySQL. SQLite is not really concerned by TLS configuration. This rule could be extended for MSSQL, but the dialectOptions is specific  (WARNING). Found at src/sequelize-weak-tls-version.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'sequelize-weak-tls-version': TLS1.0 and TLS1.1 are deprecated and should not be used anymore",
        failureDescription: "Imported from semgrep rule 'sequelize-weak-tls-version': TLS1.0 and TLS1.1 are deprecated and should not be used anymore. By default, NodeJS used TLSv1.2. So, TLS min version must not be downgrade to ",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/sequelize-weak-tls-version.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
