/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-vm2-context-injection",
  bugClass: "novel",
  files: {
    ["src/vm2-context-injection.js"]: "'use strict';\n\nconst fs = require('fs');\nconst {VM, NodeVM} = require('vm2');\n\n// ruleid:vm2-context-injection\nasync function test1(input) {\n  code = `\n    console.log(\"Hello world\")\n  `;\n\n  const sandbox = {\n    setTimeout,\n    watch: input\n  };\n\n  return new VM({timeout: 40 * 1000, sandbox}).run(code);\n}\n\n// ruleid:vm2-context-injection\nfunction test2(input) {\n  const sandbox = {\n    setTimeout,\n    input\n  };\n\n  const nodeVM = new NodeVM({timeout: 40 * 1000, sandbox});\n  return nodeVM.run('console.log(\"Hello world\")')\n}\n\n// ok:vm2-context-injection\nasync function okTest1() {\n  code = `\n    console.log(\"Hello world\")\n  `;\n\n  const sandbox = {\n    setTimeout,\n    fs\n  };\n\n  return new VM({timeout: 40 * 1000, sandbox}).run(code);\n}\n\n// ok:vm2-context-injection\nfunction okTest2() {\n  const sandbox = {\n    setTimeout,\n    fs\n  };\n\n  const nodeVM = new NodeVM({timeout: 40 * 1000, sandbox});\n  return nodeVM.run('console.log(\"Hello world\")')\n}\n",
  },
  bugReport: "Imported from semgrep rule 'vm2-context-injection': Make sure that unverified user data can not reach `vm2`. metadata: owasp: - A03:2021 - Injection - A05:2025 - Injection cwe: - \"CWE-94: Improper Control of Generation of Code ('Code Injection')\" category: security technology: - vm2 cwe2022-top25: true subcategory: - audit likelihood: LOW impact: HIGH confidence: LOW references: - https://owasp.org/Top10/A03_2021-Injection languages: - javascript - (WARNING). Found at src/vm2-context-injection.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'vm2-context-injection': Make sure that unverified user data can not reach `vm2`. metadata: o",
        failureDescription: "Imported from semgrep rule 'vm2-context-injection': Make sure that unverified user data can not reach `vm2`. metadata: owasp: - A03:2021 - Injection - A05:2025 - Injection cwe: - \"CWE-94: Improper Con",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/vm2-context-injection.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
