/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-sandbox-code-injection",
  bugClass: "novel",
  files: {
    ["src/sandbox-code-injection.js"]: "const Sandbox = require('sandbox');\n\nfunction test1(userInput, cb) {\n    const s = new Sandbox();\n    // ruleid: sandbox-code-injection\n    s.run('lol('+userInput+')', cb);\n}\n\nfunction test2(userInput, cb) {\n    const s = new Sandbox();\n    var code = 'lol('+userInput+')'\n    // ruleid: sandbox-code-injection\n    s.run(code, cb);\n}\n\nfunction test3(userInput, cb) {\n    const s = new Sandbox();\n    // ruleid: sandbox-code-injection\n    s.run(`lol(${userInput})`, cb);\n}\n\nfunction okTest1(cb) {\n    const s = new Sandbox();\n    // ok: sandbox-code-injection\n    s.run('lol(\"hi\")', cb);\n}\n\nfunction okTest2(cb) {\n    const s = new Sandbox();\n    var code = 'lol(\"hi\")'\n    // ok: sandbox-code-injection\n    s.run(code, cb);\n}\n\nfunction okTest3(cb) {\n    const s = new Sandbox();\n    // ok: sandbox-code-injection\n    s.run(`lol(\"hi\")`, cb);\n}\n",
  },
  bugReport: "Imported from semgrep rule 'sandbox-code-injection': Make sure that unverified user data can not reach `sandbox`. metadata: owasp: - A03:2021 - Injection - A05:2025 - Injection cwe: - \"CWE-94: Improper Control of Generation of Code ('Code Injection')\" category: security technology: - sandbox cwe2022-top25: true subcategory: - audit likelihood: LOW impact: LOW confidence: LOW references: - https://owasp.org/Top10/A03_2021-Injection languages: - javas (WARNING). Found at src/sandbox-code-injection.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'sandbox-code-injection': Make sure that unverified user data can not reach `sandbox`. metada",
        failureDescription: "Imported from semgrep rule 'sandbox-code-injection': Make sure that unverified user data can not reach `sandbox`. metadata: owasp: - A03:2021 - Injection - A05:2025 - Injection cwe: - \"CWE-94: Imprope",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/sandbox-code-injection.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
