/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-react-href-var",
  bugClass: "novel",
  files: {
    ["src/react-href-var.tsx"]: "import {\n  SEMGREP_REPO,\n} from \"../../util\";\n\nimport SEMGREP_REPO1 from \"../../util1\";\n\n// ok: react-href-var\nlet zzz = <Foo className={\"foobar\"} href={getQuery()} />;\n\nfunction test1(input) {\n// ruleid: react-href-var\n  const params = {href: input.a};\n  return React.createElement(\"a\", params);\n}\n\n// ok: react-href-var\nlet zzz = <Foo className={\"foobar\"} href={`${input}`} />;\n\n// ok: react-href-var\nlet zzz = <Foo className={\"foobar\"} href={SEMGREP_REPO} />;\n\n// ok: react-href-var\nlet zzz = <Foo className={\"foobar\"} href={SEMGREP_REPO1} />;\n\nfunction test1_ok(input) {\n// ok: react-href-var\n  if(input.startsWith(\"https:\")) {\n    const params = {href: input};\n    return React.createElement(\"a\", params);\n  }\n}\n\nfunction test2(input) {\n  // ok: react-href-var\n  const params = {href: \"#\"+input};\n  return React.createElement(\"a\", params);\n}\n\nfunction test2_ok(input) {\n  // ok: react-href-var\n  const params = {href: \"#\"+input};\n  return React.createElement(\"a\", params);\n}\n\n\n// ok: react-href-var\nconst b = <a className={\"foobar\"} href={\"http://www.example.com\"}></a>;\n\n// ok: react-href-var\nlet x = <a className={\"foobar\"} href={\"#\"+input}></a>;\n\n// ok: react-href-var\nlet x = <a className={\"foobar\"} href={`#${input}`}></a>;\n\nfunction okTest1() {\n// ok: react-href-var\n  return React.createElement(\"a\", {href: \"https://www.example.com\"});\n}",
  },
  bugReport: "Imported from semgrep rule 'react-href-var': Detected a variable used in an anchor tag with the 'href' attribute. A malicious actor may be able to input the 'javascript:' URI, which could cause cross-site scripting (XSS). It is recommended to disallow 'javascript:' URIs within your application. metadata: cwe: - \"CWE-79: Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')\" owasp: - A07:2017 - Cross-Site Script (WARNING). Found at src/react-href-var.tsx line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'react-href-var': Detected a variable used in an anchor tag with the 'href' attribute. A mali",
        failureDescription: "Imported from semgrep rule 'react-href-var': Detected a variable used in an anchor tag with the 'href' attribute. A malicious actor may be able to input the 'javascript:' URI, which could cause cross-",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/react-href-var.tsx", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
