/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-sequelize-sqli",
  bugClass: "novel",
  files: {
    ["src/sequelize-sqli.js"]: "let response;\n\nconst prettyPrint = (ob) => JSON.stringify(ob, null, 2).replace('\\'','');\nconst timestamp = () => new Date();\n\nconst toBase64 = (msg) => Buffer.from(msg).toString('base64');\n\nconst { Sequelize } = require('sequelize');\nexports.handler = async function (event, context) {\n  console.log(event);\n  const sequelize = new Sequelize('postgres://user:pass@example.com:5432/dbname')\n\n  records = [];\n  event.Records.forEach((record) => {\n    const { body } = record;\n    records.push(toBase64(body));\n  });\n\n  const query = `INSERT INTO public.messages (body, encoded_message) VALUES ('${JSON.stringify(event)}', '${records[0]}');`;\n  console.log(query);\n\n  try {\n    // ruleid: sequelize-sqli\n    await sequelize.query(query)\n\n    // ok: sequelize-sqli\n    await sequelize.query(\n      'SELECT * FROM projects WHERE status = :status',\n      {\n        replacements: { status: 'active' },\n        type: QueryTypes.SELECT\n      }\n    );\n  } catch (error) {\n    console.log(error);\n  }\n\n  return { key: JSON.stringify(records) };\n};",
  },
  bugReport: "Imported from semgrep rule 'sequelize-sqli': Detected SQL statement that is tainted by `$EVENT` object. This could lead to SQL injection if the variable is user-controlled and not properly sanitized. In order to prevent SQL injection, use parameterized queries or prepared statements instead. You can use parameterized statements like so: `sequelize.query('SELECT * FROM projects WHERE status = ?', { replacements: ['active'], type: QueryTypes.S (WARNING). Found at src/sequelize-sqli.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'sequelize-sqli': Detected SQL statement that is tainted by `$EVENT` object. This could lead ",
        failureDescription: "Imported from semgrep rule 'sequelize-sqli': Detected SQL statement that is tainted by `$EVENT` object. This could lead to SQL injection if the variable is user-controlled and not properly sanitized. ",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/sequelize-sqli.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
