/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-express-jwt-not-revoked",
  bugClass: "novel",
  files: {
    ["src/express-jwt-not-revoked.js"]: "var jwt = require('express-jwt');\nvar blacklist = require('express-jwt-blacklist');\n\n// ruleid: express-jwt-not-revoked\napp.get('/ok-protected', jwt({ secret: process.env.SECRET }), function(req, res) {\n    if (!req.user.admin) return res.sendStatus(401);\n    res.sendStatus(200);\n});\n\nlet configSecret = config.get('secret')\nconst opts = Object.assign({issuer: 'http://issuer'}, {secret: configSecret})\n// ruleid: express-jwt-not-revoked\napp.get('/ok-protected', jwt(opts), function(req, res) {\n    if (!req.user.admin) return res.sendStatus(401);\n    res.sendStatus(200);\n});\n\n// ok: express-jwt-not-revoked\napp.get('/ok-protected', jwt({ secret: process.env.SECRET, isRevoked: blacklist.isRevoked }), function(req, res) {\n    if (!req.user.admin) return res.sendStatus(401);\n    res.sendStatus(200);\n});\n\n// ok: express-jwt-not-revoked\nlet configSecret = config.get('secret')\nconst opts = Object.assign({issuer: 'http://issuer'}, {isRevoked: blacklist.isRevoked})\n\napp.get('/ok-protected', jwt(opts), function(req, res) {\n    if (!req.user.admin) return res.sendStatus(401);\n    res.sendStatus(200);\n});\n",
  },
  bugReport: "Imported from semgrep rule 'express-jwt-not-revoked': No token revoking configured for `express-jwt`. A leaked token could still be used and unable to be revoked. Consider using function as the `isRevoked` option. metadata: cwe: - 'CWE-522: Insufficiently Protected Credentials' owasp: - A02:2017 - Broken Authentication - A04:2021 - Insecure Design - A06:2025 - Insecure Design source-rule-url: https://github.com/goldbergyoni/nodebestpractices/blob/mas (WARNING). Found at src/express-jwt-not-revoked.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'express-jwt-not-revoked': No token revoking configured for `express-jwt`. A leaked token cou",
        failureDescription: "Imported from semgrep rule 'express-jwt-not-revoked': No token revoking configured for `express-jwt`. A leaked token could still be used and unable to be revoked. Consider using function as the `isRev",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/express-jwt-not-revoked.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
