/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-puppeteer-evaluate-code-injection",
  bugClass: "novel",
  files: {
    ["src/puppeteer-evaluate-code-injection.js"]: "const puppeteer = require('puppeteer');\n\nasync function test2(userInput) {\n\n  const browser = await puppeteer.launch();\n  const page = await browser.newPage();\n\n  // ok:puppeteer-evaluate-code-injection\n  await page.evaluate(x => console.log(x), 5);\n\n  // ruleid:puppeteer-evaluate-code-injection\n  await page.evaluate(`fetch(${userInput})`);\n\n  await page.screenshot({path: 'example.png'});\n  await browser.close();\n}\n",
  },
  bugReport: "Imported from semgrep rule 'puppeteer-evaluate-code-injection': If unverified user data can reach the `evaluate` method it can result in Server-Side Request Forgery vulnerabilities metadata: owasp: - A10:2021 - Server-Side Request Forgery (SSRF) - A01:2025 - Broken Access Control cwe: - 'CWE-918: Server-Side Request Forgery (SSRF)' category: security technology: - puppeteer cwe2022-top25: true cwe2021-top25: true subcategory: - audit likelihood: LOW impact: LO (WARNING). Found at src/puppeteer-evaluate-code-injection.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'puppeteer-evaluate-code-injection': If unverified user data can reach the `evaluate` method ",
        failureDescription: "Imported from semgrep rule 'puppeteer-evaluate-code-injection': If unverified user data can reach the `evaluate` method it can result in Server-Side Request Forgery vulnerabilities metadata: owasp: - ",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/puppeteer-evaluate-code-injection.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
