/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-mysql-sqli",
  bugClass: "novel",
  files: {
    ["src/mysql-sqli.js"]: "var AWS = require('aws-sdk');\nconst mysql = require('mysql2');\n\nexports.handler = async (event, context) => {\n  console.log(event);\n  var secretsManager = new AWS.SecretsManager();\n  var secretId = event.arguments[0][2];\n  const secret = await secretsManager.getSecretValue({\n      SecretId: secretId\n      }).promise();\n\n  var secretJson = JSON.parse(secret.SecretString);\n\n  var host = secretJson.host;\n  var user = secretJson.username;\n  var password = secretJson.password;\n\n  let connectionConfig = {\n    host: host,\n    user: user,\n    password: password,\n    connectTimeout: 60000\n  };\n\n  var pool = await mysql.createPool(connectionConfig);\n  var conn = pool.promise();\n\n  var table = event.arguments[0][0];\n  var columnName = event.arguments[0][1];\n\n  var createStmt = 'create temporary table ' + table + '_jointemp (temp_seq int, '+ columnName + ' varchar(100)); ';\n  // ruleid: mysql-sqli\n  await conn.query(createStmt);\n\n\n  var values = event.arguments.map((x, i) => \"(\"+i+\",'\"+x[3]+\"')\");\n  var insertStmt = 'insert into ' + table + '_jointemp(temp_seq, '+ columnName +') values ' + values.join(',') + ';';\n  // ruleid: mysql-sqli\n  await conn.query({sql: insertStmt, rowsAsArray: true});\n\n  var selectStmt = 'select t2.* FROM ' + table + '_jointemp t1 LEFT OUTER JOIN ' + table + ' t2 using ('+ columnName +') order by temp_seq;'\n  // ruleid: mysql-sqli\n  const [results, fields] = await conn.execute(selectStmt);\n\n  // ok: mysql-sqli\n  const [results2, fields2] = await conn.execute('SELECT * FROM foobar WHERE id = ?', [columnName]);\n\n  var res = {};\n  if(results.length > 0){\n    res = results.map((row) => JSON.stringify(row));\n    }\n    var response = JSON.stringify({\"results\": res});\n    conn.end();\n  return response;\n};",
  },
  bugReport: "Imported from semgrep rule 'mysql-sqli': Detected SQL statement that is tainted by `$EVENT` object. This could lead to SQL injection if the variable is user-controlled and not properly sanitized. In order to prevent SQL injection, use parameterized queries or prepared statements instead. You can use parameterized statements like so: `connection.query('SELECT $1 from table', [userinput])` metadata: references: - https://www.npmjs.com/pack (WARNING). Found at src/mysql-sqli.js line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'mysql-sqli': Detected SQL statement that is tainted by `$EVENT` object. This could lead to S",
        failureDescription: "Imported from semgrep rule 'mysql-sqli': Detected SQL statement that is tainted by `$EVENT` object. This could lead to SQL injection if the variable is user-controlled and not properly sanitized. In o",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/mysql-sqli.js", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
