/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-express-session-hardcoded-secret",
  bugClass: "novel",
  files: {
    ["src/express-session-hardcoded-secret.ts"]: "import express from 'express'\nimport session from 'express-session'\nconst app = express()\nconst port = 3000\n\nlet a = 'a'\nlet config = {\n  // ruleid: express-session-hardcoded-secret\n  secret: 'a',\n  resave: false,\n  saveUninitialized: false,\n}\n\nlet config1 = {\n  // ok: express-session-hardcoded-secret\n  secret: config.secret,\n  resave: false,\n  saveUninitialized: false,\n}\n\n\napp.use(session({\n  // ruleid: express-session-hardcoded-secret\n  secret: a,\n  resave: false,\n  saveUninitialized: false,\n}));\n\napp.use(session(config));\n\napp.use(session(config1));\n\nlet secret2 = {\n  resave: false,\n  // ruleid: express-session-hardcoded-secret\n  secret: 'foo',\n  saveUninitialized: false,\n}\napp.use(session(secret2));\n\n\napp.use(session({\n  // ok: express-session-hardcoded-secret\n  secret: config.secret,\n  resave: false,\n  saveUninitialized: false,\n}));",
  },
  bugReport: "Imported from semgrep rule 'express-session-hardcoded-secret': A hard-coded credential was detected. It is not recommended to store credentials in source-code, as this risks secrets being leaked and used by either an internal or external malicious adversary. It is recommended to use environment variables to securely provide credentials or retrieve credentials from a secure vault or HSM (Hardware Security Module). options: interfile: true metadata: interfile:  (WARNING). Found at src/express-session-hardcoded-secret.ts line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'express-session-hardcoded-secret': A hard-coded credential was detected. It is not recommend",
        failureDescription: "Imported from semgrep rule 'express-session-hardcoded-secret': A hard-coded credential was detected. It is not recommended to store credentials in source-code, as this risks secrets being leaked and u",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/express-session-hardcoded-secret.ts", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
