/**
 * IMPORTED FROM semgrep-rules.
 * Auto-generated by src/fix/corpus/import-semgrep.ts.
 * Do not edit by hand: re-run the importer.
 */
import type { CorpusScenario } from "../../scenarios.js";

export const scenario: CorpusScenario = {
  id: "imported-awscdk-bucket-grantpublicaccessmethod",
  bugClass: "novel",
  files: {
    ["src/awscdk-bucket-grantpublicaccessmethod.ts"]: "import * as cdk from '@aws-cdk/core';\nimport * as s3 from '@aws-cdk/aws-s3';\nimport * as rename_s3  from '@aws-cdk/aws-s3';\nimport {Bucket} from '@aws-cdk/aws-s3';\n\nexport class CdkStarterStack extends cdk.Stack {\n  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {\n    super(scope, id, props);\n\n    // ruleid:awscdk-bucket-grantpublicaccessmethod\n    const publicBucket1 = new s3.Bucket(this, 'bucket')\n    console.log('something unrelated')\n    publicBucket1.grantPublicAccess()\n\n    // ruleid:awscdk-bucket-grantpublicaccessmethod\n    const publicBucket2 = new s3.Bucket(this, 'bucket')\n    publicBucket2.grantPublicAccess()\n\n    // ok:awscdk-bucket-grantpublicaccessmethod\n    const nonPublicBucketRenamed = new rename_s3.Bucket(this, 'bucket')\n\n    // ruleid:awscdk-bucket-grantpublicaccessmethod\n    const publicBucket1Rename = new rename_s3.Bucket(this, 'bucket')\n    console.log('something unrelated')\n    publicBucket1Rename.grantPublicAccess()\n\n    // ruleid:awscdk-bucket-grantpublicaccessmethod\n    const publicBucket2Rename = new rename_s3.Bucket(this, 'bucket')\n    publicBucket2Rename.grantPublicAccess()\n\n    // ok:awscdk-bucket-grantpublicaccessmethod\n    const nonPublicBucketRename = new rename_s3.Bucket(this, 'bucket')\n\n    // ruleid:awscdk-bucket-grantpublicaccessmethod\n    const publicBucket1Direct = new Bucket(this, 'bucket')\n    console.log('something unrelated')\n    publicBucket1Direct.grantPublicAccess()\n\n    // ruleid:awscdk-bucket-grantpublicaccessmethod\n    const publicBucket2Direct = new Bucket(this, 'bucket')\n    publicBucket2Direct.grantPublicAccess()\n\n    // ok:awscdk-bucket-grantpublicaccessmethod\n    const nonPublicBucketDirect = new Bucket(this, 'bucket')\n  }\n}\n",
  },
  bugReport: "Imported from semgrep rule 'awscdk-bucket-grantpublicaccessmethod': Using the GrantPublicAccess method on bucket contruct $X will make the objects in the bucket (WARNING). Found at src/awscdk-bucket-grantpublicaccessmethod.ts line 1.",
  expected: {
    completes: ["intake"],
    outcome: "out_of_scope",
  },
  llmResponses: [
    {
      matchPrompt: "bug-report parser",
      response: JSON.stringify({
        summary: "Imported from semgrep rule 'awscdk-bucket-grantpublicaccessmethod': Using the GrantPublicAccess method on bucket contruc",
        failureDescription: "Imported from semgrep rule 'awscdk-bucket-grantpublicaccessmethod': Using the GrantPublicAccess method on bucket contruct $X will make the objects in the bucket (WARNING). Found at src/awscdk-bucket-g",
        fixHint: "imported semgrep rule — out of scope for current principle library",
        codeReferences: [{ file: "src/awscdk-bucket-grantpublicaccessmethod.ts", line: 1 }],
        bugClassHint: "novel",
      }),
    },
    {
      matchPrompt: "classifying a bug report",
      response: JSON.stringify({
        primaryLayer: "out_of_scope",
        secondaryLayers: [],
        artifacts: [],
        rationale: "Imported semgrep rule with no matching principle.",
      }),
    },
  ],
};
