// SPDX-License-Identifier: Apache-2.0
//
// Draft operation table for the hand-mapped core subset. The full
// operation set is mint-more-realizations, not new machinery: each
// added operation gets a table entry, lowering rule, and receipt.

pub const CORE_OPERATION_SUBSET: &[&str] = &[
    "seq",
    "if",
    "while",
    "return",
    "call",
    "break",
    "continue",
    "skip",
    "eq",
    "lt",
    "le",
    "add",
    "sub",
    "mul",
    "neg",
    "and",
    "or",
    "not",
    "deref",
    "assign",
    "source-unit",
    "cast",
    "bop_eq",
    "bop_ne",
    "bop_lt",
    "bop_le",
    "bop_gt",
    "bop_ge",
    "bop_add",
    "bop_sub",
    "bop_mul",
    "bop_div",
    "bop_mod",
    "bop_shl",
    "bop_shr",
    "bop_bitand",
    "bop_bitor",
    "bop_bitxor",
    "bop_logand",
    "bop_logor",
    "bop_comma",
    "uop_neg",
    "uop_lognot",
    "uop_deref",
    "uop_bitnot",
    "uop_plus",
];

pub const ALGEBRA_TO_JVM_TABLE: &[(&str, &str)] = &[
    ("seq(a,b,...)", "emit each statement in order"),
    (
        "if(c,t,e) statement",
        "emit c; ifeq L_else; emit t; goto L_end when t falls through; L_else: emit e; L_end:",
    ),
    (
        "if(c,t,e) expression",
        "emit c; ifeq L_else; emit t; goto L_end; L_else: emit e; L_end:",
    ),
    (
        "while(c,b)",
        "L_top: emit c; ifeq L_done; emit b; goto L_top; L_done:",
    ),
    ("return(e)", "emit e; ireturn"),
    (
        "call(f,args...)",
        "emit args left to right; invokestatic Class/f(II...)I",
    ),
    ("break", "goto the active loop done label"),
    ("continue", "goto the active loop top label"),
    ("skip", "emit no instructions"),
    ("var x", "iload slot(x)"),
    ("const n", "iconst, bipush, sipush, or ldc"),
    (
        "eq(a,b)",
        "emit a; emit b; if_icmpeq L_true; iconst_0; goto L_end; L_true: iconst_1; L_end:",
    ),
    ("lt(a,b)", "same shape with if_icmplt"),
    ("le(a,b)", "same shape with if_icmple"),
    ("bop_eq(a,b)", "same shape with if_icmpeq"),
    ("bop_ne(a,b)", "same shape with if_icmpne"),
    ("bop_lt(a,b)", "same shape with if_icmplt"),
    ("bop_le(a,b)", "same shape with if_icmple"),
    ("bop_gt(a,b)", "same shape with if_icmpgt"),
    ("bop_ge(a,b)", "same shape with if_icmpge"),
    ("add(a,b)", "emit a; emit b; iadd"),
    ("sub(a,b)", "emit a; emit b; isub"),
    ("mul(a,b)", "emit a; emit b; imul"),
    ("bop_add(a,b)", "emit a; emit b; iadd"),
    ("bop_sub(a,b)", "emit a; emit b; isub"),
    ("bop_mul(a,b)", "emit a; emit b; imul"),
    ("bop_div(a,b)", "emit a; emit b; idiv"),
    ("bop_mod(a,b)", "emit a; emit b; irem"),
    ("bop_shl(a,b)", "emit a; emit b; ishl"),
    ("bop_shr(a,b)", "emit a; emit b; ishr"),
    ("bop_bitand(a,b)", "emit a; emit b; iand"),
    ("bop_bitor(a,b)", "emit a; emit b; ior"),
    ("bop_bitxor(a,b)", "emit a; emit b; ixor"),
    ("neg(a)", "emit a; ineg"),
    ("uop_neg(a)", "emit a; ineg"),
    ("and(a,b)", "short-circuit to 0 or 1 with ifeq"),
    ("or(a,b)", "short-circuit to 0 or 1 with ifne"),
    ("bop_logand(a,b)", "short-circuit to 0 or 1 with ifeq"),
    ("bop_logor(a,b)", "short-circuit to 0 or 1 with ifne"),
    ("bop_comma(a,b)", "emit a; pop; emit b"),
    (
        "not(a)",
        "emit a; ifeq L_true; iconst_0; goto L_end; L_true: iconst_1; L_end:",
    ),
    ("uop_lognot(a)", "same shape as not(a)"),
    ("uop_bitnot(a)", "emit a; iconst_m1; ixor"),
    ("uop_plus(a)", "emit a"),
    (
        "deref(p)",
        "getstatic Class/memory [I; emit p; iaload in the minimal int-memory model",
    ),
    ("uop_deref(p)", "same shape as deref(p)"),
    (
        "source-unit(bytes, term)",
        "project to term before lowering",
    ),
    (
        "cast(target_type,value)",
        "target_type is type metadata; lower value in the i32 subset",
    ),
    ("assign(x,v)", "emit v; istore slot(x) for local variables"),
    (
        "assign(p,v)",
        "getstatic Class/memory [I; emit p; emit v; iastore otherwise",
    ),
];
