/* SPDX-License-Identifier: Apache-2.0 */
/* DO NOT EDIT — generated by tools/generate-c11-from-cursorkind.py */
#ifndef PROVEKIT_C11_CURSOR_DISPATCH_GENERATED_H
#define PROVEKIT_C11_CURSOR_DISPATCH_GENERATED_H

#include <stddef.h>

#ifdef PK_C_ENABLE_CLANG_AST
#include <clang-c/Index.h>

typedef struct {
    enum CXCursorKind cursor_kind;
    const char *cursor_kind_name;
    const char *op_name;
    const char *op_cid;
    int arity;
    const char *arity_shape_json;
    const char *child_shape;
    const char *classification;
    const char *notes;
} pk_c11_cursor_dispatch;

typedef struct {
    const char *op_name;
    const char *op_cid;
    int serialize_supported;
} pk_c11_op_dispatch;

const pk_c11_cursor_dispatch *pk_c11_cursor_dispatch_lookup(enum CXCursorKind kind);
const pk_c11_op_dispatch *pk_c11_op_dispatch_lookup(const char *op_name);
const char *pk_c11_signature_cid(void);

#endif

#endif
