#!/bin/sh
set -eu
BASE="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
PYTHONDONTWRITEBYTECODE=1 python3 -m unittest "$BASE/scripts/test_discharge.py"
PYTHONDONTWRITEBYTECODE=1 python3 -m unittest "$BASE/scripts/test_mint_language_morphisms.py"
PYTHONDONTWRITEBYTECODE=1 python3 "$BASE/scripts/discharge.py"
PYTHONDONTWRITEBYTECODE=1 python3 "$BASE/scripts/primitive_ops.py"
PYTHONDONTWRITEBYTECODE=1 python3 "$BASE/scripts/mint_language_morphisms.py"
PYTHONDONTWRITEBYTECODE=1 python3 "$BASE/scripts/mint_option.py"
PYTHONDONTWRITEBYTECODE=1 python3 "$BASE/scripts/mint_pair.py"
PYTHONDONTWRITEBYTECODE=1 python3 "$BASE/scripts/mint_result.py"
PYTHONDONTWRITEBYTECODE=1 python3 "$BASE/scripts/mint_tagged_union.py"
PYTHONDONTWRITEBYTECODE=1 python3 "$BASE/scripts/mint_list.py"
PYTHONDONTWRITEBYTECODE=1 python3 "$BASE/scripts/mint_identity.py"
PYTHONDONTWRITEBYTECODE=1 python3 "$BASE/scripts/mint_bool_cell.py"
PYTHONDONTWRITEBYTECODE=1 python3 "$BASE/scripts/mint_unit.py"
PYTHONDONTWRITEBYTECODE=1 python3 "$BASE/scripts/mint_assert.py"
PYTHONDONTWRITEBYTECODE=1 python3 "$BASE/scripts/mint_result_python.py"
PYTHONDONTWRITEBYTECODE=1 python3 "$BASE/scripts/mint_result_java.py"
PYTHONDONTWRITEBYTECODE=1 python3 "$BASE/scripts/mint_option_bind.py"
PYTHONDONTWRITEBYTECODE=1 python3 "$BASE/scripts/mint_result_bind.py"
PYTHONDONTWRITEBYTECODE=1 python3 "$BASE/scripts/mint_trinity.py"
PYTHONDONTWRITEBYTECODE=1 python3 "$BASE/scripts/mint_tagged_union_java.py"
PYTHONDONTWRITEBYTECODE=1 python3 "$BASE/scripts/mint_tagged_union_python.py"
PYTHONDONTWRITEBYTECODE=1 python3 "$BASE/scripts/mint_identity_python.py"
PYTHONDONTWRITEBYTECODE=1 python3 "$BASE/scripts/mint_list_python.py"
PYTHONDONTWRITEBYTECODE=1 python3 "$BASE/scripts/mint_identity_java.py"
PYTHONDONTWRITEBYTECODE=1 python3 "$BASE/scripts/mint_list_java.py"
PYTHONDONTWRITEBYTECODE=1 python3 "$BASE/scripts/mint_assert_python.py"
PYTHONDONTWRITEBYTECODE=1 python3 "$BASE/scripts/mint_assert_java.py"
PYTHONDONTWRITEBYTECODE=1 python3 "$BASE/scripts/mint_unit_python.py"
