#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0

source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/common.sh"

section "Bridgeworks Walkthrough"
say "This is a CLI-first tour of the entire Bridgeworks stack."
say "The stack is not software proving software. It is a chain of contracts across native domains."

section "What This Directory Contains"
say "CSV measurements -> physics paper -> SPICE cells -> BLIF gates -> Verilog RTL -> ISA spec -> compiler trace -> C source."
say "Each layer has a native artifact, a contract, and a bridge edge to the next layer."

explain_then_pause "check tools and prepare local binaries" <<'TEXT'
What ProvekIt is doing here:
This first script is not proving the stack yet. It is establishing the execution surface for the rest of the exhibit. Every later step needs to run through the same tools a user would run: provekit lift, provekit lower, provekit mint, provekit dump, and the Bridgeworks runner. The script checks the local toolchain and prepares the local binaries that implement those surfaces.

Value ProvekIt adds:
The important value here is reproducibility and composition. The walkthrough should not hide behind cargo invocations or checked-in generated artifacts. Once the binaries are prepared, the numbered scripts can show ProvekIt doing the work directly: lifting native artifacts, lowering witness obligations, minting .proof files, and dumping the resulting CID DAG.

Relationship to the chain:
Bridgeworks is about a contract chain, not a demo fixture. The chain starts in measured material behavior, crosses papers, cell models, logic equations, RTL, ISA semantics, compiler lowering, and only then arrives at C software. ProvekIt is the thing that carries that chain across native domains through ProofIR and then compresses the implication DAG into .proof artifacts.

What to look for:
After the prompt, the script should report the toolchain, prepare any stale binaries, and state that lift and mint resolve the Bridgeworks surface from .provekit/config.toml. Later scripts should not repeatedly show binary preparation unless a relevant source file actually changed.
TEXT

section "Tool Check"
need_cmd cargo
need_cmd cc
need_cmd make
need_jq
say "cargo, cc, make, and jq are available."
say "Repo root: $REPO_ROOT"
say "Exhibit:   $EXHIBIT_ROOT"

section "Binary Prep"
say "The walkthrough builds local binaries once, then invokes the protocol tools by name."
ensure_walkthrough_bins
say "provekit, provekit-bridgeworks, and Bridgeworks kit binaries are on the walkthrough PATH."
say "Lift and mint resolve the Bridgeworks surface from .provekit/config.toml."

section "Rule"
say "The scripts use temp directories for generated artifacts."
say "The lowered C witness is generated by the C lowerer at runtime; it is not checked in."

analysis_with_receipts <<'TEXT'
The receipts here are environmental rather than proof-theoretic. The tool check names the local commands the exhibit depends on. The binary prep section says the walkthrough will invoke provekit, provekit-bridgeworks, and the Bridgeworks kit binaries by name. That matters because the rest of the tour must make ProvekIt visible as the actor doing the lift, lower, mint, and dump work.

The final rule is also a receipt for the design of the exhibit: generated artifacts go into temp directories. If later steps show generated C witness code, that code should appear as runtime evidence in lower output or in witness proof metadata, not as a checked-in source file.
TEXT

next_script "01-map-stack.sh"
