/**
 * Corpus loader: enumerates and loads all registered scenarios.
 *
 * Hand-written scenarios live under src/fix/corpus/scenarios/<bug-class>/<id>.ts
 * and are imported explicitly so tsc can validate every scenario at build time.
 *
 * Imported scenarios live under src/fix/corpus/scenarios/imported/*.ts and are
 * loaded via runtime require() glob — they are auto-generated by
 * scripts/import-semgrep.ts and may be many. They are appended after the
 * curated set so any ID collision is impossible (curated names use prefixes
 * like dbz-, null-, ternary-, adv-, multi-; imported names use imported-).
 *
 * BugsJS-imported scenarios live one level deeper at imported/bugsjs/*.ts
 * (auto-generated by scripts/import-bugsjs.ts) and use the bugsjs- prefix.
 * They are loaded via the same runtime require() glob, recursed once.
 */

import { readdirSync, statSync } from "fs";
import { join } from "path";
import type { CorpusScenario } from "./scenarios.js";

import { scenario as dbz001 } from "./scenarios/division-by-zero/dbz-001.js";
import { scenario as dbz002 } from "./scenarios/division-by-zero/dbz-002.js";
import { scenario as dbz003 } from "./scenarios/division-by-zero/dbz-003.js";
import { scenario as null001 } from "./scenarios/null-assertion/null-001.js";
import { scenario as null002 } from "./scenarios/null-assertion/null-002.js";
import { scenario as ternary001 } from "./scenarios/ternary-branch-collapse/ternary-001.js";
import { scenario as ternary002 } from "./scenarios/ternary-branch-collapse/ternary-002.js";
import { scenario as advMissingFile } from "./scenarios/adversarial/adv-missing-file.js";
import { scenario as advOutOfScope } from "./scenarios/adversarial/adv-out-of-scope.js";
import { scenario as advUnsatInvariant } from "./scenarios/adversarial/adv-unsatisfiable-invariant.js";
import { scenario as advFixFailsOracle2 } from "./scenarios/adversarial/adv-fix-fails-oracle2.js";
import { scenario as multi001 } from "./scenarios/multi-file/multi-001.js";

/** Curated, hand-written scenarios in declaration order. */
const CURATED_SCENARIOS: CorpusScenario[] = [
  dbz001,
  dbz002,
  dbz003,
  null001,
  null002,
  ternary001,
  ternary002,
  advMissingFile,
  advOutOfScope,
  advUnsatInvariant,
  advFixFailsOracle2,
  multi001,
];

/**
 * Load auto-generated scenarios from scenarios/imported/*.ts at runtime.
 * Returns [] if the directory is missing or no imported files exist yet.
 *
 * Uses CommonJS require() — this file's containing project is "type":"commonjs"
 * so dynamic require is the simplest portable approach. We tolerate per-file
 * load failures so a single broken import doesn't kill the entire corpus.
 *
 * Loads from the top of imported/ AND from imported/bugsjs/ (one level deep).
 * Top-level imported entries that are directories are recursed into; any
 * other subdirectories beyond bugsjs/ are also walked so future importers
 * can land in their own namespaced subdir without further changes here.
 */
function loadImportedScenarios(): CorpusScenario[] {
  const importedDir = join(__dirname, "scenarios", "imported");
  const out: CorpusScenario[] = [];
  loadFromDir(importedDir, out);
  return out;
}

function loadFromDir(dir: string, out: CorpusScenario[]): void {
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return;
  }
  for (const name of entries) {
    const full = join(dir, name);
    let st;
    try {
      st = statSync(full);
    } catch {
      continue;
    }
    if (st.isDirectory()) {
      // Recurse one level into namespaced subdirs (e.g., bugsjs/).
      loadFromDir(full, out);
      continue;
    }
    if (!name.endsWith(".js") && !name.endsWith(".ts")) continue;
    if (name.endsWith(".d.ts")) continue;
    try {
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      const mod = require(full) as { scenario?: CorpusScenario };
      if (mod.scenario && typeof mod.scenario.id === "string") {
        out.push(mod.scenario);
      }
    } catch {
      // Single broken import shouldn't kill the corpus; skip it.
    }
  }
}

/** All registered corpus scenarios — curated set followed by any imported ones. */
export const ALL_SCENARIOS: CorpusScenario[] = [
  ...CURATED_SCENARIOS,
  ...loadImportedScenarios(),
];

/**
 * Load scenarios filtered by bug class.
 * Pass "all" (or omit) to get every scenario.
 */
export function loadScenarios(bugClass?: string): CorpusScenario[] {
  if (!bugClass || bugClass === "all") return ALL_SCENARIOS;
  return ALL_SCENARIOS.filter((s) => s.bugClass === bugClass);
}

/** Look up a single scenario by ID. */
export function getScenario(id: string): CorpusScenario | undefined {
  return ALL_SCENARIOS.find((s) => s.id === id);
}
