# Generated by bootstrap/phase5py/driver_v0.py.
# This module is the Phase-5-Py-v0 realize_python output snapshot.
from __future__ import annotations

def null():
    raise NotImplementedError("sugar-bind canonical: return(call:new(Arc::new, [Null]))")

def boolean(b):
    raise NotImplementedError("sugar-bind canonical: return(call:new(Arc::new, [call:Bool(Value::Bool, [b])]))")

def integer(n):
    raise NotImplementedError("sugar-bind canonical: return(call:new(Arc::new, [call:Integer(Value::Integer, [n])]))")

def string(s):
    raise NotImplementedError("sugar-bind canonical: return(call:new(Arc::new, [call:String(Value::String, [method:into(s, [])])]))")
