# Generated by bootstrap/phase5py/driver_v1.py.
# This module is the Phase-5-Py-v1 realize_python output snapshot.
from __future__ import annotations

def null():
    return Value.NULL

def boolean(b):
    return Value.boolean(b)

def integer(n):
    return Value.integer(n)

def string(s):
    return Value.string(s)
