// SPDX-License-Identifier: Apache-2.0
//
// Report renderer.
//
// Substrate-voice, ten sections. Concrete data next to every claim.
// No first-person; no em-dashes (Sir's rule).

use std::collections::BTreeMap;
use std::fmt::Write;
use std::path::Path;

use crate::{ConceptRecord, ContractOrigin, NameSource, PassResult, WitnessRecord};

pub fn render_report(
    fixture_root: &Path,
    pass_1: &PassResult,
    pass_2: &PassResult,
    renamed_pair: Option<&(String, String)>,
) -> String {
    let mut s = String::new();
    let _ = writeln!(s, "# Smoke Test: End-to-End Vision Demo");
    let _ = writeln!(s);
    let _ = writeln!(
        s,
        "The eight-verb pipeline (Lift, Cluster, Name, Scope, Cluster, Identify, Realize, Witness) walking around a 200-line Rust fixture. Every contract in the rewritten output traces to one of three substrate sources: a lifted annotation, a lifted test assertion, or a wp_rule applied to a recognized term-shape. None of the contracts shown below were authored by the smoke-test driver author."
    );
    let _ = writeln!(s);
    let _ = writeln!(s, "Fixture root: `{}`", fixture_root.display());
    let _ = writeln!(s);

    section_1_fixture(&mut s);
    section_2_lift(&mut s, pass_1);
    section_3_clustering(&mut s, pass_1);
    section_4_bindings(&mut s, pass_1);
    section_5_propagation(&mut s, pass_1);
    section_6_compression(&mut s, pass_1);
    section_7_round_trip(&mut s, fixture_root);
    section_8_zero_authoring(&mut s, pass_1);
    section_9_open_karlton(&mut s, pass_1);
    section_10_naming_roundtrip(&mut s, pass_1, pass_2, renamed_pair);

    // Trailing receipt.
    let _ = writeln!(s);
    let _ = writeln!(s, "---");
    let _ = writeln!(
        s,
        "Generated by `cargo run -p smoke-test-e2e-driver` against the fixture at `menagerie/smoke-test-e2e/`."
    );
    let _ = writeln!(
        s,
        "All hashes are BLAKE3-512 self-identifying strings. All `mint_contract` envelopes are signed with the shared dev seed `[0x42; 32]` per the kit default; they are reproducible across machines."
    );

    s
}

fn section_1_fixture(s: &mut String) {
    let _ = writeln!(s, "## 1. The fixture");
    let _ = writeln!(s);
    let _ = writeln!(
        s,
        "Three idioms are deliberately mixed so the smoke test can prove each substrate-source pathway separately:"
    );
    let _ = writeln!(s);
    let _ = writeln!(
        s,
        "- `src/option_handling.rs` carries `#[requires]` / `#[ensures]` annotations on every fn. These exercise the ANNOTATION-LIFT path."
    );
    let _ = writeln!(
        s,
        "- `src/validate_then_commit.rs` carries no contract annotations on either fn. A unit test in `tests/properties.rs` asserts a post-condition over `commit_balance_change` only. This exercises the TEST-LIFT path and (combined with the clustering result) the PROPAGATION path onto `commit_inventory_change`."
    );
    let _ = writeln!(
        s,
        "- `src/retry_with_backoff.rs` carries neither annotations nor test assertions. Both functions have a structural shape the term algebra recognizes as `retry-with-bounded-attempts`. This exercises the ALGEBRA-SYNTHESIS path AND the COMPRESSION event (two visibly different functions sharing one concept-CID)."
    );
    let _ = writeln!(s);
    let _ = writeln!(
        s,
        "The fixture itself is plain Rust 2021. Attributes are kept inert under `rustc` via `#[cfg_attr(any(), requires(...))]` so `cargo build` and `cargo test` succeed unchanged while `syn::parse_file` still observes the attribute literals."
    );
    let _ = writeln!(s);
}

fn section_2_lift(s: &mut String, pass: &PassResult) {
    let _ = writeln!(s, "## 2. The lift");
    let _ = writeln!(s);
    let _ = writeln!(
        s,
        "Pass 1 lifted {} sites across {} files. For each site, the driver constructed a canonical term shape, minted a `contract` memento (via `provekit-claim-envelope::mint_contract`) when a contract was recoverable, and assigned a stable BLAKE3-512 shape-CID for clustering.",
        pass.bindings.len(),
        count_unique_files(pass)
    );
    let _ = writeln!(s);
    let _ = writeln!(s, "| Site | Shape-CID (prefix) | Mint Envelope CID (prefix) | Contract content-CID (prefix) |");
    let _ = writeln!(s, "|---|---|---|---|");
    for b in &pass.bindings {
        let _ = writeln!(
            s,
            "| `{}::{}` | `{}` | `{}` | `{}` |",
            b.site_file,
            b.site_fn,
            short_cid(&b.shape_cid),
            b.contract_cid
                .as_deref()
                .map(short_cid)
                .unwrap_or_else(|| "(empty)".into()),
            b.contract_content_cid
                .as_deref()
                .map(short_cid)
                .unwrap_or_else(|| "(empty)".into()),
        );
    }
    let _ = writeln!(s);
}

fn section_3_clustering(s: &mut String, pass: &PassResult) {
    let _ = writeln!(s, "## 3. The clustering");
    let _ = writeln!(s);
    let _ = writeln!(
        s,
        "Shape-CIDs were grouped via exact equality (the algebra's address). Each cluster received a name via the priority order: human annotation (pass 2 only) -> seed catalog -> `UNNAMED-CONCEPT-N`."
    );
    let _ = writeln!(s);
    let _ = writeln!(
        s,
        "| Concept | Shape-CID (prefix) | Source of Name | # sites | Catalog id |"
    );
    let _ = writeln!(s, "|---|---|---|---|---|");
    for c in &pass.concepts {
        let _ = writeln!(
            s,
            "| `{}` | `{}` | {} | {} | {} |",
            c.name,
            short_cid(&c.shape_cid),
            describe_name_source(&c.name_source),
            c.site_indices.len(),
            c.catalog_id.clone().unwrap_or_else(|| "(none)".into()),
        );
    }

    let unnamed: Vec<&ConceptRecord> = pass
        .concepts
        .iter()
        .filter(|c| matches!(c.name_source, NameSource::Auto))
        .collect();
    if !unnamed.is_empty() {
        let _ = writeln!(s);
        let _ = writeln!(
            s,
            "{} unnamed cluster(s) surfaced in pass 1. Each carries a stable shape-CID. The naming round-trip in section 10 closes one of them.",
            unnamed.len()
        );
    }
    let _ = writeln!(s);
}

fn section_4_bindings(s: &mut String, pass: &PassResult) {
    let _ = writeln!(s, "## 4. The bindings");
    let _ = writeln!(s);
    let _ = writeln!(
        s,
        "Each binding is a `(code-site -> concept -> discharge verdict)` triple. The discharge verdict is computed by a structural oracle that respects the substrate's loss model:"
    );
    let _ = writeln!(s);
    let _ = writeln!(
        s,
        "- `exact` if both shape and formula are losslessly transported."
    );
    let _ = writeln!(
        s,
        "- `loudly-bounded-lossy(...)` when the shape transports exactly but the formula uses the smoke-test's single-atom encoding (see section 8)."
    );
    let _ = writeln!(s, "- `refuse(...)` if no contract was recovered.");
    let _ = writeln!(s);
    let _ = writeln!(s, "| Site | Concept | Origin | Discharge Verdict |");
    let _ = writeln!(s, "|---|---|---|---|");
    for b in &pass.bindings {
        let concept_name = pass.concepts[b.concept_idx].name.clone();
        let _ = writeln!(
            s,
            "| `{}::{}` | `{}` | `{}` | `{}` |",
            b.site_file,
            b.site_fn,
            concept_name,
            b.contract_origin.label(),
            b.discharge_verdict.label(),
        );
    }
    let _ = writeln!(s);
}

fn section_5_propagation(s: &mut String, pass: &PassResult) {
    let _ = writeln!(s, "## 5. The propagation event");
    let _ = writeln!(s);
    if pass.witnesses.is_empty() {
        let _ = writeln!(s, "No witnesses lifted in pass 1.");
        let _ = writeln!(s);
        return;
    }
    let _ = writeln!(
        s,
        "One unit-test assertion lifted into the substrate as a `WitnessMemento` and attached to a concept (not a single site). Every other binding to the same concept-CID inherits the witness obligation. Before-and-after shown explicitly below."
    );
    for w in &pass.witnesses {
        render_witness_event(s, pass, w);
    }
    let _ = writeln!(s);
}

fn render_witness_event(s: &mut String, pass: &PassResult, w: &WitnessRecord) {
    let _ = writeln!(s);
    let _ = writeln!(s, "### Witness event");
    let _ = writeln!(s);
    let _ = writeln!(s, "- Source: `{}`", w.source_location);
    let _ = writeln!(
        s,
        "- Concept shape-CID: `{}`",
        short_cid(&w.concept_shape_cid)
    );
    let _ = writeln!(s, "- Formula (substrate-pretty): `{}`", w.pretty_formula);
    let _ = writeln!(s);
    let _ = writeln!(
        s,
        "**Before the witness fires**: the sites bound to this concept have no inherited obligation. The driver's per-site contract origins are recorded individually."
    );
    let _ = writeln!(s);
    let _ = writeln!(s, "| Site | Pre-witness Origin | Pre-witness Verdict |");
    let _ = writeln!(s, "|---|---|---|");
    for idx in &w.propagated_to {
        let b = &pass.bindings[*idx];
        let _ = writeln!(
            s,
            "| `{}::{}` | `{}` | `{}` |",
            b.site_file,
            b.site_fn,
            b.contract_origin.label(),
            b.discharge_verdict.label(),
        );
    }
    let _ = writeln!(s);
    let _ = writeln!(
        s,
        "**After the witness fires**: the concept-CID carries the obligation. Every binding to that shape-CID inherits a `#[cfg_attr(any(), witness(...))]` marker in the rewritten output. The propagated-to set is exactly the concept's site list."
    );
    let _ = writeln!(s);
    let _ = writeln!(s, "| Site | Inherited Witness |");
    let _ = writeln!(s, "|---|---|");
    for idx in &w.propagated_to {
        let b = &pass.bindings[*idx];
        let _ = writeln!(
            s,
            "| `{}::{}` | `{}` |",
            b.site_file, b.site_fn, w.pretty_formula
        );
    }
    let _ = writeln!(s);
    let _ = writeln!(
        s,
        "The propagation is the magic: one assertion against one function attaches a property to N sites by going through the concept abstraction. The witness travels with the algebra, not with the code-site."
    );
}

fn section_6_compression(s: &mut String, pass: &PassResult) {
    let _ = writeln!(s, "## 6. The compression event");
    let _ = writeln!(s);

    // Find concepts with > 1 site.
    let multi: Vec<&ConceptRecord> = pass
        .concepts
        .iter()
        .filter(|c| c.site_indices.len() >= 2)
        .collect();
    if multi.is_empty() {
        let _ = writeln!(s, "No multi-site concept-clusters found in pass 1.");
        let _ = writeln!(s);
        return;
    }
    let _ = writeln!(
        s,
        "When the algebra's address is the cluster key, syntactic variants of the same idea fall into one bucket. The fixture has two such clusters; both compress automatically."
    );
    for c in multi {
        let _ = writeln!(s);
        let _ = writeln!(s, "### Cluster: `{}`", c.name);
        let _ = writeln!(s);
        let _ = writeln!(s, "- Primary shape-CID: `{}`", c.shape_cid);
        if !c.shape_cid_aliases.is_empty() {
            let _ = writeln!(s, "- Alias shape-CIDs (compressed into the same cluster):");
            for alias in &c.shape_cid_aliases {
                let _ = writeln!(s, "  - `{}`", alias);
            }
        }
        let _ = writeln!(s, "- Sites:");
        for idx in &c.site_indices {
            let b = &pass.bindings[*idx];
            let alias_note = if b.shape_cid == c.shape_cid {
                String::from("(primary shape)")
            } else {
                format!("(alias shape `{}`)", short_cid(&b.shape_cid))
            };
            let _ = writeln!(
                s,
                "  - `{}::{}` (line {}) realizes `{}` {}",
                b.site_file, b.site_fn, b.site_line, c.name, alias_note
            );
        }
        let _ = writeln!(s);
        if c.shape_cid_aliases.is_empty() {
            let _ = writeln!(
                s,
                "Every site in this cluster has the same canonical shape-CID. The compression is byte-identical at the algebra level."
            );
        } else {
            let _ = writeln!(
                s,
                "The driver did not need to be told these functions are related. They were written with different syntax (different loop forms, different mutation patterns) and the canonical term-shape classifier collapses them into one cluster across `{}` distinct shape-CIDs. That is the algebra compression event for this cluster: structurally different term-shapes recognized by the catalog's classification rule and merged under one named concept.",
                1 + c.shape_cid_aliases.len()
            );
        }
    }
    let _ = writeln!(s);
}

fn section_7_round_trip(s: &mut String, fixture_root: &Path) {
    let _ = writeln!(s, "## 7. The round-trip");
    let _ = writeln!(s);
    let _ = writeln!(
        s,
        "Every fixture `.rs` was re-emitted into `rewritten/src/<basename>.rs` with a substrate-attributed header block above each fn:"
    );
    let _ = writeln!(s);
    let _ = writeln!(s, "```rust");
    let _ = writeln!(s, "// concept: <name-or-UNNAMED-CONCEPT-N>");
    let _ = writeln!(
        s,
        "// substrate-origin: <annotation-lift | test-lift | algebra-synthesis[rule-id]>"
    );
    let _ = writeln!(s, "// memento-cid: <blake3-512:...>");
    let _ = writeln!(s, "#[cfg_attr(any(), requires(<pre>))]   // if pre present");
    let _ = writeln!(
        s,
        "#[cfg_attr(any(), ensures(<post>))]   // if post present"
    );
    let _ = writeln!(
        s,
        "#[cfg_attr(any(), witness(<formula>))] // if inherited via propagation"
    );
    let _ = writeln!(s, "// witness-inherited-from: <source-of-witness>");
    let _ = writeln!(s, "pub fn the_function(...) {{ ... }}");
    let _ = writeln!(s, "```");
    let _ = writeln!(s);
    let _ = writeln!(
        s,
        "The rewritten tree under `rewritten/` is itself a buildable Rust crate (`smoke-test-e2e-rewritten`). It is the input to pass 2."
    );
    let _ = writeln!(s);
    let diff_paths = [
        ("src/option_handling.rs", "rewritten/src/option_handling.rs"),
        (
            "src/retry_with_backoff.rs",
            "rewritten/src/retry_with_backoff.rs",
        ),
        (
            "src/validate_then_commit.rs",
            "rewritten/src/validate_then_commit.rs",
        ),
    ];
    let _ = writeln!(s, "### Round-trip diff inventory");
    let _ = writeln!(s);
    for (a, b) in diff_paths {
        let _ = writeln!(s, "- `{}` -> `{}`", a, b);
    }
    let _ = writeln!(s);
    let _ = writeln!(
        s,
        "Run `diff -u {0}/src/option_handling.rs {0}/rewritten/src/option_handling.rs` (etc) to see every line the substrate added.",
        fixture_root.display()
    );
    let _ = writeln!(s);
}

fn section_8_zero_authoring(s: &mut String, pass: &PassResult) {
    let _ = writeln!(s, "## 8. Zero-authoring receipt");
    let _ = writeln!(s);
    let _ = writeln!(
        s,
        "Every contract in the rewritten output, with its substrate source traced back to its origin:"
    );
    let _ = writeln!(s);
    let _ = writeln!(s, "| Site | Pre | Post | Origin |");
    let _ = writeln!(s, "|---|---|---|---|");
    for b in &pass.bindings {
        let pre = b.pretty_pre.clone().unwrap_or_else(|| "(none)".into());
        let post = b.pretty_post.clone().unwrap_or_else(|| "(none)".into());
        let _ = writeln!(
            s,
            "| `{}::{}` | `{}` | `{}` | {} |",
            b.site_file,
            b.site_fn,
            pre,
            post,
            origin_explanation(&b.contract_origin)
        );
    }
    let _ = writeln!(s);
    let _ = writeln!(s, "### Known transport losses");
    let _ = writeln!(s);
    let _ = writeln!(
        s,
        "- The driver's `formula_text_to_value` encoding wraps each pretty-printed contract string in a single-atom IR formula (`{{kind:atomic, name:\"<text>\", args:[]}}`). The mint envelope is signed correctly and the BLAKE3-512 CID is deterministic, but the formula is opaque to the kit's parse/serialize round-trip. Discharge verdict for these mints is `loudly-bounded-lossy(formula-string-transport)`. Closing this gap requires the upstream `provekit-ir-symbolic::parse` to accept the rewritten predicate strings; until then the smoke test's transport is signed-but-opaque."
    );
    let _ = writeln!(
        s,
        "- **[CLOSED — Stub 2]** The smoke-test driver now invokes the live `libprovekit::wp` evaluator for algebra-synthesis discharge. A `SmokeTestResolver` carries authored `wp_rule`s for `retry-loop` (`max_attempts >= 0 ∧ Q`) and `guard-then-commit` (`Q`). The evaluator reduces the rule against the postcondition placeholder and returns a ground formula; verdict is `exact`. The previously blocking condition (wp-as-formula PR series — PRs #619, #633, #663) is fully merged on main; this stub is now closed. Remaining loss on algebra-synthesis sites: the synthesized contract formula is still a single-atom shim (Stub 1 — `provekit-ir-symbolic::parse` round-trip not yet wired). The discharge ITSELF is exact; the formula encoding is the remaining open gap."
    );
    let _ = writeln!(
        s,
        "- **[CLOSED — Stub 3]** `ConceptSiteMemento` is now emitted with `schemaVersion: \"1\"` using the canonical `provekit_ir_types::ConceptSiteMemento` type (PR #692, commit 5919e46f). Each site with a recovered contract emits a fully-structured JSON artifact under `artifacts/`. Sites with no recovered contract are skip-emitted (see next bullet). `ConceptAbstractionMemento` remains on `stub-0` schema (its canonical spec is a separate landing)."
    );
    let _ = writeln!(
        s,
        "- **[Open — synthetic referents]** `provenance.{{clusterer_cid,discharger_cid,lifter_cid}}` and `discharge.discharge_receipt_cid` are synthetic deterministic hashes (`blake3-512` of a stable seed string). No real binary CIDs or `MorphismDischargeReceipt` objects exist yet (PR-B and PR-C are pending). The smoke test's CIDs are reproducible and content-addressed but do not reference objects in the pool. Closing this gap requires PR-B (lifter wiring) and PR-C (discharge wiring)."
    );
    let _ = writeln!(
        s,
        "- **[Open — skip-emitted sites]** The 3 sites with no recovered contract (`clamp_score`, `clamp_pressure`, `attempt_succeeds`) do not emit a `ConceptSiteMemento` because `local_contract_cid` is required by spec §1.1 and there is no contract to reference. These sites are recorded with `discharge_verdict: refuse(no contract recovered)` in the report but are absent from the artifacts pool. Closing this gap requires a `FunctionContractMemento` for empty-contract functions (e.g., a trivial `true` postcondition)."
    );
    let _ = writeln!(s);
}

fn section_9_open_karlton(s: &mut String, pass: &PassResult) {
    let _ = writeln!(s, "## 9. Open Karlton work");
    let _ = writeln!(s);
    let unnamed: Vec<&ConceptRecord> = pass
        .concepts
        .iter()
        .filter(|c| c.name.starts_with("UNNAMED-CONCEPT-"))
        .collect();
    if unnamed.is_empty() {
        let _ = writeln!(
            s,
            "Every cluster in pass 1 received a name from the seed catalog or a human annotation. No open naming work remains in this run."
        );
        let _ = writeln!(s);
        return;
    }
    let _ = writeln!(
        s,
        "{} cluster(s) surfaced without a name. The substrate places each one's stable shape-CID alongside a `// concept: UNNAMED-CONCEPT-N` annotation in the rewritten output, inviting a human to write the name where it surfaced. Section 10 demonstrates the closure path.",
        unnamed.len()
    );
    let _ = writeln!(s);
    let _ = writeln!(s, "| Unnamed | Shape-CID | First site |");
    let _ = writeln!(s, "|---|---|---|");
    for c in unnamed {
        let first = c
            .site_indices
            .first()
            .map(|idx| {
                let b = &pass.bindings[*idx];
                format!("`{}::{}`", b.site_file, b.site_fn)
            })
            .unwrap_or_else(|| "(no sites)".into());
        let _ = writeln!(s, "| `{}` | `{}` | {} |", c.name, c.shape_cid, first);
    }
    let _ = writeln!(s);
}

fn section_10_naming_roundtrip(
    s: &mut String,
    pass_1: &PassResult,
    pass_2: &PassResult,
    renamed_pair: Option<&(String, String)>,
) {
    let _ = writeln!(
        s,
        "## 10. The naming round-trip: how Karlton's second hard thing closes inline"
    );
    let _ = writeln!(s);
    let _ = writeln!(
        s,
        "Karlton: there are two hard things in computer science, cache invalidation and naming things. The substrate handles the first via content-addressed mementos. This section handles the second."
    );
    let _ = writeln!(s);
    let _ = writeln!(
        s,
        "When the substrate emits rewritten code with `// concept: UNNAMED-CONCEPT-N` above a cluster it could not name, that annotation IS substrate input on the next lift. A human reads the rewritten code in their editor, replaces `UNNAMED-CONCEPT-N` with a real name, and the next pass picks it up. The concept's shape-CID is stable; only the name changes."
    );
    let _ = writeln!(s);
    let _ = writeln!(s, "### Annotation format");
    let _ = writeln!(s);
    let _ = writeln!(s, "```rust");
    let _ = writeln!(s, "// concept: <name>");
    let _ = writeln!(s, "[other substrate-emitted attributes...]");
    let _ = writeln!(s, "pub fn the_function(...) {{ ... }}");
    let _ = writeln!(s, "```");
    let _ = writeln!(s);
    let _ = writeln!(
        s,
        "The `<name>` is a bare identifier (no `concept:` prefix). The lifter scans upward from each `fn` declaration across attribute lines for the first `// concept: <name>` and uses it. Whitespace is trimmed. Anything that is not a `#[...]` line breaks the upward scan."
    );
    let _ = writeln!(s);

    let _ = writeln!(s, "### Pass 1 -> Pass 1.5 -> Pass 2");
    let _ = writeln!(s);
    if let Some((shape_cid, new_name)) = renamed_pair {
        let _ = writeln!(
            s,
            "Pass 1 surfaced an unnamed cluster at shape-CID `{}`. The driver wrote `// concept: UNNAMED-CONCEPT-N` above one of the cluster's sites in `rewritten/src/...`.",
            short_cid(shape_cid)
        );
        let _ = writeln!(s);
        let _ = writeln!(
            s,
            "Pass 1.5 (simulated human edit, executed by `naming_roundtrip::apply_human_naming`) replaces that annotation with `// concept: {}`. The change is exactly what a human editor would commit. The substrate did not generate the name; the substrate ASKED for it, the human SUPPLIED it, the substrate now LEARNS it.",
            new_name
        );
        let _ = writeln!(s);
        let _ = writeln!(
            s,
            "Pass 2 re-lifts the same source tree (now with the human-edited annotation) and binds the same shape-CID to `concept:{}`. Every binding to that shape-CID inherits the new name without any further human action.",
            new_name
        );
        let _ = writeln!(s);
        let _ = writeln!(s, "Before pass 2:");
        let _ = writeln!(s);
        let _ = writeln!(
            s,
            "- concept at shape-CID `{}` had name `UNNAMED-CONCEPT-N`",
            short_cid(shape_cid)
        );
        let pre_sites = sites_for_shape(pass_1, shape_cid);
        for (file, fn_name) in &pre_sites {
            let _ = writeln!(
                s,
                "  - binding at `{}::{}` reported under `UNNAMED-CONCEPT-N`",
                file, fn_name
            );
        }
        let _ = writeln!(s);
        let _ = writeln!(s, "After pass 2:");
        let _ = writeln!(s);
        // The pass-2 source root is `rewritten/`, so file paths look like
        // `src/<basename>.rs` relative to rewritten.
        let post_sites = sites_for_shape(pass_2, shape_cid);
        let post_name = pass_2
            .concepts
            .iter()
            .find(|c| c.shape_cid == *shape_cid)
            .map(|c| c.name.clone())
            .unwrap_or_else(|| format!("concept:{}", new_name));
        let _ = writeln!(
            s,
            "- concept at shape-CID `{}` has name `{}`",
            short_cid(shape_cid),
            post_name
        );
        for (file, fn_name) in &post_sites {
            let _ = writeln!(
                s,
                "  - binding at `{}::{}` reported under `{}`",
                file, fn_name, post_name
            );
        }
        let _ = writeln!(s);
        let _ = writeln!(
            s,
            "The shape-CID did not move. The name attached. Every other binding inherited the new name through the concept-CID, not through a code change."
        );
    } else {
        let _ = writeln!(
            s,
            "Pass 1 did not surface any UNNAMED concept; the seed catalog covered every cluster. The naming round-trip mechanism is unexercised in this run but is implemented and documented above. The next fixture that uses a novel shape will exercise it."
        );
    }
    let _ = writeln!(s);
    let _ = writeln!(
        s,
        "Karlton's second hard thing closes inline. No catalog editor, no separate naming workflow. The unnamed thing surfaces where the code is. The name lands where the unnamed thing surfaced. The substrate learns on the next pass."
    );
    let _ = writeln!(s);
}

// ----- helpers --------------------------------------------------------------

fn sites_for_shape(pass: &PassResult, shape_cid: &str) -> Vec<(String, String)> {
    // Resolve to a concept (looking through aliases) and return every
    // binding that resolved to that concept regardless of which alias
    // shape produced it.
    let concept_idx_opt = pass.concepts.iter().position(|c| {
        c.shape_cid == shape_cid || c.shape_cid_aliases.iter().any(|a| a == shape_cid)
    });
    let Some(ci) = concept_idx_opt else {
        return Vec::new();
    };
    let mut out = Vec::new();
    for idx in &pass.concepts[ci].site_indices {
        let b = &pass.bindings[*idx];
        out.push((b.site_file.clone(), b.site_fn.clone()));
    }
    out
}

fn count_unique_files(pass: &PassResult) -> usize {
    let mut set: BTreeMap<String, ()> = BTreeMap::new();
    for b in &pass.bindings {
        set.insert(b.site_file.clone(), ());
    }
    set.len()
}

fn describe_name_source(n: &NameSource) -> &'static str {
    match n {
        NameSource::Auto => "auto (UNNAMED-CONCEPT-N)",
        NameSource::Catalog => "seed catalog",
        NameSource::HumanAnnotation => "human annotation",
    }
}

fn origin_explanation(o: &ContractOrigin) -> String {
    match o {
        ContractOrigin::AttributeLift => {
            "annotation-lift (lifted from `#[requires]`/`#[ensures]` on the source)".into()
        }
        ContractOrigin::TestLift => {
            "test-lift (lifted from `assert!` in `tests/properties.rs`)".into()
        }
        ContractOrigin::AlgebraSynthesis { rule_id } => format!(
            "algebra-synthesis (wp_rule `{}` fired structurally on the cluster)",
            rule_id
        ),
        ContractOrigin::Empty => "(no contract recovered)".into(),
    }
}

fn short_cid(s: &str) -> String {
    // `blake3-512:` + 16 hex chars.
    let prefix = "blake3-512:";
    if let Some(rest) = s.strip_prefix(prefix) {
        let truncated: String = rest.chars().take(16).collect();
        format!("{}{}\u{2026}", prefix, truncated)
    } else if s.len() > 24 {
        format!("{}\u{2026}", &s[..24])
    } else {
        s.to_string()
    }
}
