name = "go-lift"
<<<<<<< HEAD
command = ["go", "run", "./cmd/provekit-lift-go"]
working_dir = "provekit-lift-go-tests"
=======
command = ["./provekit-lift-go-tests/provekit-lift-go", "--rpc"]
working_dir = "."
>>>>>>> origin/main
