// SPDX-License-Identifier: Apache-2.0
//
// Hand-maintained operation table for the current core subset.
// The full operation set is mint-more-realizations, not new machinery:
// each added operation is another homomorphic table entry plus its receipt.

pub const CORE_OPERATION_SUBSET: &[&str] = &[
    "seq",
    "if",
    "while",
    "return",
    "call",
    "break",
    "continue",
    "skip",
    "eq",
    "lt",
    "le",
    "add",
    "sub",
    "mul",
    "neg",
    "and",
    "or",
    "not",
    "var",
    "const",
    "deref",
    "assign",
    "source-unit",
    "cast",
    "bop_eq",
    "bop_ne",
    "bop_lt",
    "bop_le",
    "bop_gt",
    "bop_ge",
    "bop_add",
    "bop_sub",
    "bop_mul",
    "bop_div",
    "bop_mod",
    "bop_shl",
    "bop_shr",
    "bop_bitand",
    "bop_bitor",
    "bop_bitxor",
    "bop_logand",
    "bop_logor",
    "bop_comma",
    "uop_neg",
    "uop_lognot",
    "uop_deref",
    "uop_bitnot",
    "uop_plus",
];

pub const ALGEBRA_TO_C_TABLE: &[(&str, &str)] = &[
    ("seq(a,b)", "emit a followed by b"),
    (
        "if(c,t,e) statement",
        "if c { t } else { e } with structured blocks",
    ),
    (
        "if(c,t,e) expression",
        "(c) ? (t) : (e) with expression branches",
    ),
    ("while(c,b)", "while c { b }"),
    ("return(e)", "return (e);"),
    ("call(f,args)", "f(args)"),
    ("break(unit)", "break;"),
    ("continue(unit)", "continue;"),
    ("skip(unit)", ";"),
    ("var x", "x"),
    ("const n", "n"),
    ("eq(a,b)", "((a) == (b))"),
    ("lt(a,b)", "((a) < (b))"),
    ("le(a,b)", "((a) <= (b))"),
    ("add(a,b)", "((a) + (b))"),
    ("sub(a,b)", "((a) - (b))"),
    ("mul(a,b)", "((a) * (b))"),
    ("neg(a)", "(-(a))"),
    ("and(a,b)", "((a) && (b))"),
    ("or(a,b)", "((a) || (b))"),
    ("not(a)", "(!(a))"),
    ("deref(p)", "(*(p))"),
    (
        "source-unit(bytes, term)",
        "project to term before lowering",
    ),
    ("cast(T, v)", "((T)(v))"),
    ("bop_eq(a,b)", "((a) == (b))"),
    ("bop_ne(a,b)", "((a) != (b))"),
    ("bop_lt(a,b)", "((a) < (b))"),
    ("bop_le(a,b)", "((a) <= (b))"),
    ("bop_gt(a,b)", "((a) > (b))"),
    ("bop_ge(a,b)", "((a) >= (b))"),
    ("bop_add(a,b)", "((a) + (b))"),
    ("bop_sub(a,b)", "((a) - (b))"),
    ("bop_mul(a,b)", "((a) * (b))"),
    ("bop_div(a,b)", "((a) / (b))"),
    ("bop_mod(a,b)", "((a) % (b))"),
    ("bop_shl(a,b)", "((a) << (b))"),
    ("bop_shr(a,b)", "((a) >> (b))"),
    ("bop_bitand(a,b)", "((a) & (b))"),
    ("bop_bitor(a,b)", "((a) | (b))"),
    ("bop_bitxor(a,b)", "((a) ^ (b))"),
    ("bop_logand(a,b)", "((a) && (b))"),
    ("bop_logor(a,b)", "((a) || (b))"),
    ("bop_comma(a,b)", "((a), (b))"),
    ("uop_neg(a)", "(-(a))"),
    ("uop_lognot(a)", "(!(a))"),
    ("uop_deref(p)", "(*(p))"),
    ("uop_bitnot(a)", "(~(a))"),
    ("uop_plus(a)", "(+(a))"),
    (
        "assign(lv,e)",
        "lv = (e); in statement position, (lv = (e)) in expression position",
    ),
];
