#!/usr/bin/env python3
"""Generate the C11 cursor-kind signature assets from a vendored snapshot."""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import OrderedDict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SIG = ROOT / "menagerie/c11-language-signature"
SPECS = SIG / "specs"
MAPPING = SIG / "cursor-kind-map.generated.json"
C_HDR = ROOT / "implementations/c/provekit-walk-c/src/c11_cursor_dispatch.generated.h"
C_SRC = ROOT / "implementations/c/provekit-walk-c/src/c11_cursor_dispatch.generated.c"
GENERATOR = "tools/generate-c11-from-cursorkind.py"
GENERATED = f"DO NOT EDIT — generated by {GENERATOR}"
SNAPSHOT_REPO_PATH = Path("tools/c11gen/cxcursorkind-snapshot.h")
SNAPSHOT = ROOT / SNAPSHOT_REPO_PATH


SORTS = [
    "sort_stmt.spec.json",
    "sort_expr.spec.json",
    "sort_lvalue.spec.json",
    "sort_int.spec.json",
    "sort_ptr.spec.json",
    "sort_bool.spec.json",
    "sort_unit.spec.json",
    "sort_fncontract.spec.json",
    "sort_fieldname.spec.json",
    "sort_listofstmt.spec.json",
    "sort_listofexpr.spec.json",
    "sort_addr.spec.json",
    "sort_value.spec.json",
    "sort_reason.spec.json",
    "sort_bottom.spec.json",
]

CORE_OPS = [
    "op_skip.spec.json",
    "op_seq.spec.json",
    "op_if.spec.json",
    "op_while.spec.json",
    "op_for.spec.json",
    "op_switch.spec.json",
    "op_call.spec.json",
    "op_return.spec.json",
    "op_break.spec.json",
    "op_continue.spec.json",
    "op_deref.spec.json",
    "op_member.spec.json",
    "op_add.spec.json",
    "op_sub.spec.json",
    "op_mul.spec.json",
    "op_eq.spec.json",
    "op_lt.spec.json",
    "op_le.spec.json",
    "op_and.spec.json",
    "op_or.spec.json",
    "op_not.spec.json",
    "op_assign.spec.json",
    "op_neg.spec.json",
]

EQUATIONS = [
    "eq_seq_assoc.spec.json",
    "eq_seq_skip_left.spec.json",
    "eq_seq_skip_right.spec.json",
    "eq_if_true.spec.json",
    "eq_if_false.spec.json",
    "eq_if_idemp.spec.json",
    "eq_while_false.spec.json",
    "eq_for_desugar.spec.json",
    "eq_and_false.spec.json",
    "eq_and_true.spec.json",
    "eq_or_true.spec.json",
    "eq_or_false.spec.json",
    "eq_not_not.spec.json",
    "eff_eq_read_after_write.spec.json",
]

EFFECT_SIGS = [
    "effsig_memread.spec.json",
    "effsig_memwrite.spec.json",
    "effsig_io.spec.json",
    "effsig_trap.spec.json",
]

EFFECT_OPS = [
    "eff_op_read.spec.json",
    "eff_op_write.spec.json",
    "eff_op_input.spec.json",
    "eff_op_output.spec.json",
    "eff_op_trap.spec.json",
]


MINTED_OPS: OrderedDict[str, dict] = OrderedDict(
    [
        (
            "opaque",
            {
                "formals": ["unit"],
                "formal_sorts": ["Unit"],
                "return_sort": "Stmt",
                "wp": "stable placeholder for non-lifted or intentionally opaque cursor kinds",
                "notes": "Serializer stubs this operation unless a literal source payload is supplied.",
            },
        ),
        (
            "decl",
            {
                "formals": ["name", "initializer"],
                "formal_sorts": ["Expr", "Expr"],
                "return_sort": "Stmt",
                "wp": "bind local name to initializer before continuing",
            },
        ),
        (
            "case",
            {
                "formals": ["value", "body"],
                "formal_sorts": ["Expr", "Stmt"],
                "return_sort": "Stmt",
                "wp": "switch case arm body guarded by value",
            },
        ),
        (
            "default",
            {
                "formals": ["body"],
                "formal_sorts": ["Stmt"],
                "return_sort": "Stmt",
                "wp": "switch default arm body",
            },
        ),
        (
            "label",
            {
                "formals": ["name", "body"],
                "formal_sorts": ["Expr", "Stmt"],
                "return_sort": "Stmt",
                "wp": "statement label with body",
            },
        ),
        (
            "goto",
            {
                "formals": ["target"],
                "formal_sorts": ["Expr"],
                "return_sort": "Stmt",
                "wp": "control transfer to label target",
                "notes": "Projection is intentionally conservative.",
            },
        ),
        (
            "do",
            {
                "formals": ["body", "cond"],
                "formal_sorts": ["Stmt", "Bool"],
                "return_sort": "Stmt",
                "wp": "do body once, then loop while cond",
            },
        ),
        (
            "cast",
            {
                "formals": ["value"],
                "formal_sorts": ["Expr"],
                "return_sort": "Expr",
                "wp": "C cast expression preserving lifted child value",
            },
        ),
        (
            "array-subscript",
            {
                "formals": ["base", "index"],
                "formal_sorts": ["Expr", "Expr"],
                "return_sort": "LValue",
                "wp": "array element lvalue projection",
            },
        ),
        (
            "conditional",
            {
                "formals": ["cond", "then_expr", "else_expr"],
                "formal_sorts": ["Bool", "Expr", "Expr"],
                "return_sort": "Expr",
                "wp": "ternary expression selected by cond",
            },
        ),
        (
            "compound-literal",
            {
                "formals": ["value"],
                "formal_sorts": ["Expr"],
                "return_sort": "Expr",
                "wp": "compound literal expression payload",
            },
        ),
        (
            "init-list",
            {
                "formals": ["items"],
                "formal_sorts": ["ListOfExpr"],
                "return_sort": "Expr",
                "wp": "initializer list expression payload",
            },
        ),
        (
            "string-literal",
            {
                "formals": ["unit"],
                "formal_sorts": ["Unit"],
                "return_sort": "Expr",
                "wp": "string literal token payload elided at this layer",
                "notes": "Serializer is stubbed until literal payload terms are added.",
            },
        ),
        (
            "char-literal",
            {
                "formals": ["unit"],
                "formal_sorts": ["Unit"],
                "return_sort": "Expr",
                "wp": "character literal token payload elided at this layer",
                "notes": "Serializer is stubbed until literal payload terms are added.",
            },
        ),
        (
            "float-literal",
            {
                "formals": ["unit"],
                "formal_sorts": ["Unit"],
                "return_sort": "Expr",
                "wp": "floating literal token payload elided at this layer",
                "notes": "Serializer is stubbed until literal payload terms are added.",
            },
        ),
        (
            "imaginary-literal",
            {
                "formals": ["unit"],
                "formal_sorts": ["Unit"],
                "return_sort": "Expr",
                "wp": "imaginary literal token payload elided at this layer",
                "notes": "Serializer is stubbed until literal payload terms are added.",
            },
        ),
        (
            "null",
            {
                "formals": ["unit"],
                "formal_sorts": ["Unit"],
                "return_sort": "Expr",
                "wp": "null pointer constant expression",
            },
        ),
        (
            "generic-selection",
            {
                "formals": ["control", "associations"],
                "formal_sorts": ["Expr", "ListOfExpr"],
                "return_sort": "Expr",
                "wp": "C11 generic selection expression",
            },
        ),
        (
            "stmt-expr",
            {
                "formals": ["body"],
                "formal_sorts": ["Stmt"],
                "return_sort": "Expr",
                "wp": "GNU statement expression payload",
            },
        ),
        (
            "addr-label",
            {
                "formals": ["label"],
                "formal_sorts": ["Expr"],
                "return_sort": "Expr",
                "wp": "GNU address-of-label expression",
            },
        ),
        (
            "div",
            {
                "formals": ["lhs", "rhs"],
                "formal_sorts": ["Int", "Int"],
                "return_sort": "Int",
                "wp": "integer division expression",
            },
        ),
        (
            "mod",
            {
                "formals": ["lhs", "rhs"],
                "formal_sorts": ["Int", "Int"],
                "return_sort": "Int",
                "wp": "integer remainder expression",
            },
        ),
        (
            "shl",
            {
                "formals": ["lhs", "rhs"],
                "formal_sorts": ["Int", "Int"],
                "return_sort": "Int",
                "wp": "integer left shift expression",
            },
        ),
        (
            "shr",
            {
                "formals": ["lhs", "rhs"],
                "formal_sorts": ["Int", "Int"],
                "return_sort": "Int",
                "wp": "integer right shift expression",
            },
        ),
        (
            "bit_and",
            {
                "formals": ["lhs", "rhs"],
                "formal_sorts": ["Int", "Int"],
                "return_sort": "Int",
                "wp": "integer bitwise and expression",
            },
        ),
        (
            "bit_or",
            {
                "formals": ["lhs", "rhs"],
                "formal_sorts": ["Int", "Int"],
                "return_sort": "Int",
                "wp": "integer bitwise or expression",
            },
        ),
        (
            "bit_xor",
            {
                "formals": ["lhs", "rhs"],
                "formal_sorts": ["Int", "Int"],
                "return_sort": "Int",
                "wp": "integer bitwise xor expression",
            },
        ),
        (
            "gt",
            {
                "formals": ["lhs", "rhs"],
                "formal_sorts": ["Int", "Int"],
                "return_sort": "Bool",
                "wp": "integer greater-than comparison",
            },
        ),
        (
            "ge",
            {
                "formals": ["lhs", "rhs"],
                "formal_sorts": ["Int", "Int"],
                "return_sort": "Bool",
                "wp": "integer greater-than-or-equal comparison",
            },
        ),
        (
            "ne",
            {
                "formals": ["lhs", "rhs"],
                "formal_sorts": ["Int", "Int"],
                "return_sort": "Bool",
                "wp": "integer not-equal comparison",
            },
        ),
        (
            "comma",
            {
                "formals": ["lhs", "rhs"],
                "formal_sorts": ["Expr", "Expr"],
                "return_sort": "Expr",
                "wp": "comma expression evaluates lhs then yields rhs",
            },
        ),
        (
            "bit_not",
            {
                "formals": ["value"],
                "formal_sorts": ["Int"],
                "return_sort": "Int",
                "wp": "integer bitwise complement expression",
            },
        ),
        (
            "addr_of",
            {
                "formals": ["target"],
                "formal_sorts": ["LValue"],
                "return_sort": "Ptr",
                "wp": "address-of expression yielding a pointer to target",
            },
        ),
        (
            "pre_inc",
            {
                "formals": ["target"],
                "formal_sorts": ["LValue"],
                "return_sort": "Expr",
                "wp": "prefix increment expression yielding the updated value",
            },
        ),
        (
            "post_inc",
            {
                "formals": ["target"],
                "formal_sorts": ["LValue"],
                "return_sort": "Expr",
                "wp": "postfix increment expression yielding the previous value",
            },
        ),
        (
            "pre_dec",
            {
                "formals": ["target"],
                "formal_sorts": ["LValue"],
                "return_sort": "Expr",
                "wp": "prefix decrement expression yielding the updated value",
            },
        ),
        (
            "post_dec",
            {
                "formals": ["target"],
                "formal_sorts": ["LValue"],
                "return_sort": "Expr",
                "wp": "postfix decrement expression yielding the previous value",
            },
        ),
        (
            "plus",
            {
                "formals": ["value"],
                "formal_sorts": ["Int"],
                "return_sort": "Int",
                "wp": "unary plus expression preserving value",
            },
        ),
        (
            "unexposed-stmt",
            {
                "formals": ["children"],
                "formal_sorts": ["ListOfStmt"],
                "return_sort": "Stmt",
                "wp": "libclang unexposed statement with lifted child sequence",
            },
        ),
        (
            "unexposed-expr",
            {
                "formals": ["children"],
                "formal_sorts": ["ListOfExpr"],
                "return_sort": "Expr",
                "wp": "libclang unexposed expression with lifted child sequence",
            },
        ),
        (
            "binary-operator",
            {
                "formals": ["lhs", "rhs"],
                "formal_sorts": ["Expr", "Expr"],
                "return_sort": "Expr",
                "wp": "fallback binary operator when no core C11 operator is selected",
                "notes": "Core arithmetic and comparison operators dispatch to their existing op CIDs.",
            },
        ),
        (
            "unary-operator",
            {
                "formals": ["value"],
                "formal_sorts": ["Expr"],
                "return_sort": "Expr",
                "wp": "fallback unary operator when no core C11 operator is selected",
                "notes": "Negation, boolean not, and dereference dispatch to existing op CIDs.",
            },
        ),
    ]
)

SERIALIZER_TEMPLATES: OrderedDict[str, str] = OrderedDict(
    [
        ("skip", ";"),
        ("seq", "<a>\n<b>"),
        ("if", "if (<cond>) { <then> } else { <else> }"),
        ("while", "while (<cond>) { <body> }"),
        ("for", "for (<init>; <cond>; <step>) { <body> }"),
        ("switch", "switch (<scrutinee>) { <body> }"),
        ("call", "<callee>(<args...>)"),
        ("return", "return <value>;"),
        ("break", "break;"),
        ("continue", "continue;"),
        ("deref", "(*<value>)"),
        ("member", "<base>.<field>"),
        ("add", "(<lhs> + <rhs>)"),
        ("sub", "(<lhs> - <rhs>)"),
        ("mul", "(<lhs> * <rhs>)"),
        ("eq", "(<lhs> == <rhs>)"),
        ("lt", "(<lhs> < <rhs>)"),
        ("le", "(<lhs> <= <rhs>)"),
        ("and", "(<lhs> && <rhs>)"),
        ("or", "(<lhs> || <rhs>)"),
        ("not", "(!<value>)"),
        ("assign", "(<lhs> = <rhs>)"),
        ("neg", "(-<value>)"),
        ("div", "(<lhs> / <rhs>)"),
        ("mod", "(<lhs> % <rhs>)"),
        ("shl", "(<lhs> << <rhs>)"),
        ("shr", "(<lhs> >> <rhs>)"),
        ("bit_and", "(<lhs> & <rhs>)"),
        ("bit_or", "(<lhs> | <rhs>)"),
        ("bit_xor", "(<lhs> ^ <rhs>)"),
        ("gt", "(<lhs> > <rhs>)"),
        ("ge", "(<lhs> >= <rhs>)"),
        ("ne", "(<lhs> != <rhs>)"),
        ("comma", "(<lhs>, <rhs>)"),
        ("bit_not", "(~<value>)"),
        ("addr_of", "(&<value>)"),
        ("pre_inc", "(++<value>)"),
        ("post_inc", "(<value>++)"),
        ("pre_dec", "(--<value>)"),
        ("post_dec", "(<value>--)"),
        ("plus", "(+<value>)"),
        ("opaque", "/* opaque */"),
        ("decl", "int <name> = <initializer>;"),
        ("case", "case <value>: <body>"),
        ("default", "default: <body>"),
        ("label", "<name>: <body>"),
        ("goto", "goto <target>;"),
        ("do", "do { <body> } while (<cond>);"),
        ("cast", "((int)<value>)"),
        ("array-subscript", "<base>[<index>]"),
        ("conditional", "(<cond> ? <then_expr> : <else_expr>)"),
        ("compound-literal", "((int){<value>})"),
        ("init-list", "{<items...>}"),
        ("string-literal", "\"provekit\""),
        ("char-literal", "'p'"),
        ("float-literal", "1.5"),
        ("imaginary-literal", "1.0i"),
        ("null", "0"),
        ("generic-selection", "_Generic(<control>, <associations...>)"),
        ("stmt-expr", "({ <body> })"),
        ("addr-label", "&&<label>"),
        ("unexposed-stmt", "<children...>"),
        ("unexposed-expr", "<children...>"),
        ("binary-operator", "(<lhs> / <rhs>)"),
        ("unary-operator", "(~<value>)"),
    ]
)


CORE_CURSOR_MAP = {
    "CXCursor_CompoundStmt": ("seq", 2, "fold children left with seq; empty body is skip"),
    "CXCursor_IfStmt": ("if", 3, "condition, then branch, else branch or skip"),
    "CXCursor_SwitchStmt": ("switch", 2, "scrutinee, folded arm body"),
    "CXCursor_WhileStmt": ("while", 2, "condition, body"),
    "CXCursor_ForStmt": ("for", 4, "init, condition, step, body"),
    "CXCursor_ReturnStmt": ("return", 1, "returned expression or unit"),
    "CXCursor_BreakStmt": ("break", 1, "unit"),
    "CXCursor_ContinueStmt": ("continue", 1, "unit"),
    "CXCursor_NullStmt": ("skip", 1, "unit"),
    "CXCursor_CallExpr": ("call", 2, "callee reference, argument list"),
    "CXCursor_MemberRefExpr": ("member", 2, "base lvalue, field name"),
}

LEAF_CURSOR_MAP = {
    "CXCursor_DeclRefExpr": ("var", 0, "term leaf; spelling is the variable name"),
    "CXCursor_IntegerLiteral": ("const", 0, "term leaf; token text is the integer value"),
}

BINARY_OPERATOR_TOKENS: OrderedDict[str, str] = OrderedDict(
    [
        ("==", "eq"),
        ("!=", "ne"),
        ("&&", "and"),
        ("||", "or"),
        ("<=", "le"),
        (">=", "ge"),
        ("<<", "shl"),
        (">>", "shr"),
        ("<", "lt"),
        (">", "gt"),
        ("=", "assign"),
        ("+", "add"),
        ("-", "sub"),
        ("*", "mul"),
        ("/", "div"),
        ("%", "mod"),
        ("&", "bit_and"),
        ("|", "bit_or"),
        ("^", "bit_xor"),
        (",", "comma"),
    ]
)

COMPOUND_ASSIGN_OPERATOR_TOKENS: OrderedDict[str, str] = OrderedDict(
    [
        ("+=", "add"),
        ("-=", "sub"),
        ("*=", "mul"),
        ("/=", "div"),
        ("%=", "mod"),
        ("<<=", "shl"),
        (">>=", "shr"),
        ("&=", "bit_and"),
        ("|=", "bit_or"),
        ("^=", "bit_xor"),
    ]
)

UNARY_OPERATOR_TOKENS: OrderedDict[str, str] = OrderedDict(
    [
        ("-", "neg"),
        ("!", "not"),
        ("*", "deref"),
        ("~", "bit_not"),
        ("&", "addr_of"),
        ("prefix ++", "pre_inc"),
        ("postfix ++", "post_inc"),
        ("prefix --", "pre_dec"),
        ("postfix --", "post_dec"),
        ("+", "plus"),
    ]
)

DISPATCH_CURSOR_MAP = {
    "CXCursor_BinaryOperator": {
        "op_name": "operator-dispatch",
        "arity": 2,
        "child_shape": "lhs, rhs; token text selects a concrete binary op or fallback binary-operator",
        "token_ops": BINARY_OPERATOR_TOKENS,
        "fallback": "binary-operator",
    },
    "CXCursor_CompoundAssignOperator": {
        "op_name": "operator-dispatch",
        "arity": 2,
        "child_shape": "lhs, rhs; token text desugars to assign(lhs, op(lhs, rhs)) or fallback binary-operator",
        "token_ops": COMPOUND_ASSIGN_OPERATOR_TOKENS,
        "fallback": "binary-operator",
    },
    "CXCursor_UnaryOperator": {
        "op_name": "operator-dispatch",
        "arity": 1,
        "child_shape": "operand; token text and prefix/postfix position select a concrete unary op or fallback unary-operator",
        "token_ops": UNARY_OPERATOR_TOKENS,
        "fallback": "unary-operator",
    },
}

MINTED_CURSOR_MAP = {
    "CXCursor_VarDecl": ("decl", 2, "declared name, initializer or unit"),
    "CXCursor_DeclStmt": ("decl", 2, "fold variable declarations as decl terms"),
    "CXCursor_CaseStmt": ("case", 2, "case expression, folded body"),
    "CXCursor_DefaultStmt": ("default", 1, "folded body"),
    "CXCursor_LabelStmt": ("label", 2, "label name, body"),
    "CXCursor_GotoStmt": ("goto", 1, "label target"),
    "CXCursor_IndirectGotoStmt": ("goto", 1, "computed label target"),
    "CXCursor_DoStmt": ("do", 2, "body, condition"),
    "CXCursor_CStyleCastExpr": ("cast", 1, "cast child expression"),
    "CXCursor_ArraySubscriptExpr": ("array-subscript", 2, "base, index"),
    "CXCursor_ConditionalOperator": ("conditional", 3, "condition, then expression, else expression"),
    "CXCursor_CompoundLiteralExpr": ("compound-literal", 1, "initializer payload"),
    "CXCursor_InitListExpr": ("init-list", 1, "list payload"),
    "CXCursor_StringLiteral": ("string-literal", 1, "unit placeholder"),
    "CXCursor_CharacterLiteral": ("char-literal", 1, "unit placeholder"),
    "CXCursor_FloatingLiteral": ("float-literal", 1, "unit placeholder"),
    "CXCursor_ImaginaryLiteral": ("imaginary-literal", 1, "unit placeholder"),
    "CXCursor_GNUNullExpr": ("null", 1, "unit placeholder"),
    "CXCursor_GenericSelectionExpr": ("generic-selection", 2, "control expression, association list"),
    "CXCursor_StmtExpr": ("stmt-expr", 1, "compound statement payload"),
    "CXCursor_AddrLabelExpr": ("addr-label", 1, "label target"),
    "CXCursor_UnexposedStmt": ("unexposed-stmt", 1, "folded children"),
    "CXCursor_UnexposedExpr": ("unexposed-expr", 1, "folded children"),
}

TRANSPARENT_CURSOR_KINDS = {
    "CXCursor_ParenExpr": "single child expression",
}

OPAQUE_PREFIXES = (
    "CXCursor_ObjC",
    "CXCursor_CXX",
    "CXCursor_OMP",
    "CXCursor_OpenACC",
    "CXCursor_CUDA",
    "CXCursor_SEH",
    "CXCursor_MS",
)

OPAQUE_EXACT = {
    "CXCursor_TranslationUnit",
    "CXCursor_UnexposedDecl",
    "CXCursor_StructDecl",
    "CXCursor_UnionDecl",
    "CXCursor_ClassDecl",
    "CXCursor_EnumDecl",
    "CXCursor_FieldDecl",
    "CXCursor_EnumConstantDecl",
    "CXCursor_FunctionDecl",
    "CXCursor_ParmDecl",
    "CXCursor_TypedefDecl",
    "CXCursor_Namespace",
    "CXCursor_LinkageSpec",
    "CXCursor_TemplateTypeParameter",
    "CXCursor_NonTypeTemplateParameter",
    "CXCursor_TemplateTemplateParameter",
    "CXCursor_FunctionTemplate",
    "CXCursor_ClassTemplate",
    "CXCursor_ClassTemplatePartialSpecialization",
    "CXCursor_NamespaceAlias",
    "CXCursor_UsingDirective",
    "CXCursor_UsingDeclaration",
    "CXCursor_TypeAliasDecl",
    "CXCursor_TypeRef",
    "CXCursor_TemplateRef",
    "CXCursor_NamespaceRef",
    "CXCursor_OverloadedDeclRef",
    "CXCursor_VariableRef",
    "CXCursor_LabelRef",
    "CXCursor_InvalidFile",
    "CXCursor_NoDeclFound",
    "CXCursor_NotImplemented",
    "CXCursor_InvalidCode",
    "CXCursor_GCCAsmStmt",
    "CXCursor_BuiltinBitCastExpr",
    "CXCursor_ModuleImportDecl",
    "CXCursor_TypeAliasTemplateDecl",
    "CXCursor_StaticAssert",
    "CXCursor_FriendDecl",
    "CXCursor_ConceptDecl",
    "CXCursor_OverloadCandidate",
    "CXCursor_PreprocessingDirective",
    "CXCursor_MacroDefinition",
    "CXCursor_MacroExpansion",
    "CXCursor_InclusionDirective",
}


def find_cursor_snapshot(explicit: str | None) -> Path:
    path = Path(explicit).expanduser() if explicit else SNAPSHOT
    if path.exists():
        return path
    raise SystemExit(f"could not find CXCursorKind snapshot: {path}")


def source_path_for(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(ROOT.resolve()))
    except ValueError:
        return str(path)


def parse_cursor_enum(index_h: Path) -> list[dict]:
    text = index_h.read_text(encoding="utf-8")
    m = re.search(r"enum\s+CXCursorKind\s*\{(?P<body>.*?)\n\};", text, re.S)
    if not m:
        raise SystemExit(f"enum CXCursorKind not found in {index_h}")
    body = re.sub(r"/\*.*?\*/", "", m.group("body"), flags=re.S)
    body = re.sub(r"//.*", "", body)
    values: dict[str, int] = {}
    entries: list[dict] = []
    next_value = 0
    for raw in body.splitlines():
        line = raw.strip()
        if not line or not line.startswith("CXCursor_"):
            continue
        mm = re.match(r"(CXCursor_[A-Za-z0-9_]+)\s*(?:=\s*([^,]+))?\s*,?", line)
        if not mm:
            continue
        name, expr = mm.group(1), mm.group(2)
        alias_of = None
        if expr is None:
            value = next_value
        else:
            expr = expr.strip()
            if re.fullmatch(r"0x[0-9A-Fa-f]+|\d+", expr):
                value = int(expr, 0)
            elif expr in values:
                value = values[expr]
                alias_of = expr
            else:
                continue
        values[name] = value
        next_value = value + 1
        if name.startswith("CXCursor_First") or name.startswith("CXCursor_Last"):
            continue
        entries.append({"cursor_kind": name, "value": value, "alias_of": alias_of})
    return entries


def op_name_for_spec(spec: str) -> str:
    path = SPECS / spec
    if path.exists():
        try:
            value = json.loads(path.read_text(encoding="utf-8"))
            fn_name = value.get("fn_name", "")
            if fn_name.startswith("c11:"):
                return fn_name.removeprefix("c11:")
        except (OSError, json.JSONDecodeError):
            pass
    return spec.removeprefix("op_").removesuffix(".spec.json").replace("_", "-")


def cids_by_op() -> tuple[dict[str, str], str | None, list[dict]]:
    entries = []
    cids_path = SIG / "cids.tsv"
    if cids_path.exists():
        for line in cids_path.read_text(encoding="utf-8").splitlines():
            parts = line.split("\t")
            if len(parts) >= 3:
                entry = {
                    "kind": parts[0],
                    "spec": parts[1],
                    "cid": parts[2],
                }
                if len(parts) >= 4:
                    entry["path"] = parts[3]
                entries.append(entry)
    elif (SIG / "component-cids.json").exists():
        entries = json.loads((SIG / "component-cids.json").read_text(encoding="utf-8"))

    op_cids: dict[str, str] = {}
    signature_cid = None
    for entry in entries:
        spec = entry.get("spec", "")
        cid = entry.get("cid")
        if not cid:
            continue
        if spec.startswith("op_") and spec.endswith(".spec.json"):
            op_cids[op_name_for_spec(spec)] = cid
        elif spec == "language_signature_c11.spec.json":
            signature_cid = cid
        elif spec.startswith("eff_op_") and spec.endswith(".spec.json"):
            name = "effect:" + spec.removeprefix("eff_op_").removesuffix(".spec.json")
            op_cids[name] = cid
    return op_cids, signature_cid, entries


def sort_ref(name: str) -> dict:
    return {"kind": "ctor", "name": name, "args": []}


def true_formula() -> dict:
    return {"kind": "atomic", "name": "true", "args": []}


def operation_post(name: str, arity: list[str], result: str, wp: str, notes: str | None = None) -> dict:
    post = {
        "kind": "operation-contract",
        "operator": name,
        "arity": arity,
        "result": result,
        "wp": wp,
    }
    if notes:
        post["notes"] = notes
    return post


def algorithm_spec(name: str, cfg: dict) -> dict:
    return {
        "kind": "algorithm",
        "fn_name": f"c11:{name}",
        "formals": cfg["formals"],
        "formal_sorts": [sort_ref(s) for s in cfg["formal_sorts"]],
        "return_sort": sort_ref(cfg["return_sort"]),
        "pre": true_formula(),
        "post": operation_post(
            name,
            cfg["formal_sorts"],
            cfg["return_sort"],
            cfg["wp"],
            cfg.get("notes"),
        ),
        "effects": {"effects": []},
        "locus": "menagerie/c11-language-signature/README.md#generated-cursor-kind-operations",
    }


def spec_filename_for_op(name: str) -> str:
    return "op_" + name.replace("-", "_").replace(":", "_") + ".spec.json"


def generated_op_specs() -> dict[Path, str]:
    out: dict[Path, str] = {}
    for name, cfg in MINTED_OPS.items():
        path = SPECS / spec_filename_for_op(name)
        out[path] = json.dumps(algorithm_spec(name, cfg), indent=2, sort_keys=False) + "\n"
    return out


def op_spec_files() -> list[str]:
    return CORE_OPS + [spec_filename_for_op(name) for name in MINTED_OPS] + EFFECT_OPS


def language_signature_spec() -> str:
    value = {
        "kind": "language_signature",
        "fn_name": "c:c11",
        "sorts": SORTS[:11],
        "operations": CORE_OPS + [spec_filename_for_op(name) for name in MINTED_OPS],
        "equations": EQUATIONS,
        "effect_signatures": EFFECT_SIGS,
    }
    return json.dumps(value, indent=2, sort_keys=False) + "\n"


def mint_sh() -> str:
    def join(items: list[str]) -> str:
        return " ".join(items)

    return (
        "#!/bin/sh\n"
        "set -eu\n"
        "BASE=\"$(CDPATH= cd -- \"$(dirname -- \"$0\")\" && pwd)\"\n"
        "ROOT=\"$(CDPATH= cd -- \"$BASE/../..\" && pwd)\"\n"
        "RUST_DIR=\"$ROOT/implementations/rust\"\n"
        "PROVEKIT=\"$RUST_DIR/target/debug/provekit\"\n"
        "SPEC_DIR=\"$BASE/specs\"\n"
        "CATALOG_REAL=\"$BASE/catalog\"\n"
        "CATALOG_ARG=\"$BASE/dev/../catalog\"\n"
        "CID_FILE=\"$BASE/cids.tsv\"\n"
        "mkdir -p \"$BASE/dev\"\n"
        "rm -rf \"$CATALOG_REAL\"\n"
        "cargo build --manifest-path \"$RUST_DIR/Cargo.toml\" -p provekit-cli -p provekit-ir-compiler-maude\n"
        ": > \"$CID_FILE\"\n"
        "mint_one() {\n"
        "  kind=\"$1\"\n"
        "  spec=\"$2\"\n"
        "  out=$(\"$PROVEKIT\" mint \"$kind\" --spec \"$SPEC_DIR/$spec\" --unsigned --catalog \"$CATALOG_ARG\")\n"
        "  printf '%s\\t%s\\t%s\\n' \"$kind\" \"$spec\" \"$out\" | tee -a \"$CID_FILE\"\n"
        "}\n"
        f"for spec in {join(SORTS)}; do\n"
        "  mint_one sort \"$spec\"\n"
        "done\n"
        f"for spec in {join(op_spec_files())}; do\n"
        "  mint_one algorithm \"$spec\"\n"
        "done\n"
        f"for spec in {join(EQUATIONS)}; do\n"
        "  mint_one equation \"$spec\"\n"
        "done\n"
        f"for spec in {join(EFFECT_SIGS)}; do\n"
        "  mint_one effect-signature \"$spec\"\n"
        "done\n"
        "mint_one language-signature language_signature_c11.spec.json\n"
    )


def is_opaque_kind(name: str) -> bool:
    return name in OPAQUE_EXACT or name.startswith(OPAQUE_PREFIXES) or name.endswith("Attr")


def classify_entry(entry: dict, op_cids: dict[str, str]) -> dict:
    name = entry["cursor_kind"]
    row = {
        "cursor_kind": name,
        "value": entry["value"],
        "alias_of": entry.get("alias_of"),
        "op_name": "c11:opaque",
        "op_cid": op_cids.get("opaque"),
        "arity": 1,
        "child_shape": "unit",
        "classification": "opaque",
        "notes": "Non-lifted cursor kind maps stably to c11:opaque.",
    }
    if entry.get("alias_of"):
        row["notes"] = f"Alias of {entry['alias_of']}; uses the target cursor-kind mapping."
    if name in CORE_CURSOR_MAP:
        op, arity, shape = CORE_CURSOR_MAP[name]
        row.update(
            {
                "op_name": f"c11:{op}",
                "op_cid": op_cids.get(op),
                "arity": arity,
                "child_shape": shape,
                "classification": "existing-core",
                "notes": "Reuses an existing hand-curated C11 core op.",
            }
        )
    elif name in LEAF_CURSOR_MAP:
        op, arity, shape = LEAF_CURSOR_MAP[name]
        row.update(
            {
                "op_name": op,
                "op_cid": None,
                "arity": arity,
                "child_shape": shape,
                "classification": "term-leaf",
                "notes": "Leaf term constructor, not a minted operation.",
            }
        )
    elif name in DISPATCH_CURSOR_MAP:
        cfg = DISPATCH_CURSOR_MAP[name]
        dispatch = {
            "tokens": [
                {
                    "token": token,
                    "op_name": f"c11:{op}",
                    "op_cid": op_cids.get(op),
                }
                for token, op in cfg["token_ops"].items()
            ],
            "fallback": {
                "op_name": f"c11:{cfg['fallback']}",
                "op_cid": op_cids.get(cfg["fallback"]),
            },
        }
        row.update(
            {
                "op_name": cfg["op_name"],
                "op_cid": None,
                "arity": cfg["arity"],
                "child_shape": cfg["child_shape"],
                "classification": "operator-dispatch",
                "notes": "Operator spelling selects one of the listed op CIDs.",
                "operator_dispatch": dispatch,
            }
        )
    elif name in MINTED_CURSOR_MAP:
        op, arity, shape = MINTED_CURSOR_MAP[name]
        row.update(
            {
                "op_name": f"c11:{op}",
                "op_cid": op_cids.get(op),
                "arity": arity,
                "child_shape": shape,
                "classification": "newly-minted",
                "notes": "Generated minimal stable op for this libclang cursor kind.",
            }
        )
    elif name in TRANSPARENT_CURSOR_KINDS:
        row.update(
            {
                "op_name": "passthrough",
                "op_cid": None,
                "arity": 1,
                "child_shape": TRANSPARENT_CURSOR_KINDS[name],
                "classification": "passthrough",
                "notes": "Parser unwraps this cursor kind and emits its child term.",
            }
        )
    elif not is_opaque_kind(name):
        if 100 <= entry["value"] <= 199:
            row.update(
                {
                    "op_name": "c11:unexposed-expr",
                    "op_cid": op_cids.get("unexposed-expr"),
                    "arity": 1,
                    "child_shape": "folded child expressions",
                    "classification": "newly-minted",
                    "notes": "Generated fallback expression op for a C-family expression cursor.",
                }
            )
        elif 200 <= entry["value"] <= 399:
            row.update(
                {
                    "op_name": "c11:unexposed-stmt",
                    "op_cid": op_cids.get("unexposed-stmt"),
                    "arity": 1,
                    "child_shape": "folded child statements",
                    "classification": "newly-minted",
                    "notes": "Generated fallback statement op for a C-family statement cursor.",
                }
            )
    return row


def build_mapping(entries: list[dict], op_cids: dict[str, str], signature_cid: str | None, index_h: Path) -> dict:
    rows = [classify_entry(e, op_cids) for e in entries]
    return {
        "generated_by": GENERATOR,
        "source": source_path_for(index_h),
        "signature_cid": signature_cid,
        "serializers": [
            {
                "op_name": f"c11:{name}",
                "op_cid": op_cids.get(name),
                "render_template": template,
            }
            for name, template in SERIALIZER_TEMPLATES.items()
        ],
        "cursor_kind_count": len(rows),
        "rows": rows,
    }


def c_string(value: str | None) -> str:
    if value is None:
        return "NULL"
    return json.dumps(value)


def generated_c_header() -> str:
    return f"""/* SPDX-License-Identifier: Apache-2.0 */
/* {GENERATED} */
#ifndef PROVEKIT_C11_CURSOR_DISPATCH_GENERATED_H
#define PROVEKIT_C11_CURSOR_DISPATCH_GENERATED_H

#include <stddef.h>

#ifdef PK_C_ENABLE_CLANG_AST
#include <clang-c/Index.h>

typedef struct {{
    enum CXCursorKind cursor_kind;
    const char *cursor_kind_name;
    const char *op_name;
    const char *op_cid;
    int arity;
    const char *child_shape;
    const char *classification;
    const char *notes;
}} pk_c11_cursor_dispatch;

typedef struct {{
    const char *op_name;
    const char *op_cid;
    int serialize_supported;
}} pk_c11_op_dispatch;

const pk_c11_cursor_dispatch *pk_c11_cursor_dispatch_lookup(enum CXCursorKind kind);
const pk_c11_op_dispatch *pk_c11_op_dispatch_lookup(const char *op_name);
const char *pk_c11_signature_cid(void);

#endif

#endif
"""


def generated_c_source(mapping: dict, op_cids: dict[str, str]) -> str:
    rows = [r for r in mapping["rows"] if not r.get("alias_of")]
    signature_cid = mapping.get("signature_cid") or ""
    lines = [
        "/* SPDX-License-Identifier: Apache-2.0 */",
        f"/* {GENERATED} */",
        '#include "c11_cursor_dispatch.generated.h"',
        "",
        "#ifdef PK_C_ENABLE_CLANG_AST",
        "#include <string.h>",
        "",
        "const char *pk_c11_signature_cid(void) {",
        f"    return {c_string(signature_cid)};",
        "}",
        "",
        "const pk_c11_cursor_dispatch *pk_c11_cursor_dispatch_lookup(enum CXCursorKind kind) {",
        "    switch (kind) {",
    ]
    for row in rows:
        lines.extend(
            [
                f"    case {row['cursor_kind']}: {{",
                "        static const pk_c11_cursor_dispatch info = {",
                f"            {row['cursor_kind']},",
                f"            {c_string(row['cursor_kind'])},",
                f"            {c_string(row.get('op_name'))},",
                f"            {c_string(row.get('op_cid'))},",
                f"            {int(row.get('arity') or 0)},",
                f"            {c_string(row.get('child_shape'))},",
                f"            {c_string(row.get('classification'))},",
                f"            {c_string(row.get('notes'))}",
                "        };",
                "        return &info;",
                "    }",
            ]
        )
    lines.extend(
        [
            "    }",
            "    return NULL;",
            "}",
            "",
            "static const pk_c11_op_dispatch PK_C11_OPS[] = {",
        ]
    )
    all_ops = OrderedDict()
    for spec in CORE_OPS:
        name = op_name_for_spec(spec)
        all_ops[name] = op_cids.get(name)
    for name in MINTED_OPS:
        all_ops[name] = op_cids.get(name)
    missing_templates = sorted(set(all_ops) - set(SERIALIZER_TEMPLATES))
    extra_templates = sorted(set(SERIALIZER_TEMPLATES) - set(all_ops))
    if missing_templates or extra_templates:
        raise SystemExit(
            "serializer template mismatch: "
            f"missing={','.join(missing_templates)} extra={','.join(extra_templates)}"
        )
    serializable = set(SERIALIZER_TEMPLATES)
    for name, cid in all_ops.items():
        lines.append(f"    {{{c_string('c11:' + name)}, {c_string(cid)}, {1 if name in serializable else 0}}},")
    lines.extend(
        [
            "    {NULL, NULL, 0}",
            "};",
            "",
            "const pk_c11_op_dispatch *pk_c11_op_dispatch_lookup(const char *op_name) {",
            "    if (op_name == NULL) return NULL;",
            "    for (size_t i = 0; PK_C11_OPS[i].op_name != NULL; i++) {",
            "        if (strcmp(PK_C11_OPS[i].op_name, op_name) == 0) return &PK_C11_OPS[i];",
            "    }",
            "    return NULL;",
            "}",
            "",
            "#endif",
            "",
        ]
    )
    return "\n".join(lines)


def refresh_component_cids(entries: list[dict]) -> dict[Path, str]:
    if not entries:
        return {}
    return {SIG / "component-cids.json": json.dumps(entries, indent=2, sort_keys=False) + "\n"}


def generated_readme(signature_cid: str | None) -> str:
    path = SIG / "README.md"
    old = path.read_text(encoding="utf-8") if path.exists() else "# C11 Language Signature Memento\n"
    cid = signature_cid or "PENDING"
    old = re.sub(
        r"The minted C11 `LanguageSignatureMemento` is:\n\n`[^`]+`",
        f"The minted C11 `LanguageSignatureMemento` is:\n\n`{cid}`",
        old,
    )
    rows = [
        "| Operation | Arity | Result | Contract meaning |",
        "| --- | --- | --- | --- |",
    ]
    for spec in CORE_OPS + [spec_filename_for_op(name) for name in MINTED_OPS]:
        spec_path = SPECS / spec
        if spec_path.exists():
            value = json.loads(spec_path.read_text(encoding="utf-8"))
        elif spec.startswith("op_") and spec.endswith(".spec.json"):
            matches = [name for name in MINTED_OPS if spec_filename_for_op(name) == spec]
            op_name = matches[0] if matches else spec.removeprefix("op_").removesuffix(".spec.json").replace("_", "-")
            value = algorithm_spec(op_name, MINTED_OPS[op_name])
        else:
            continue
        name = value["fn_name"].removeprefix("c11:")
        post = value.get("post", {})
        arity = " x ".join(post.get("arity", [])) or "Unit"
        result = post.get("result") or value.get("return_sort", {}).get("name", "")
        wp = post.get("wp", "")
        rows.append(f"| `{name}` | `{arity}` | `{result}` | {wp} |")
    table = "\n".join(rows)
    if "## Generated Cursor Kind Operations" not in old:
        old = old.replace("## Equations", "## Generated Cursor Kind Operations\n\nAdditional operations below are generated from `enum CXCursorKind` for cursor kinds that do not fit the hand-curated core. Non-lifted declarations, attributes, preprocessing cursors, and non-C-family extensions map to `opaque`.\n\n## Equations")
    old = re.sub(r"## Operations\n\n.*?\n\n## Generated Cursor Kind Operations", f"## Operations\n\n{table}\n\n## Generated Cursor Kind Operations", old, flags=re.S)
    return old


def generated_files(index_h: Path) -> dict[Path, str]:
    op_cids, signature_cid, cid_entries = cids_by_op()
    enum_entries = parse_cursor_enum(index_h)
    mapping = build_mapping(enum_entries, op_cids, signature_cid, index_h)
    files: dict[Path, str] = {}
    files.update(generated_op_specs())
    files[SPECS / "language_signature_c11.spec.json"] = language_signature_spec()
    files[SIG / "mint.sh"] = mint_sh()
    files[MAPPING] = json.dumps(mapping, indent=2, sort_keys=False) + "\n"
    files[C_HDR] = generated_c_header()
    files[C_SRC] = generated_c_source(mapping, op_cids)
    files[SIG / "README.md"] = generated_readme(signature_cid)
    files.update(refresh_component_cids(cid_entries))
    return files


def write_files(files: dict[Path, str]) -> None:
    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        if path.name == "mint.sh" or path.name == "generate-c11-from-cursorkind.py":
            path.chmod(0o755)


def check_files(files: dict[Path, str]) -> int:
    stale = []
    for path, expected in files.items():
        try:
            actual = path.read_text(encoding="utf-8")
        except FileNotFoundError:
            stale.append((path, "missing"))
            continue
        if actual != expected:
            stale.append((path, "stale"))
    if stale:
        for path, reason in stale:
            print(f"{path}: {reason}", file=sys.stderr)
        return 1
    return 0


def print_summary(files: dict[Path, str]) -> None:
    mapping = json.loads(files[MAPPING])
    rows = mapping["rows"]
    counts: dict[str, int] = {}
    for row in rows:
        counts[row["classification"]] = counts.get(row["classification"], 0) + 1
    print(f"source: {mapping['source']}")
    print(f"cursor kinds: {mapping['cursor_kind_count']}")
    for key in sorted(counts):
        print(f"{key}: {counts[key]}")
    print(f"signature_cid: {mapping.get('signature_cid') or 'PENDING'}")


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--index-h",
        help="Path to a CXCursorKind snapshot or clang-c/Index.h for deliberate snapshot updates",
    )
    parser.add_argument("--check", action="store_true", help="Fail if generated files are stale")
    parser.add_argument("--summary", action="store_true", help="Print mapping summary")
    args = parser.parse_args(argv)

    index_h = find_cursor_snapshot(args.index_h)
    files = generated_files(index_h)
    if args.check:
        return check_files(files)
    write_files(files)
    if args.summary:
        print_summary(files)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
