// SPDX-License-Identifier: Apache-2.0
//
// Hand-maintained operation table for the current core subset. The full
// C11 operation set should mint more realization rows, not new machinery.

pub const CORE_OPERATION_SUBSET: &[&str] = &[
    "seq",
    "if",
    "while",
    "return",
    "call",
    "break",
    "continue",
    "skip",
    "eq",
    "lt",
    "le",
    "add",
    "sub",
    "mul",
    "neg",
    "and",
    "or",
    "not",
    "deref",
    "assign",
    "source-unit",
    "cast",
    "bop_eq",
    "bop_ne",
    "bop_lt",
    "bop_le",
    "bop_gt",
    "bop_ge",
    "bop_add",
    "bop_sub",
    "bop_mul",
    "bop_div",
    "bop_mod",
    "bop_shl",
    "bop_shr",
    "bop_bitand",
    "bop_bitor",
    "bop_bitxor",
    "bop_logand",
    "bop_logor",
    "bop_comma",
    "uop_neg",
    "uop_lognot",
    "uop_deref",
    "uop_bitnot",
    "uop_plus",
];

pub const LANGUAGE_MORPHISM_TABLE: &[(&str, &str)] = &[
    ("seq(a, b)", "emit a followed by b"),
    (
        "if(c, a, b)",
        "compile c to eax, cmp eax, 0, branch with je",
    ),
    (
        "while(c, b)",
        "loop label, condition compare, exit branch, body, back edge",
    ),
    ("return(e)", "compile e to eax, ret"),
    (
        "call(f, args)",
        "SysV integer argument registers, call f, result in eax",
    ),
    ("break", "jump to innermost loop exit label"),
    ("continue", "jump to innermost loop head label"),
    ("skip", "emit no instruction"),
    ("eq(a, b)", "cmp a, b followed by sete"),
    ("lt(a, b)", "cmp a, b followed by setl"),
    ("le(a, b)", "cmp a, b followed by setle"),
    ("bop_eq(a, b)", "cmp a, b followed by sete"),
    ("bop_ne(a, b)", "cmp a, b followed by setne"),
    ("bop_lt(a, b)", "cmp a, b followed by setl"),
    ("bop_le(a, b)", "cmp a, b followed by setle"),
    ("bop_gt(a, b)", "cmp a, b followed by setg"),
    ("bop_ge(a, b)", "cmp a, b followed by setge"),
    ("add(a, b)", "add eax, ecx"),
    ("sub(a, b)", "sub eax, ecx"),
    ("mul(a, b)", "imul eax, ecx"),
    ("bop_add(a, b)", "add eax, ecx"),
    ("bop_sub(a, b)", "sub eax, ecx"),
    ("bop_mul(a, b)", "imul eax, ecx"),
    ("bop_div(a, b)", "cdq; idiv ecx; quotient in eax"),
    ("bop_mod(a, b)", "cdq; idiv ecx; remainder edx moved to eax"),
    ("bop_shl(a, b)", "shl eax, cl"),
    ("bop_shr(a, b)", "sar eax, cl"),
    ("bop_bitand(a, b)", "and eax, ecx"),
    ("bop_bitor(a, b)", "or eax, ecx"),
    ("bop_bitxor(a, b)", "xor eax, ecx"),
    ("neg(a)", "neg eax"),
    ("uop_neg(a)", "neg eax"),
    ("and(a, b)", "normalize to 0 or 1, and eax, ecx"),
    ("or(a, b)", "normalize to 0 or 1, or eax, ecx"),
    ("bop_logand(a, b)", "short-circuit to 0 or 1"),
    ("bop_logor(a, b)", "short-circuit to 0 or 1"),
    ("bop_comma(a, b)", "compile a then compile b"),
    ("not(a)", "cmp eax, 0 followed by sete"),
    ("uop_lognot(a)", "cmp eax, 0 followed by sete"),
    ("uop_bitnot(a)", "not eax"),
    ("uop_plus(a)", "compile a"),
    ("var(x)", "move from assigned SysV argument register"),
    ("const(i)", "mov eax, immediate"),
    ("deref(p)", "load DWORD PTR [address]"),
    ("uop_deref(p)", "load DWORD PTR [address]"),
    (
        "source-unit(bytes, term)",
        "project to term before lowering",
    ),
    (
        "cast(target_type,value)",
        "target_type is type metadata; lower value in the i32 subset",
    ),
    (
        "assign(x, e)",
        "compile e and store into x or DWORD PTR [address]",
    ),
];
